const crypto=require('crypto');
const {healPlayer,healingMultiplier}=require('../status/status-manager');
const {rewardChoice}=require('./danger-system');
const {addEquipment}=require('../equipment/equipment-manager');
const {persist}=require('../room/room-manager');
function healAmount(room,p){return Math.round(p.maxHp*[.34,.28,.24][Math.min(2,room.areaIndex||0)]);}
function options(room,player){return [{id:'supply',label:'補給',desc:'獲得 1 件隨機武器、防具、飾品或消耗品；背包滿時轉入共享背包。',rewardHint:'1 件裝備或消耗品，品質受目前危險度影響。'}, {id:'breather',label:'小歇',desc:`恢復自己 ${Math.min(player.maxHp-player.hp,Math.round(healAmount(room,player)*healingMultiplier(player)))} HP。`},...room.players.filter(p=>p.id!==player.id&&p.hp>0).map(p=>({id:'heal:'+p.id,label:'替 '+p.name+' 療傷',desc:`恢復隊友 ${Math.min(p.maxHp-p.hp,Math.round(healAmount(room,p)*healingMultiplier(p)))} HP；這會使用你在本節點的選擇。`}))];}
function open(room){room.restChoices={};room.currentEvent={id:'rest-'+crypto.randomUUID(),name:'休整',scope:'personal',sceneType:'rest',description:'各自選擇補給、小歇或替隊友療傷；每人一次，不需擲骰，也不改變危險度。',optionsByPlayer:Object.fromEntries(room.players.filter(p=>p.connected&&p.hp>0).map(p=>[p.id,options(room,p)])),options:[]};persist();}
function choose(room,player,optionId){if(room.phase!=='exploration'||room.currentEvent?.sceneType!=='rest'||room.eventResult||player.hp<=0||!player.connected)throw new Error('目前不能選擇休整行動。');if(room.restChoices?.[player.id])throw new Error('你已完成本次休整選擇。');const selected=options(room,player).find(o=>o.id===optionId);if(!selected)throw new Error('無效的休整選項。');const result={playerId:player.id,sinner:require('../status/status-manager').sinnerOf(player)?.name||player.name,degree:'rest',choice:selected.label,healed:0};if(optionId==='supply'){const reward=rewardChoice(room,player);if(reward.slot)addEquipment(player,reward);else if(player.inventory.length<4)player.inventory.push(reward);else room.sharedInventory.push(reward);result.loot={item:reward};}else {const target=optionId==='breather'?player:room.players.find(p=>p.id===optionId.slice(5)&&p.hp>0);if(!target)throw new Error('隊友目前無法接受療傷。');result.healed=healPlayer(target,healAmount(room,target));result.targetName=target.name;room.visualEffect={id:crypto.randomUUID(),type:'heal',playerId:target.id,amount:result.healed};}room.restChoices[player.id]=result;room.currentEvent.optionsByPlayer=Object.fromEntries(room.players.filter(p=>p.hp>0).map(p=>[p.id,options(room,p)]));complete(room);persist();return result;}
function complete(room){if(room.currentEvent?.sceneType!=='rest'||room.eventResult)return;const active=room.players.filter(p=>p.connected&&p.hp>0);if(!active.length||active.some(p=>!room.restChoices?.[p.id]))return;room.eventResult={degree:'personal',scope:'personal',rest:true,personalResults:Object.values(room.restChoices),damage:0,dangerDelta:0};const node=room.exploration.route[room.exploration.position];node.resolved=true;require('./route-generator').primeFogAfterResolution(room);}
module.exports={healAmount,options,open,choose,complete};
