const crypto=require('crypto');
const C=require('../../shared/cards');
const {SINNERS,SINNER_SKILLS,applyUpgrade}=require('../../shared/game-data');
const {statFor,healPlayer}=require('../status/status-manager');
function shuffle(list){for(let i=list.length-1;i>0;i--){const j=crypto.randomInt(i+1);[list[i],list[j]]=[list[j],list[i]];}return list;}
function instance(card){return {...JSON.parse(JSON.stringify(card)),uid:crypto.randomUUID()};}
function ensureCollection(player){player.explorationCards=(Array.isArray(player.explorationCards)?player.explorationCards:[]).filter(id=>C.COLLECTIBLE.some(c=>c.id===id)).slice(0,24);return player.explorationCards;}
function grantCard(player,card){const ids=ensureCollection(player);if(ids.length>=24)return null;const def=C.COLLECTIBLE.find(c=>c.id===(typeof card==='string'?card:card?.id));if(!def)return null;ids.push(def.id);return {...def};}
function deckFor(player){const removed=new Set(player.removedDeckCards||[]);const a=C.personalAbility(player.sinnerId);return [...C.initialCards(player.sinnerId),...C.weaponCards(player.equipment?.weapon,player.sinnerId),...C.ABILITIES.slice(0,2).map(x=>({...x,kind:'ability',source:'通用'})),...(a?[{...a,kind:'ability',source:'罪人限定'}]:[]),...ensureCollection(player).map(id=>({...C.COLLECTIBLE.find(c=>c.id===id),source:'探索'}))].filter(c=>c.source==='探索'||!removed.has(c.id));}
function starterSkill(player){const first=SINNER_SKILLS.find(s=>s.sinnerId===player.sinnerId);player.learnedSkills=Array.isArray(player.learnedSkills)?player.learnedSkills:[];if(first&&!player.learnedSkills.length)player.learnedSkills.push(first.id);}
function draw(deck,count){const drawn=[];for(let i=0;i<count&&deck.hand.length<8;i++){if(!deck.draw.length){if(!deck.discard.length)break;deck.draw=shuffle(deck.discard.splice(0));deck.shuffles++;}const card=deck.draw.shift();deck.hand.push(card);drawn.push(card);}return drawn;}
function initialize(room){const combat=room.combat;combat.cardMode=true;combat.cardDecks={};combat.roundGuard={};combat.selections={};for(const p of room.players.filter(p=>p.hp>0)){starterSkill(p);const deck={draw:shuffle(deckFor(p).map(instance)),discard:[],hand:[],abilityUses:0,copies:0,shuffles:0,round:combat.round};combat.cardDecks[p.id]=deck;draw(deck,5);}return combat;}
function ensureDeck(room,player){if(!room.combat.cardMode)initialize(room);const deck=room.combat.cardDecks?.[player.id];if(!deck)throw new Error('此玩家沒有戰鬥牌組。');return deck;}
function assertPlayable(room,player){if(room.phase!=='exploration'||!room.combat||room.combat.ended||player.hp<=0||!player.connected)throw new Error('目前不能出牌。');const deck=ensureDeck(room,player);if(room.combat.selections?.[player.id]?.confirmed)throw new Error('請先取消確認再修改卡牌。');return deck;}
function skills(player){const list=SINNER_SKILLS.filter(s=>s.sinnerId===player.sinnerId);return list.map((s,i)=>({...applyUpgrade(s,player.skillUpgrades?.[s.id]),cardRequirement:C.requirement(s,i)})).filter(s=>player.learnedSkills?.includes(s.id));}
function validatePicks(deck,picks){if(!Array.isArray(picks)||picks.length>8)throw new Error('出牌資料不正確。');const ids=new Set();return picks.map(p=>{if(!p||typeof p.uid!=='string'||typeof p.flipped!=='boolean'||ids.has(p.uid))throw new Error('重複或無效的卡牌。');const card=deck.hand.find(c=>c.uid===p.uid);if(!card||card.kind!=='action')throw new Error('只能選擇手中的行動牌。');ids.add(p.uid);return {uid:p.uid,flipped:p.flipped};});}
function selection(room,player,{picks=[],targetId=null,partId=null,skillId=null}){const deck=assertPlayable(room,player),valid=validatePicks(deck,picks),totals=C.totals(deck.hand,valid);const enemy=(room.combat.enemies||[]).find(e=>e.instanceId===targetId&&e.currentHp>0)||(room.combat.enemies||[]).find(e=>e.currentHp>0);const part=enemy?.parts?.find(p=>p.id===partId&&!p.destroyed);if(skillId){const skill=skills(player).find(s=>s.id===skillId);if(!skill||!C.meets(totals.counts,skill.cardRequirement))throw new Error('技能的罪孽卡牌條件尚未達成。');}const auto=skills(player).filter(s=>C.meets(totals.counts,s.cardRequirement)).sort((a,b)=>Object.values(b.cardRequirement).reduce((x,y)=>x+y,0)-Object.values(a.cardRequirement).reduce((x,y)=>x+y,0)||b.cost-a.cost)[0];const matched=skills(player).filter(s=>C.meets(totals.counts,s.cardRequirement)),chosen=matched[0]?.id||null;const selected={actionId:'cards',picks:valid,targetId:enemy?.instanceId||null,partId:part?.id||null,skillId:chosen,skillIds:matched.map(s=>s.id),confirmed:false,points:totals.points,counts:totals.counts,label:`${valid.length} 張牌${chosen?' · '+matched.map(s=>s.name).join('＋'):''}`};const {estimateDamage}=require('../combat/combat-actions');const actionsNow=actions(room,player,selected);const attackPreviews=actionsNow.filter(a=>!['card-guard','heal','team-buff'].includes(a.kind)).flatMap(a=>['aoe','aoe-debuff'].includes(a.kind)?room.combat.enemies.filter(e=>e.currentHp>0).map(e=>estimateDamage(room,player,a,e,null)):[estimateDamage(room,player,a,enemy,part)]);selected.preview={attackDice:attackPreviews.reduce((sum,p)=>sum+Math.min(16,Math.max(1,Math.round((p.min+p.max)/7))),0),min:attackPreviews.reduce((sum,p)=>sum+p.min,0),max:attackPreviews.reduce((sum,p)=>sum+p.max,0),hit:100,shield:actionsNow.reduce((sum,a)=>sum+Number(a.guardDice||0),0)};room.combat.selections[player.id]=selected;return selected;}
function useAbility(room,player,{uid,costId,targetId}){const deck=assertPlayable(room,player),card=deck.hand.find(c=>c.uid===uid);if(!card||card.kind!=='ability')throw new Error('這不是手中的能力牌。');if(card.sinnerId&&card.sinnerId!==player.sinnerId)throw new Error('這不是此罪人的能力牌。');if(deck.abilityUses>=2)throw new Error('每回合最多使用 2 張能力牌。');const reserved=new Set((room.combat.selections[player.id]?.picks||[]).map(p=>p.uid));const needCost=['shuffle','recover','stack','copy'].includes(card.effect),cost=deck.hand.find(c=>c.uid===costId&&c.uid!==uid&&!reserved.has(c.uid));if(needCost&&!cost)throw new Error('請選擇 1 張未出的手牌作為棄牌代價。');let target=null;
 if(card.effect==='recover'){target=deck.discard.find(c=>c.uid===targetId&&c.kind==='action');if(!target)throw new Error('請選擇回收堆的行動牌。');}
 if(card.effect==='stack'){target=deck.draw.find(c=>c.uid===targetId&&c.kind==='action');if(!target)throw new Error('請選擇抽牌堆的行動牌。');}
 if(card.effect==='copy'){target=deck.hand.find(c=>c.uid===targetId&&c.kind==='action'&&c.uid!==costId);if(!target)throw new Error('請選擇另一張手中行動牌。');if(deck.copies>=2)throw new Error('每場戰鬥最多複製 2 張牌。');}
 
 deck.hand=deck.hand.filter(c=>c.uid!==uid&&c.uid!==cost?.uid);deck.discard.push(card);if(cost)deck.discard.push(cost);deck.abilityUses++;
 if(card.effect==='draw')draw(deck,1);
 if(card.effect==='shuffle'){shuffle(deck.draw);draw(deck,1);}
 if(card.effect==='recover'){deck.discard=deck.discard.filter(c=>c.uid!==target.uid);deck.hand.push(target);}
 if(card.effect==='stack'){deck.draw=deck.draw.filter(c=>c.uid!==target.uid);deck.draw.unshift(target);}
 if(card.effect==='copy'){deck.hand.push({...instance(target),temporary:true,source:'戰鬥複製'});deck.copies++;}
 if(card.shield)player.temporaryShield=Math.min(99,Number(player.temporaryShield||0)+card.shield);const healed=card.heal?healPlayer(player,card.heal):0;if(healed)room.visualEffect={id:crypto.randomUUID(),type:'heal',playerId:player.id,amount:healed};room.combat.log.push({round:room.combat.round,text:`${player.name} 使用「${card.name}」。`});const old=room.combat.selections[player.id];if(old)selection(room,player,old);return {name:card.name,drawn:deck.hand.length};}
function nextRound(room){room.combat.roundGuard={};for(const p of room.players){const deck=room.combat.cardDecks?.[p.id];if(!deck)continue;const used=new Set((room.combat.selections?.[p.id]?.confirmed?room.combat.selections[p.id].picks||[]:[]).map(x=>x.uid));deck.discard.push(...deck.hand.filter(c=>used.has(c.uid)));deck.hand=deck.hand.filter(c=>!used.has(c.uid));deck.abilityUses=0;deck.round=room.combat.round;if(p.hp>0){draw(deck,Math.max(0,5-deck.hand.length));draw(deck,Math.min(2,Number(deck.nextDrawBonus||0)));}deck.nextDrawBonus=0;}}
function actions(room,player,selected){const deck=ensureDeck(room,player);const picks=validatePicks(deck,selected.picks||[]),{points}=C.totals(deck.hand,picks),stat=Math.max(1,statFor(player,'combat')),attackSum=points.slash+points.blunt+points.pierce,out=[];
 for(const type of ['slash','blunt','pierce'])if(points[type]>0){const base=Math.round(points[type]*1.55+stat*.55*(points[type]/attackSum));out.push({id:'card-'+type,label:`${C.TYPES[type]}擊 · ${points[type]} 點`,kind:'card-attack',damageType:type,soundType:type,stat:'combat',power:base/stat,cardBase:base});}
 if(points.guard>0)out.unshift({id:'card-guard',label:`防禦 · ${points.guard} 點`,kind:'card-guard',guardDice:require('../combat/opposed-dice').guardCount(points.guard,statFor(player,'stability'))});
 for(const chosen of skills(player).filter(s=>C.meets(C.totals(deck.hand,picks).counts,s.cardRequirement))){const {counts}=C.totals(deck.hand,picks);if(!C.meets(counts,chosen.cardRequirement))throw new Error('技能條件不足。');out.push({...chosen,kind:chosen.kind==='team-buff'&&Number(chosen.power)>0?'card-buff-attack':chosen.kind,teamBuff:chosen.kind==='team-buff',label:chosen.name,skillId:chosen.id,cardSkill:true});}return out;
}
module.exports={shuffle,instance,ensureCollection,grantCard,deckFor,draw,initialize,ensureDeck,starterSkill,assertPlayable,selection,useAbility,nextRound,actions,skills,validatePicks};
