const crypto=require('crypto'),C=require('../../shared/cards');
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=crypto.randomInt(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;};
function draw(d,n){for(let i=0;i<n&&d.hand.length<Number(d.limit||8);i++){if(!d.draw.length){if(!d.discard.length)break;d.draw=shuffle(d.discard.splice(0));d.shuffles++;}d.hand.push(d.draw.shift());}}
function deckFor(e){const seed=[...(e.baseName||e.name)].reduce((n,c)=>n+c.charCodeAt(0),0),types=['slash','blunt','pierce'],sins=Object.keys(C.SINS),type=e.damageType||types[seed%3];return [...Array.from({length:12},(_,i)=>({id:`enemy-${i}`,name:'敵方行動',kind:'action',source:'敵方',faces:[{sin:sins[(seed+(i%3))%7],type,value:1+i%2},{sin:sins[(seed+(i%3))%7],type:'guard',value:1+i%2}]})),...C.ABILITIES.slice(0,3).map(c=>({...c,kind:'ability',source:'敵方'}))].map(c=>({...c,uid:crypto.randomUUID()}));}
function plan(e,combat){combat.enemyCardDecks=combat.enemyCardDecks||{};let d=combat.enemyCardDecks[e.instanceId];if(!d){d={draw:shuffle(deckFor(e)),discard:[],hand:[],round:0,shuffles:0,abilityUses:0};combat.enemyCardDecks[e.instanceId]=d;}if(d.round===combat.round){const sums=C.totals(d.hand,d.plan.picks);d.plan.cards=d.plan.picks.map(p=>{const card=d.hand.find(c=>c.uid===p.uid);return {...card,flipped:p.flipped};});Object.assign(d.plan,{points:sums.points,counts:sums.counts,attackColors:sums.attackColors,guardColors:sums.guardColors,attackFaces:sums.attackFaces,guardFaces:sums.guardFaces});return d.plan;}if(d.round){const used=new Set(d.plan.picks.map(p=>p.uid));d.discard.push(...d.hand.filter(c=>used.has(c.uid)));d.hand=d.hand.filter(c=>!used.has(c.uid));}d.limit=require('../status/battle-status').handLimit(e);require('../status/battle-status').trimHand(e,d);draw(d,Math.max(0,require('../status/battle-status').handTarget(e)-d.hand.length));d.abilityUses=0;const abilities=[];
 for(const card of [...d.hand].filter(c=>c.kind==='ability')){if(d.abilityUses>=2)break;const cost=d.hand.find(c=>c.kind==='action'),target=d.discard.find(c=>c.kind==='action');if(card.effect!=='draw'&&!cost||card.effect==='recover'&&!target)continue;d.hand=d.hand.filter(c=>c.uid!==card.uid&&!(card.effect!=='draw'&&c.uid===cost.uid));d.discard.push(card);if(card.effect!=='draw')d.discard.push(cost);if(card.effect==='shuffle')shuffle(d.draw);if(card.effect==='recover'){d.discard=d.discard.filter(c=>c.uid!==target.uid);d.hand.push(target);}else draw(d,1);d.abilityUses++;abilities.push(card.name);}
 const hand=d.hand.filter(c=>c.kind==='action'),guardCount=e.currentHp/e.maxHp<.35?2:1,chosen=hand.slice(0,5),picks=chosen.map((c,i)=>({uid:c.uid,flipped:i>=chosen.length-guardCount})),sums=C.totals(d.hand,picks);d.round=combat.round;d.plan={picks,points:sums.points,counts:sums.counts,attackColors:sums.attackColors,guardColors:sums.guardColors,attackFaces:sums.attackFaces,guardFaces:sums.guardFaces,cards:chosen.map(c=>({...c,flipped:picks.find(p=>p.uid===c.uid).flipped})),abilities};return d.plan;
}
module.exports={plan,draw,deckFor};
