(()=>{
 const C=KBMCards,esc=escapeHtml;const pileOpen={draw:false,discard:false};const selectable=room=>!room.combat?.flowVersion||['attack','defense'].includes(room.combat.phase);const applies=(room,f)=>!room.combat?.flowVersion||(room.combat.phase==='attack'?f.type!=='guard':f.type==='guard');let key='',rotations=new Map(),focused=null,pendingCards=false,optimistic=null;
 const icons={slash:'<path d="M12 3 16 7 14 16H10L8 7ZM8 17H16M12 17V21M10 21H14"/>',blunt:'<path d="M5 4H19V11H5ZM11 11V21H13V11M8 4V11M16 4V11"/>',pierce:'<path d="M3 7H18V12H9L7 18H4L5 12H3ZM18 8H22V11H18M10 12V15H14V12"/>',guard:'<path d="m12 3 8 3v7c0 4-5 7-8 9-3-2-8-5-8-9V6zm0 3v12"/>'};
 function icon(type){return `<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${icons[type]||icons.guard}</svg>`;}
 function colorText(value){const names=Object.values(C.SINS),pattern=new RegExp(names.map(s=>s.name).join("|"),"g");return esc(value).replace(pattern,name=>`<span class="sin-word" style="--sin:${names.find(s=>s.name===name).color}">${name}</span>`);}
 function conditions(req){if(req==null)return '<span>條件未設定</span>';return Object.entries(req||{}).map(([sin,n])=>`<span class="sin-cost" style="--sin:${C.SINS[sin].color}">${esc(C.SINS[sin].name)} ${typeof n==='number'?n+'點（累計）':n.exact!=null?'單張＝'+n.exact:'單張≥'+n.min}</span>`).join('');}
 function sourceClass(source){return source==='初始'?'initial':source==='武器'?'weapon':source==='戰鬥複製'?'copy':'explore';}
 function half(f,position){return `<div class="card-half ${position} type-${f.type}" style="--sin:${C.SINS[f.sin].color}"><div class="card-edge"><span>${C.SINS[f.sin].name}</span><em>${C.TYPES[f.type]}</em></div><div class="card-value"><b>${f.value}</b>${icon(f.type)}</div></div>`;}
 const cardName=c=>c.kind==='ability'?c.name:`${c.name} · ${c.faces.map(f=>`${C.SINS[f.sin].name} ${C.TYPES[f.type]}${f.value}`).join(' / ')}`;
 function skillTag(s){const cls=s.skillClass==='攻擊技能'?'attack':s.skillClass==='特殊技能'?'special':s.skillClass==='防禦技能'?'defense':'support';return `<span class="skill-category ${cls}">${esc(s.skillClass||'技能')}</span>`;}
 function requirementLine(s){const attack=C.isOutputSkill(s);return `條件: <span class="card-side-tag ${attack?'attack':'defense'}">${attack?'攻擊卡':'防禦卡'}</span> ${conditions(s.cardRequirement)}`;}
 function selected(room){return optimistic?.roomId===room.id&&optimistic.phaseSerial===room.combat?.phaseSerial?optimistic:room.combat?.selections?.[state.selfId]||{picks:[]};}
 function send(room,picks,extra={}){if(pendingCards)return;const old=selected(room),data={roomId:room.id,picks,targetId:old.targetId||room.combat.enemies.find(e=>e.currentHp>0)?.instanceId,partId:old.partId||null,...extra};pendingCards=true;optimistic={...old,...data,phaseSerial:room.combat.phaseSerial,preview:null};render(room);confirm(room);socket.emit('combat:cards',data,res=>{pendingCards=false;optimistic=null;if(!res?.ok)alert(res?.error||'操作失敗。');if(state.room?.combat){render(state.room);confirm(state.room);}});}
 function target(room,targetId,partId=null){send(room,selected(room).picks||[],{targetId,partId});}
 function play(room,uid){const deck=room.combat.cardDecks?.[state.selfId],card=deck?.hand.find(c=>c.uid===uid);if(!card)return;if(card.kind==='ability')return ability(room,card);const picks=[...(selected(room).picks||[])];const index=picks.findIndex(p=>p.uid===uid);if(index>=0)picks.splice(index,1);else {picks.push({uid,flipped:!!rotations.get(uid)});}send(room,picks);}
 function rotate(room,uid){const flipped=!rotations.get(uid);rotations.set(uid,flipped);const picks=selected(room).picks||[];if(picks.some(p=>p.uid===uid))send(room,picks.map(p=>p.uid===uid?{...p,flipped}:p));else render(room);}
 function ability(room,card){
  document.getElementById('abilityDialog')?.remove();const deck=room.combat.cardDecks[state.selfId],reserved=new Set((selected(room).picks||[]).map(p=>p.uid)),costs=deck.hand.filter(c=>c.uid!==card.uid&&!reserved.has(c.uid));
  const targets=card.effect==='recover'?deck.discard.filter(c=>c.kind==='action'):card.effect==='stack'?deck.draw.filter(c=>c.kind==='action'):card.effect==='copy'?deck.hand.filter(c=>c.kind==='action'):[];
  const needCost=C.abilityNeedsCost(card),needEnemy=C.abilityNeedsEnemy(card),options=list=>list.map(c=>`<option value="${esc(c.uid)}">${esc(cardName(c))}</option>`).join('');
  const dialog=document.createElement('dialog');dialog.id='abilityDialog';dialog.className='ability-dialog';dialog.innerHTML=`<form><strong>${esc(card.name)}</strong><p>${esc(card.description)}</p>${needCost?`<label>棄牌代價<select name="cost" required><option value="">請選擇未出的手牌</option>${options(costs)}</select></label>`:''}${['recover','stack','copy'].includes(card.effect)?`<label>${card.effect==='recover'?'回收堆':card.effect==='stack'?'抽牌堆':'複製目標'}<select name="target" required><option value="">請選擇行動牌</option>${options(targets)}</select></label>`:''}${needEnemy?`<label>敵方目標<select name="enemy" required>${room.combat.enemies.filter(e=>e.currentHp>0).map(e=>`<option value="${esc(e.instanceId)}" ${e.instanceId===selected(room).targetId?'selected':''}>${esc(e.name)}</option>`).join('')}</select></label>`:''}<small>能力牌每回合最多 2 張；沒有罪孽顏色。${card.battleLimit?`本場最多 ${card.battleLimit} 次。`:''}</small><div class="dialog-actions"><button type="button" data-cancel>取消</button><button type="submit">使用能力牌</button></div><p class="ability-error" role="alert"></p></form>`;
  document.body.appendChild(dialog);dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();let busy=false;
  dialog.querySelector('form').onsubmit=e=>{e.preventDefault();if(busy)return;busy=true;dialog.querySelector('[type=submit]').disabled=true;const costId=dialog.querySelector('[name=cost]')?.value,targetId=dialog.querySelector('[name=target]')?.value,enemyId=dialog.querySelector('[name=enemy]')?.value;socket.emit('combat:ability',{roomId:room.id,uid:card.uid,costId,targetId,enemyId},res=>{if(res?.ok)dialog.close();else {busy=false;dialog.querySelector('[type=submit]').disabled=false;dialog.querySelector('.ability-error').textContent=res?.error||'無法使用。';}});};dialog.showModal();
 }
 function pileMarkup(deck){return ['draw','discard'].filter(k=>pileOpen[k]).map(k=>`<section class="card-pile-view"><strong>${k==='draw'?'抽牌堆（排列不代表抽取順序）':'回收堆'}</strong><div class="pile-card-grid">${[...deck[k]].sort((a,b)=>JSON.stringify(a.faces||a.name).localeCompare(JSON.stringify(b.faces||b.name))).map(card=>`<article class="pile-card ${card.kind==='ability'?'ability-card':''}">${card.kind==='action'?half(card.faces[0],'top')+half(card.faces[1],'bottom'):`<div class="pile-ability"><b>◇ ${esc(card.name)}</b><p>${esc(card.description)}</p>${card.battleLimit?`<small>每場 ${card.battleLimit} 次</small>`:''}</div>`}</article>`).join('')||'<span>目前沒有卡牌</span>'}</div></section>`).join('');}
 function render(room){
  const root=document.getElementById('combatOptions'),player=room.players.find(p=>p.id===state.selfId),deck=room.combat?.cardDecks?.[player?.id];if(!root||!player)return;root.classList.add('card-combat-options');if(!deck){root.innerHTML='<p>正在準備牌組…</p>';return;}
  const newKey=`${room.id}:${room.run}:${room.areaIndex}:${room.exploration.position}:${room.combat.phaseSerial||deck.round}`;if(key!==newKey){key=newKey;rotations.clear();focused=null;}
  const selection=selected(room),picks=selection.picks||[],played=new Set(picks.map(p=>p.uid)),locked=pendingCards||!!selection.confirmed||player.serverControl>0||player.hp<=0||room.phase!=='exploration'||!selectable(room);
  picks.forEach(p=>rotations.set(p.uid,p.flipped));const sums=C.totals(deck.hand,picks.filter(p=>applies(room,C.face(deck.hand.find(c=>c.uid===p.uid),p.flipped))));const available=(state.gameData.sinnerSkills||[]).filter(s=>player.learnedSkills?.includes(s.id));
  root.innerHTML=`<div class="card-deck-bar"><strong>手牌 ${deck.hand.length-(selection.confirmed?picks.length:0)}/${deck.limit||8}</strong>${['draw','discard'].map(k=>`<button type="button" data-pile="${k}" aria-expanded="${pileOpen[k]}">${k==='draw'?'抽牌':'回收'} ${deck[k].length} ${pileOpen[k]?'▴':'▾'}</button>`).join('')}<span>能力 ${deck.abilityUses}/2</span></div>${pileMarkup(deck)}
  <div class="card-hand" aria-label="未出戰鬥手牌">${deck.hand.filter(c=>!selection.confirmed||!played.has(c.uid)).map(card=>{
   const staged=played.has(card.uid),isAbility=card.kind==='ability',flip=!!rotations.get(card.uid),exhausted=isAbility&&card.battleLimit&&Number(deck.personalUses?.[card.id]||0)>=card.battleLimit;
   return `<div class="hand-card ${isAbility?'ability-card':'is-action'} ${focused===card.uid?'focused':''} ${staged?'staged':''}" data-hand-card="${esc(card.uid)}"><button type="button" class="card-surface ${flip?'flipped':''}" data-card-focus="${esc(card.uid)}" aria-pressed="${staged}" aria-label="${esc(cardName(card))}${isAbility?'':'，點擊旋轉'}" ${locked?'disabled':''}>${isAbility?`<div class="ability-face"><span>能力牌</span><b>◇</b><strong>${esc(card.name)}</strong><small>${esc(card.description)}</small></div>`:`${half(card.faces[0],'top')}<div class="card-center" aria-hidden="true"></div>${half(card.faces[1],'bottom')}`}</button><div class="card-controls"><button type="button" data-card-play="${esc(card.uid)}" ${locked||exhausted||(isAbility?deck.abilityUses>=2:!staged&&!applies(room,C.face(card,flip)))?'disabled':''}>${exhausted?'本場已用完':isAbility?'使用':staged?'取消':'選擇'}</button></div></div>`;
  }).join('')||'<p class="empty-hand">已確認出牌，等待回合結算。</p>'}</div>
  <p class="card-gesture-note">點擊行動牌旋轉，再按選擇；確認出牌後才移除。</p><div class="card-inspection">${focused?esc(cardName(deck.hand.find(c=>c.uid===focused)||{kind:'ability',name:''})):'一組攻守共用手牌，兩回合完成後才補到六張。'}</div>
  <div class="card-play-summary ${picks.length?'has-selection':''}"><b>${selection.confirmed?'✓ 已確認':'已選'} ${picks.length} 張</b><span>${Object.entries(sums.points).filter(([,v])=>v).map(([type,value])=>`${C.TYPES[type]} ${value}`).join(' · ')||'可空過回合'}</span>${selection.preview?.attackDice?`<span>攻擊 ${selection.preview.attackDice} 骰</span>`:selection.preview?.shield?`<span>防禦 ${selection.preview.shield} 骰</span>`:''}<div class="played-undo">${picks.map((pick,i)=>`<button type="button" data-card-undo="${esc(pick.uid)}" ${locked?'disabled':''}>撤回 ${i+1}</button>`).join('')}</div></div>
  <div class="card-skill-conditions"><strong>罪孽共鳴 · 達成條件的技能各發動一次</strong>${available.map(skill=>{const met=selectable(room)&&C.canUse(sums,skill)&&!(player.statuses||[]).some(s=>s.id==='sealed');return `<div class="card-skill-condition ${met?'met':''}"><span><b>${esc(skill.name)}</b><small>${requirementLine(skill)}</small></span><em>${met?'可發動':'未達成'}</em></div>`;}).join('')||'<p>尚未學會技能。</p>'}</div>`;
  root.querySelectorAll('[data-pile]').forEach(button=>button.onclick=()=>{pileOpen[button.dataset.pile]=!pileOpen[button.dataset.pile];render(room);});
  root.querySelectorAll('[data-card-focus]').forEach(button=>button.onclick=()=>{focused=button.dataset.cardFocus;const card=deck.hand.find(c=>c.uid===focused);if(card.kind==='action')rotate(room,card.uid);else {root.querySelector('.card-inspection').textContent=card.description;}});
  root.querySelectorAll('[data-card-play]').forEach(button=>button.onclick=()=>play(room,button.dataset.cardPlay));root.querySelectorAll('[data-card-undo]').forEach(button=>button.onclick=()=>send(room,picks.filter(p=>p.uid!==button.dataset.cardUndo)));
 }
 let pendingConfirm=null;
 function confirm(room){
  const root=document.getElementById('confirmBar'),s=selected(room),p=room.players.find(x=>x.id===state.selfId);if(!root)return;
  if(!root.querySelector('#confirmCombat')){
   root.innerHTML='<button type="button" id="confirmCombat"></button><button type="button" id="cancelCombatConfirm" class="secondary hidden">取消確認</button><span></span>';
   const submit=(event,confirmed)=>{
    const current=state.room,selection=selected(current||{}),button=event.currentTarget;
    if(!current?.combat||current.combat.ended||pendingConfirm||button.disabled||!!selection.confirmed!==confirmed)return;
    pendingConfirm={roomId:current.id};confirm(current);
    socket.emit(confirmed?'combat:cancel-confirm':'combat:confirm',{roomId:current.id},res=>{pendingConfirm=null;if(state.room?.combat)confirm(state.room);if(!res?.ok)alert(res?.error||'操作失敗。');});
   };
   root.querySelector('#confirmCombat').addEventListener('click',event=>submit(event,false));
   root.querySelector('#cancelCombatConfirm').addEventListener('click',event=>submit(event,true));
  }
  const button=root.querySelector('#confirmCombat'),cancel=root.querySelector('#cancelCombatConfirm'),busy=!!pendingConfirm;
  button.classList.toggle('hidden',!!s.confirmed);cancel.classList.toggle('hidden',!s.confirmed);
  button.disabled=pendingCards||busy||p?.serverControl>0||p?.hp<=0||room.phase!=='exploration'||!!room.combat?.ended||!selectable(room);cancel.disabled=pendingCards||busy||p?.serverControl>0||p?.hp<=0||room.phase!=='exploration'||!!room.combat?.ended||!selectable(room);
  root.setAttribute('aria-busy',String(busy));
  button.textContent=busy?'確認中…':s.picks?.length?'確認出牌':'不出牌，結束回合';
  root.querySelector('span').textContent=p?.serverControl>0?`治療過度：伺服器接管中（剩餘 ${p.serverControl} 回合）。`:s.confirmed?'等待其他玩家中...':'';
 }

 window.KBMCardUI={render,confirm,target,icon,conditions,colorText,half,skillTag,requirementLine};
})();
