(()=>{
 let lastEffect=null,lastRoom=null;
 const targetEl=id=>id?document.querySelector(`[data-combat-target="${CSS.escape(id)}"]`):null;
 const playerEls=id=>[...document.querySelectorAll(`[data-player-id="${CSS.escape(id)}"]`),...(id===state.selfId?[document.querySelector('#mySinner .sinner-profile')]:[])].filter(Boolean);
 function effect(target,type,text=''){if(!target)return;const fx=document.createElement('div');fx.className=`battle-effect effect-${type}`;fx.innerHTML=type==='heal'?'<i>+</i><i>+</i><i>+</i>':type==='slash'?'<i></i><i></i>':type==='pierce'?'<i></i><i></i><i></i>':'<i></i><b></b>';if(text){const n=document.createElement('strong');n.textContent=text;fx.appendChild(n);}target.appendChild(fx);setTimeout(()=>fx.remove(),1200);}
 function attack(rec){const ids=rec.hitTargets?.length?rec.hitTargets:[rec.targetId];if(rec.dealt>0)ids.forEach(id=>effect(targetEl(id),['slash','blunt','pierce'].includes(rec.damageType)?rec.damageType:'anomaly'));if(rec.healing?.length)effect(document.getElementById('battleFocus'),'heal','+'+rec.healing.reduce((sum,h)=>sum+h.amount,0)+' HP');for(const h of rec.healing||[])playerEls(h.playerId).forEach(el=>effect(el,'heal','+'+h.amount+' HP'));}
 const statusLooks={
  vulnerable:['◎','#dc6b82','pulse'],bleeding:['滴','#c84b64','fall'],paralysis:['ϟ','#d6ac30','shake'],sealed:['封','#9372b6','seal'],terror:['!','#6a587e','pulse'],burning:['焰','#e27d34','rise'],tremor:['≋','#b89460','shake'],sinking:['↓','#568dbc','fall'],
  'damage-up':['↑','#d58051','rise'],shield:['◇','#63a9c4','seal'],regeneration:['+','#58ab86','rise'],agile:['»','#69bfb5','rise'],imprint:['✦','#d4ab55','seal'],
  focused:['◎','#779fb8','pulse'],adrenaline:['↑','#dd8761','rise'],guarded:['◇','#67a9bc','seal'],'steady-mind':['○','#7396a9','pulse'],'lucky-find':['✦','#cfac51','rise'],shaken:['!','#ad7ca7','shake'],slowed:['↓','#7796b2','fall'],weakened:['↓','#a4808e','fall'],marked:['◎','#b883a6','seal'],contaminated:['≋','#93a364','pulse'],
  'attack-down':['↓','#b07b82','fall'],'defense-down':['◇','#a187ac','shake'],suppressed:['×','#7476a0','seal']
 };
 function statuses(events){for(const event of events||[]){const def=statusById(event.statusId),[symbol,color,motion]=statusLooks[event.statusId]||['✦',def?.type==='buff'?'#63bdb0':'#c98f98','pulse'];const targets=event.side==='player'?playerEls(event.targetId):[targetEl(event.targetId)].filter(Boolean);for(const target of targets){const fx=document.createElement('div');fx.className='status-application status-'+motion;fx.style.setProperty('--status-color',color);fx.dataset.status=event.statusId;for(let i=0;i<3;i++){const particle=document.createElement('i');particle.textContent=symbol;particle.style.setProperty('--particle',i);fx.appendChild(particle);}const caption=document.createElement('strong');caption.textContent=(def?.name||event.statusId)+(event.amount?' +'+event.amount:event.stacks?' '+event.stacks+'層':'');fx.appendChild(caption);target.appendChild(fx);setTimeout(()=>fx.remove(),1500);}}}
 function death(id){const el=targetEl(id);if(!el||el.dataset.deathPlayed)return;el.dataset.deathPlayed='1';el.classList.add('enemy-dying');setTimeout(()=>el.classList.add('enemy-removed'),900);}
 function shield(room){const active=room.phase==='exploration'&&room.combat&&!room.combat.ended;for(const p of room.players||[])for(const el of playerEls(p.id)){el.classList.toggle('armor-shield',active&&Number(p.temporaryShield)>0);let badge=el.querySelector('.armor-shield-value');if(active&&p.temporaryShield>0){if(!badge){badge=document.createElement('span');badge.className='armor-shield-value';el.appendChild(badge);}badge.textContent='護盾 '+p.temporaryShield;}else badge?.remove();}document.querySelectorAll('[data-combat-target]').forEach(el=>{const e=room.combat?.enemies?.find(e=>e.instanceId===el.dataset.combatTarget);el.classList.toggle('armor-shield',active&&Number(e?.shield)>0);});}
 function apply(room){requestAnimationFrame(()=>shield(room));const fx=room.visualEffect;if(room.id!==lastRoom){lastRoom=room.id;lastEffect=fx?.id;return;}if(fx?.id&&fx.id!==lastEffect){lastEffect=fx.id;requestAnimationFrame(()=>{if(fx.type==='status')statuses(fx.events);else playerEls(fx.playerId).forEach(el=>effect(el,'heal','+'+fx.amount+' HP'));});}}
 socket.on('room:update',apply);window.KBMCombatVFX={apply,attack,statuses,death,shield,effect,playerEls};
})();
