(()=>{
 let lastEffect=null,lastRoom=null;
 const targetEl=id=>id?document.querySelector(`[data-combat-target="${CSS.escape(id)}"]`):null;
 const playerEls=id=>[...document.querySelectorAll(`[data-player-id="${CSS.escape(id)}"]`),...(id===state.selfId?[document.querySelector('#mySinner .sinner-profile')]:[])].filter(Boolean);
 function effect(target,type,text=''){if(!target)return;const fx=document.createElement('div');fx.className=`battle-effect effect-${type}`;fx.innerHTML=type==='heal'?'<i>+</i><i>+</i><i>+</i>':type==='slash'?'<i></i><i></i>':type==='pierce'?'<i></i><i></i><i></i>':'<i></i><b></b>';if(text){const n=document.createElement('strong');n.textContent=text;fx.appendChild(n);}target.appendChild(fx);setTimeout(()=>fx.remove(),1200);}
 function attack(rec){const ids=rec.hitTargets?.length?rec.hitTargets:[rec.targetId];if(rec.dealt>0)ids.forEach(id=>effect(targetEl(id),['slash','blunt','pierce'].includes(rec.damageType)?rec.damageType:'anomaly'));if(rec.healing?.length)effect(document.getElementById('battleFocus'),'heal','+'+rec.healing.reduce((sum,h)=>sum+h.amount,0)+' HP');for(const h of rec.healing||[])playerEls(h.playerId).forEach(el=>effect(el,'heal','+'+h.amount+' HP'));}
 function death(id){const el=targetEl(id);if(!el||el.dataset.deathPlayed)return;el.dataset.deathPlayed='1';el.classList.add('enemy-dying');setTimeout(()=>el.classList.add('enemy-removed'),900);}
 function shield(room){for(const p of room.players||[])for(const el of playerEls(p.id)){el.classList.toggle('armor-shield',Number(p.temporaryShield)>0);let badge=el.querySelector('.armor-shield-value');if(p.temporaryShield>0){if(!badge){badge=document.createElement('span');badge.className='armor-shield-value';el.appendChild(badge);}badge.textContent='護盾 '+p.temporaryShield;}else badge?.remove();}document.querySelectorAll('[data-combat-target]').forEach(el=>{const e=room.combat?.enemies?.find(e=>e.instanceId===el.dataset.combatTarget);el.classList.toggle('armor-shield',Number(e?.shield)>0);});}
 function apply(room){requestAnimationFrame(()=>shield(room));const fx=room.visualEffect;if(room.id!==lastRoom){lastRoom=room.id;lastEffect=fx?.id;return;}if(fx?.id&&fx.id!==lastEffect){lastEffect=fx.id;requestAnimationFrame(()=>playerEls(fx.playerId).forEach(el=>effect(el,'heal','+'+fx.amount+' HP')));}}
 socket.on('room:update',apply);window.KBMCombatVFX={apply,attack,death,shield,effect,playerEls};
})();
