(()=>{
 let lastEffect=null,lastRoom=null;
 const targetEl=id=>id?document.querySelector(`[data-combat-target="${CSS.escape(id)}"]`):null;
 const playerEls=id=>[...document.querySelectorAll(`[data-player-id="${CSS.escape(id)}"]`),...(id===state.selfId?[document.querySelector('#mySinner .sinner-profile')]:[])].filter(Boolean);
 function effect(target,type,text=''){if(!target)return;if(window.KBMBattle2D?.emit(target,type)){if(text){const label=document.createElement('div');label.className='combat-float';label.textContent=text;target.appendChild(label);setTimeout(()=>label.remove(),1200);}return;}const fx=document.createElement('div');fx.className=`battle-effect effect-${type}`;fx.innerHTML=type==='heal'?'<i>+</i><i>+</i><i>+</i>':type==='slash'?'<i></i><i></i>':type==='pierce'?'<i></i><i></i><i></i>':'<i></i><b></b>';if(text){const n=document.createElement('strong');n.textContent=text;fx.appendChild(n);}target.appendChild(fx);setTimeout(()=>fx.remove(),1200);}
 function attack(rec){if(rec.shieldGained>0)playerEls(rec.playerId).forEach(el=>effect(el,'shield'));const ids=rec.hitTargets?.length?rec.hitTargets:[rec.targetId];if(rec.dealt>0)ids.forEach(id=>effect(targetEl(id),['slash','blunt','pierce'].includes(rec.damageType)?rec.damageType:'anomaly'));if(rec.healing?.length)effect(document.getElementById('battleFocus'),'heal','+'+rec.healing.reduce((sum,h)=>sum+h.amount,0)+' HP');for(const h of rec.healing||[])playerEls(h.playerId).forEach(el=>effect(el,'heal','+'+h.amount+' HP'));}
 const statusLooks={
  vulnerable:['◎','#dc6b82','pulse'],bleeding:['','#ac263e','bleed'],paralysis:['ϟ','#d6ac30','shake'],sealed:['封','#9372b6','seal'],terror:['!','#6a587e','pulse'],burning:['焰','#e27d34','rise'],tremor:['≋','#b89460','shake'],sinking:['↓','#568dbc','fall'],
  'damage-up':['↑','#d58051','rise'],shield:['◇','#63a9c4','seal'],regeneration:['+','#58ab86','rise'],agile:['»','#69bfb5','rise'],imprint:['✦','#d4ab55','seal'],
  focused:['◎','#779fb8','pulse'],adrenaline:['↑','#dd8761','rise'],guarded:['◇','#67a9bc','seal'],'steady-mind':['○','#7396a9','pulse'],'lucky-find':['✦','#cfac51','rise'],shaken:['!','#ad7ca7','shake'],slowed:['↓','#7796b2','fall'],weakened:['↓','#a4808e','fall'],marked:['◎','#b883a6','seal'],contaminated:['≋','#93a364','pulse'],
  'attack-down':['↓','#b07b82','fall'],'defense-down':['◇','#a187ac','shake'],suppressed:['×','#7476a0','seal']
 };
 function cardMotion(event){if(event.side==='player'&&event.kind==='discard'&&event.targetId!==state.selfId)return;const target=event.side==='enemy'?targetEl(event.targetId):playerEls(event.targetId).find(el=>el.getBoundingClientRect().height>0),box=target?.getBoundingClientRect();const fx=document.createElement('div');fx.className='deck-card-motion card-move-'+event.kind;fx.dataset.cardEffect=event.kind;const x=Math.max(65,Math.min(innerWidth-65,box?box.left+box.width/2:innerWidth/2)),y=Math.max(110,Math.min(innerHeight-150,box?box.top+box.height/2:innerHeight/2));fx.style.left=x+'px';fx.style.top=y+'px';const card=event.card||{},face=document.createElement('div');face.className='card-motion-face';if(card.faces)face.innerHTML=KBMCardUI.half(card.faces[0],'top')+KBMCardUI.half(card.faces[1],'bottom');else {const label=document.createElement('b');label.className='motion-ability';label.textContent='◇ '+(card.name||'能力牌');face.appendChild(label);}fx.appendChild(face);const caption=document.createElement('strong');caption.textContent=event.kind==='destroy'?'破壞・本場移除':event.kind==='steal'?'偷取・加入手牌':'丟棄・送入回收堆';fx.appendChild(caption);if(event.kind==='destroy'){const shards=document.createElement('div');shards.className='card-shards';shards.innerHTML='<i></i>'.repeat(6);shards.style.setProperty('--shard-color',KBMCards.SINS[card.faces?.[0]?.sin]?.color||'#c78665');fx.appendChild(shards);}document.body.appendChild(fx);setTimeout(()=>fx.remove(),1300);}
 function statuses(events){if(window.KBMDice?.enabled()&&window.KBMDice?.isPlaying()){window.KBMDice.whenIdle().then(()=>statuses(events));return;}for(const event of events||[]){if(event.eventType==='card'){cardMotion(event);continue;}const def=statusById(event.statusId),[symbol,color,motion]=statusLooks[event.statusId]||['✦',def?.type==='buff'?'#63bdb0':'#c98f98','pulse'];const targets=event.side==='player'?playerEls(event.targetId):[targetEl(event.targetId)].filter(Boolean);for(const target of targets){const fx=document.createElement('div');fx.className='status-application status-'+motion+(event.statusId==='paralysis'?' status-lightning':'');fx.style.setProperty('--status-color',color);fx.dataset.status=event.statusId;const rendered=window.KBMBattle2D?.emit(target,event.statusId);for(let i=0;i<(rendered?0:3);i++){const particle=document.createElement('i');if(event.statusId==='bleeding')particle.className='blood-seep';else if(event.statusId==='paralysis')particle.innerHTML='<svg class=lightning-bolt viewBox="0 0 32 64"><path d="M20 0 2 35h13L8 64 31 25H18Z"/></svg>';else if(event.statusId==='burning')particle.innerHTML='<svg class=burning-flame viewBox="0 0 40 56"><path fill="#f06c25" d="M20 0C28 20 38 22 38 38a18 18 0 0 1-36 0C2 26 12 18 12 12c8 8 6 16 9 18C29 22 20 14 20 0Z"/><path fill="#ffd45b" d="M20 27c2 10 10 10 10 17a10 10 0 0 1-20 0c0-6 7-11 10-17Z"/></svg>';else particle.textContent=symbol;particle.style.setProperty('--particle',i);fx.appendChild(particle);}const caption=document.createElement('strong');caption.textContent=(def?.name||event.statusId)+(event.amount?' +'+event.amount:event.stacks?' '+event.stacks+'層':'');fx.appendChild(caption);target.appendChild(fx);setTimeout(()=>fx.remove(),1500);}}}
 function death(id){const el=targetEl(id);if(!el||el.dataset.deathPlayed)return;el.dataset.deathPlayed='1';el.classList.add('enemy-dying');setTimeout(()=>el.classList.add('enemy-removed'),900);}
 function shield(room){const active=room.phase==='exploration'&&room.combat&&!room.combat.ended;for(const p of room.players||[])for(const el of playerEls(p.id)){el.classList.toggle('armor-shield',active&&Number(p.temporaryShield)>0);let badge=el.querySelector('.armor-shield-value');if(active&&p.temporaryShield>0){if(!badge){badge=document.createElement('span');badge.className='armor-shield-value';el.appendChild(badge);}badge.textContent='護盾 '+p.temporaryShield;}else badge?.remove();}document.querySelectorAll('[data-combat-target]').forEach(el=>{const e=room.combat?.enemies?.find(e=>e.instanceId===el.dataset.combatTarget);el.classList.toggle('armor-shield',active&&Number(e?.shield)>0);});}
 function persistent(room){const active=room.combat&&!room.combat.ended&&room.phase==='exploration';for(const entity of [...(room.players||[]),...(room.combat?.enemies||[])]){const id=entity.instanceId||entity.id,els=entity.instanceId?[targetEl(id)].filter(Boolean):playerEls(id);for(const el of els){const sink=active&&(entity.statuses||[]).some(s=>s.id==='sinking');let fx=el.querySelector('.sinking-current');if(sink&&!fx){fx=document.createElement('div');fx.className='sinking-current';fx.setAttribute('aria-hidden','true');fx.innerHTML='<i>↓</i><i>↓</i><i>↓</i><i>↓</i>';el.appendChild(fx);}if(!sink)fx?.remove();}}}
 function apply(room){requestAnimationFrame(()=>{shield(room);persistent(room);});const fx=room.visualEffect;if(room.id!==lastRoom){lastRoom=room.id;lastEffect=fx?.id;return;}if(fx?.id&&fx.id!==lastEffect){lastEffect=fx.id;requestAnimationFrame(()=>{if(fx.type==='status'){statuses(fx.events);if(fx.heal)playerEls(fx.heal.playerId).forEach(el=>effect(el,'heal','+'+fx.heal.amount+' HP'));}else playerEls(fx.playerId).forEach(el=>effect(el,'heal','+'+fx.amount+' HP'));});}}
 socket.on('room:update',apply);window.KBMCombatVFX={apply,attack,statuses,cardMotion,death,shield,persistent,effect,playerEls};
})();
