const {getStatus,CONSUMABLES,EQUIPMENT}=require('../../shared/game-data');
const {ECONOMY,eventGoldRange}=require('../economy');
const {randomFrom,pickPositiveStatus}=require('../expedition/danger-system');
const {addStatus,randomStatus,dangerShield,applyDamageToPlayer}=require('../status/status-manager');
const {addEquipment}=require('../equipment/equipment-manager');

function maybePositiveStatus(){return null;}
function maybeNegativeStatus(){return null;}
function awardGoldToParty(room,amount){const value=Math.max(0,Math.round(amount||0));if(!value)return 0;for(const player of room.players)player.gold=Math.max(0,Number(player.gold||0)+value);return value;}
function awardGoldToPlayer(player,amount){const value=Math.max(0,Math.round(amount||0));if(!value)return 0;player.gold=Math.max(0,Number(player.gold||0)+value);return value;}
function eventGold(room,degree){const range=eventGoldRange(degree),chance=ECONOMY.eventGoldChance[degree]||0;if(!range||Math.random()>chance)return 0;const [min,max]=range,danger=Number(room.exploration.danger||0),chapter=room.areaIndex||0;return awardGoldToParty(room,min+Math.floor(Math.random()*(max-min+1))+chapter*ECONOMY.eventChapterBonus+Math.floor(danger/2));}
function personalEventGold(room,player,degree){const range=eventGoldRange(degree),chance=ECONOMY.eventGoldChance[degree]||0;if(!range||Math.random()>chance)return 0;const [min,max]=range,chapter=room.areaIndex||0;return awardGoldToPlayer(player,min+Math.floor(Math.random()*(max-min+1))+chapter*ECONOMY.eventChapterBonus);}
function chooseRarity(room){const danger=Number(room.exploration?.danger||0),chapter=Number(room.areaIndex||0),rare=Math.min(.38,.06+danger*.025+chapter*.055),uncommon=Math.min(.62,.28+danger*.03+chapter*.05),r=Math.random();return r<rare?'rare':r<rare+uncommon?'uncommon':'common';}
function pickLoot(room,type){const source=type==='equipment'?EQUIPMENT:CONSUMABLES,rarity=chooseRarity(room),exact=source.filter(x=>x.rarity===rarity);return JSON.parse(JSON.stringify(randomFrom(exact.length?exact:source)));}
function grantRewardToPlayer(room,event,check,recipient){if(!recipient||!['critical','success','mixed'].includes(check.degree))return null;const rule=event?.rewardByAction?.[check.actionId];if(!rule)return null;const degreeMult=check.degree==='critical'?1.25:check.degree==='mixed'?.45:1,chance=Math.min(.95,Number(rule.chance||0)*degreeMult);if(Math.random()>chance)return null;
 if(rule.type==='gold'){const [min,max]=eventGoldRange(check.degree)||[3,6],amount=awardGoldToPlayer(recipient,min+Math.floor(Math.random()*(max-min+1))+(room.areaIndex||0)*ECONOMY.eventChapterBonus);return {playerId:recipient.id,playerName:recipient.name,type:'gold',amount};}
 let item;if(rule.type==='card'){const C=require('../../shared/cards');item=require('../cards/card-manager').grantCard(recipient,require('../expedition/danger-system').pickReward(C.rewardPool(recipient.sinnerId),room.exploration.danger,recipient,room.areaIndex));if(!item)return null;}else {item=pickLoot(room,rule.type);if(rule.type==='equipment')addEquipment(recipient,item);else if(recipient.inventory.length<4)recipient.inventory.push(item);else room.sharedInventory.push(item);}return {playerId:recipient.id,playerName:recipient.name,type:rule.type,item};}
function grantEventReward(room,event,check){const contribution=check.contributions?.[0],recipient=room.players.find(p=>p.id===contribution?.playerId);return grantRewardToPlayer(room,event,{...check,actionId:contribution?.actionId},recipient);}
function outcomeForDegree(room,degree,balance){let damage=0,cluesDelta=0,dangerDelta=0;if(degree==='critical'){cluesDelta=2;dangerDelta=-1;}else if(degree==='success')cluesDelta=1;else if(degree==='mixed'){cluesDelta=1;dangerDelta=1;damage=3;}else if(degree==='failure'){dangerDelta=2;damage=7;}else{dangerDelta=3;damage=11;}damage=Math.max(0,Math.round(damage*balance.eventDamage));dangerDelta=dangerDelta>0?Math.max(1,Math.round(dangerDelta*balance.dangerGain)):dangerDelta;const active=room.players.filter(p=>p.connected&&p.hp>0),partyShield=Math.max(...active.map(dangerShield),0);if(dangerDelta>0)dangerDelta=Math.max(0,dangerDelta-partyShield);const actualDamage=[];if(damage)for(const player of active)actualDamage.push({playerId:player.id,amount:applyDamageToPlayer(player,damage)});room.exploration.clues=Math.max(0,room.exploration.clues+cluesDelta);room.exploration.danger=Math.max(0,Math.min(room.exploration.dangerMax,room.exploration.danger+dangerDelta));const debuff=['failure','critical-failure'].includes(degree)?maybeNegativeStatus(room,degree==='critical-failure'?3:1):null,buffTarget=['critical','success'].includes(degree)?randomFrom(active):null,buff=buffTarget?maybePositiveStatus(room,buffTarget,degree==='critical'?.1:0):null,gold=0;return {damage,actualDamage,cluesDelta,dangerDelta,gold,statusApplied:debuff||(buff?{playerId:buffTarget.id,statusId:buff.id,name:buff.name}:null)};}
function personalOutcome(room,player,check){let damage=0,cluesDelta=0;if(check.degree==='critical')cluesDelta=1;else if(check.degree==='success')cluesDelta=1;else if(check.degree==='mixed')damage=3;else if(check.degree==='failure')damage=7;else damage=11;damage=Math.max(0,Math.round(damage*check.balance.eventDamage));const actualDamage=damage?applyDamageToPlayer(player,damage):0;room.exploration.clues=Math.max(0,room.exploration.clues+cluesDelta);const statusApplied=['failure','critical-failure'].includes(check.degree)?maybeNegativeStatus(room,check.degree==='critical-failure'?3:1,player):null;const buff=['critical','success'].includes(check.degree)?maybePositiveStatus(room,player,check.degree==='critical'?.08:0):null;const loot=grantRewardToPlayer(room,room.currentEvent,check,player);const gold=loot?.type==='gold'?loot.amount:0;return {playerId:player.id,degree:check.degree,die:check.die,total:check.total,dc:check.dc,damage:actualDamage,cluesDelta,gold,loot,statusApplied:statusApplied||(buff?{playerId:player.id,statusId:buff.id,name:buff.name}:null)};}
module.exports={maybePositiveStatus,maybeNegativeStatus,awardGoldToParty,awardGoldToPlayer,eventGold,personalEventGold,outcomeForDegree,personalOutcome,grantEventReward,grantRewardToPlayer};
