const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'kbm-abilities30-'));process.env.DATA_DIR=dir;
const C=require('../shared/cards'),Cards=require('../server/cards/card-manager'),B=require('../server/status/battle-status'),Skills=require('../server/skills/skill-effects'),G=require('../shared/game-data');
const action=()=>Cards.instance({kind:'action',name:'test',source:'初始',faces:[{sin:'wrath',type:'slash',value:2},{sin:'lust',type:'guard',value:2}]});
function fixture(id){const p={id:'p',name:'test',sinnerId:id,connected:true,hp:40,maxHp:100,equipment:{},statuses:[],learnedSkills:[],inventory:[],relics:[],gold:0};const e={instanceId:'e',name:'enemy',currentHp:100,maxHp:100,statuses:[]};const r={id:'TEST',phase:'exploration',players:[p],combat:{round:1,flowVersion:29,phase:'attack',phaseSerial:'test',enemies:[e],intents:{},cooldowns:{},selections:{},log:[]}};Cards.initialize(r);r.combat.enemyCardDecks={e:{hand:[action(),action(),action()],draw:[action()],discard:[action()],destroyed:[]}};return {r,p,e,d:r.combat.cardDecks.p};}
try{
 const ids=new Set();for(const sinner of G.SINNERS){const extras=C.extraPersonalAbilities(sinner.id);assert.equal(extras.length,5);assert.equal(C.personalAbilities(sinner.id).length,6);assert(extras.some(a=>['draw','shuffle'].includes(a.effect)));const f=fixture(sinner.id);assert.equal(Cards.deckFor(f.p).length,20);assert.equal(Cards.deckFor(f.p).filter(c=>c.kind==='ability').length,8);
  for(const def of extras){assert(!ids.has(def.id));ids.add(def.id);const {r,p,e,d}=fixture(sinner.id),ability=Cards.instance({...def,kind:'ability'}),cost=action();d.hand=[ability,cost];d.draw=[action(),action()];d.discard=[action()];if(def.cleanse)p.statuses=[{id:'bleeding',remaining:2,stacks:1}];const events=B.captureEffects(()=>Cards.useAbility(r,p,{uid:ability.uid,costId:cost.uid,enemyId:e.instanceId}));assert.equal(d.abilityUses,1,def.name);assert(d.discard.some(c=>c.uid===ability.uid));assert(events.some(ev=>ev.eventType==='card'&&ev.kind==='discard'&&ev.card.uid===ability.uid));assert.equal(d.hand.some(c=>c.uid===cost.uid),!C.abilityNeedsCost(def));if(def.effect==='draw'||def.effect==='shuffle')assert(d.hand.some(c=>c.uid!==cost.uid));if(def.heal)assert.equal(p.hp,40+def.heal);if(def.shield)assert.equal(p.temporaryShield,def.shield);if(def.teamShield)assert.equal(p.temporaryShield,def.teamShield);if(def.selfStatus)assert(B.stack(p,def.selfStatus)>0);if(def.applyStatus)assert(B.stack(e,def.applyStatus)>0);if(def.nextDraw)assert.equal(d.nextDrawBonus,1);if(def.regeneration)assert.equal(B.stack(p,'regeneration'),1);if(def.imprint)assert.equal(B.stack(p,'imprint'),1);if(def.cleanse)assert.equal(p.statuses.length,0);if(def.agile)assert.equal(B.stack(p,'agile'),1);if(def.goldBonus)assert.equal(p.battleGoldBonus,4);if(def.discardEnemy)assert(events.some(ev=>ev.side==='enemy'&&ev.kind==='discard'));if(def.destroyEnemy){assert.equal(r.combat.enemyCardDecks.e.destroyed.length,1);assert(events.some(ev=>ev.kind==='destroy'));}if(def.stealPile)assert(d.hand.some(c=>c.source==='戰鬥偷取'));
   if(def.battleLimit){d.hand.push(d.discard.splice(d.discard.findIndex(c=>c.uid===ability.uid),1)[0]);d.abilityUses=0;if(!d.hand.some(c=>c.uid===cost.uid))d.hand.push(d.discard.splice(d.discard.findIndex(c=>c.uid===cost.uid),1)[0]);const before=JSON.stringify(r);assert.throws(()=>Cards.useAbility(r,p,{uid:ability.uid,costId:cost.uid,enemyId:e.instanceId}),/本場使用上限/);assert.equal(JSON.stringify(r),before);}
  }
 }
 assert.equal(ids.size,60);
 // Invalid owner / missing cost / invalid target never consume cards or apply effects.
 {const {r,p,d}=fixture('04'),foreign=Cards.instance({...C.extraPersonalAbilities('02')[0],kind:'ability'});d.hand=[foreign];const before=JSON.stringify(r);assert.throws(()=>Cards.useAbility(r,p,{uid:foreign.uid}));assert.equal(JSON.stringify(r),before);}
 {const {r,p,d}=fixture('13'),card=Cards.instance({...C.extraPersonalAbilities('13')[4],kind:'ability'}),cost=action();d.hand=[card,cost];const before=JSON.stringify(r);assert.throws(()=>Cards.useAbility(r,p,{uid:card.uid,enemyId:'e'}));assert.throws(()=>Cards.useAbility(r,p,{uid:card.uid,costId:cost.uid,enemyId:'bad'}));assert.equal(JSON.stringify(r),before);}
 // Old ongoing decks gain the new cards once, without replacing hand ownership or sold cards.
 {const {r,p,d}=fixture('04');for(const pile of ['hand','draw','discard'])d[pile]=d[pile].filter(c=>!c.id.startsWith('ability-exclusive-'));delete d.personalVersion;const old=d.hand.map(c=>c.uid);p.removedDeckCards=[C.extraPersonalAbilities('04')[0].id];Cards.upgradePersonalDecks(r);assert.deepEqual(d.hand.map(c=>c.uid),old);assert.equal([...d.hand,...d.draw,...d.discard].filter(c=>c.id.startsWith('ability-exclusive-')).length,4);const after=JSON.stringify(d);Cards.upgradePersonalDecks(r);assert.equal(JSON.stringify(d),after);}
 // Skill-driven enemy discards/destruction have authoritative animation records too.
 {const {r,p,e}=fixture('04');const discard=B.captureEffects(()=>Skills.alterEnemyCards(r,p,e,'hand'));assert.equal(discard[0].kind,'discard');const destroy=B.captureEffects(()=>Skills.alterEnemyCards(r,p,e,'draw',true));assert.equal(destroy[0].kind,'destroy');assert.equal(r.combat.enemyCardDecks.e.destroyed.length,1);}
 {const {r,p,d}=fixture('03');p.healUses=2;const card=Cards.instance({...C.extraPersonalAbilities('03')[4],kind:'ability'});d.hand=[card,action()];Cards.useAbility(r,p,{uid:card.uid});assert.equal(p.serverControl,2);assert(r.combat.selections.p.confirmed);}
 console.log('v0.30 abilities passed: 60 real effects, 12 cycling cards, cost/owner/target validation, once-per-battle limits, legacy deck migration, card animation records and Don healing takeover.');
}finally{fs.rmSync(dir,{recursive:true,force:true});}
