const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'kbm-flow-'));process.env.DATA_DIR=dir;
const R=require('../server/room/room-manager'),Battle=require('../server/combat/combat-manager'),Flow=require('../server/combat/combat-flow'),Cards=require('../server/cards/card-manager'),D=require('../server/combat/opposed-dice'),I=require('../server/combat/initiative'),C=require('../shared/cards'),G=require('../shared/game-data');
const oldRoll=D.roll,oldOrder=I.order;
function fixture(two=false,first='player'){const {room:r,player:p}=R.createRoom('s1','A');r.selectedAreas=['zone-1','zone-2','zone-3'];R.setSinner(r,p,'04');if(two){const q=R.joinRoom(r.id,'s2','B').player;R.setSinner(r,q,'08');}R.resetForStart(r);Battle.startCombat(r,'combat');const e=r.combat.enemies[0];e.currentHp=e.maxHp=9999;e.parts=[];e.attack=5;r.combat.enemies=[e];r.players.forEach(p=>{p.hp=p.maxHp=100;p.learnedSkills=[];});I.order=()=>first==='player'?[...r.players.map(p=>({side:'player',id:p.id,name:p.name,total:7,mobility:7,rolls:[1]})),{side:'enemy',id:e.instanceId,name:e.name,total:4,mobility:4,rolls:[1]}]:[{side:'enemy',id:e.instanceId,name:e.name,total:8,mobility:8,rolls:[1]},...r.players.map(p=>({side:'player',id:p.id,name:p.name,total:3,mobility:3,rolls:[1]}))];Flow.movement(r);return r;}
function ackAll(r,kind){const serial=kind==='initiative'?r.combat.initiativeSerial:r.combat.lastResolution.serial;for(const p of r.players.filter(p=>p.connected&&p.hp>0))Flow.ready(r,p,kind,serial);}
function confirmAll(r){for(const p of r.players.filter(p=>p.connected&&p.hp>0))Battle.confirmCombatAction(r,p);}
const card=()=>Cards.instance({name:'test',kind:'action',faces:[{sin:'wrath',type:'slash',value:3},{sin:'lust',type:'guard',value:2}]});
try{
 D.roll=n=>Array(n).fill(1);
 // No selection before dice playback acknowledgments; multiplayer synchronizes both phases.
 const r=fixture(true),[p,q]=r.players,c=r.combat,e=c.enemies[0];assert.equal(c.phase,'initiative');assert.throws(()=>Battle.selectCombatCards(r,p,{picks:[]}));assert.throws(()=>Cards.useAbility(r,p,{uid:'x'}));Flow.ready(r,p,'initiative','stale');assert.equal(c.phase,'initiative');Flow.ready(r,p,'initiative',c.initiativeSerial);assert.equal(c.phase,'initiative');Flow.ready(r,q,'initiative',c.initiativeSerial);assert.equal(c.phase,'attack');assert(Object.values(c.intents).every(i=>i.attackDice===0&&i.defenseDice>0));
 const a=card(),b=card();c.cardDecks[p.id].hand=[a,b];const sel=Battle.selectCombatCards(r,p,{picks:[{uid:a.uid,flipped:false},{uid:b.uid,flipped:true}]});assert.equal(sel.points.slash,3);assert.equal(sel.points.guard,0);assert.deepEqual(sel.counts,{wrath:3});assert(Cards.actions(r,p,sel).every(a=>a.kind!=='card-guard'));Battle.selectCombatCards(r,q,{picks:[]});const hp=p.hp;confirmAll(r);assert.equal(c.phase,'resolving');assert(c.lastResolution.enemyResults.every(x=>!x.clashes?.length&&!x.damage));assert.equal(p.hp,hp);assert.equal(c.diceDefense.players[p.id].rolls.length,0);assert.equal(c.round,1);assert.throws(()=>Battle.selectCombatCards(r,p,{picks:[]}));assert.throws(()=>Battle.cancelCombatConfirm(r,p));assert(c.cardDecks[p.id].discard.some(x=>x.uid===a.uid));Flow.ready(r,p,'resolution',c.lastResolution.serial);assert.equal(c.phase,'resolving');q.connected=false;Flow.advance(r);assert.equal(c.phase,'defense');q.connected=true;
 const x=card(),y=card();c.cardDecks[p.id].hand=[x,y];const defense=Battle.selectCombatCards(r,p,{picks:[{uid:x.uid,flipped:false},{uid:y.uid,flipped:true}]});assert.equal(defense.points.slash,0);assert.equal(defense.points.guard,2);assert.deepEqual(defense.counts,{lust:2});assert(Cards.actions(r,p,defense).every(a=>a.kind!=='card-attack'));Battle.selectCombatCards(r,q,{picks:[]});const ehp=e.currentHp;confirmAll(r);assert.equal(e.currentHp,ehp);assert(c.lastResolution.enemyResults.length>0);assert.equal(c.diceDefense.players[p.id].rolls.length,2);assert.equal(c.round,1);ackAll(r,'resolution');assert.equal(c.phase,'initiative');assert.equal(c.round,2);
 // Enemy first requires defense selection first, then swaps to player attack.
 const enemyFirst=fixture(false,'enemy');ackAll(enemyFirst,'initiative');assert.equal(enemyFirst.combat.phase,'defense');confirmAll(enemyFirst);ackAll(enemyFirst,'resolution');assert.equal(enemyFirst.combat.phase,'attack');
 // A lethal first attack ends combat without any enemy turn or another card selection.
 const lethal=fixture();ackAll(lethal,'initiative');const lp=lethal.players[0],le=lethal.combat.enemies[0];le.currentHp=1;le.shield=0;lethal.combat.intents[le.instanceId].defenseDice=0;const lc=card();lethal.combat.cardDecks[lp.id].hand=[lc];Battle.selectCombatCards(lethal,lp,{picks:[{uid:lc.uid,flipped:false}]});confirmAll(lethal);assert(lethal.combat.ended);assert(lethal.combat.lastResolution.enemyResults.every(x=>!x.clashes?.length&&!x.damage));assert(lethal.combat.lastResolution.initiativeAlreadyPlayed);
 // Guard-triggered team healing resolves before enemy damage; periodic effects tick after both exchanges.
 const healing=fixture(true,'enemy');ackAll(healing,'initiative');const healer=healing.players[0],ally=healing.players[1];healer.sinnerId='02';healer.learnedSkills=['faust-fluid'];healer.hp=ally.hp=50;healer.statuses=[{id:'regeneration',stacks:1,remaining:2,fresh:false}];const hd=healing.combat.cardDecks[healer.id];hd.hand=['lust','gloom'].map(sin=>Cards.instance({name:'healing',kind:'action',faces:[{sin,type:'slash',value:2},{sin,type:'guard',value:2}]}));Battle.selectCombatCards(healing,healer,{picks:hd.hand.map(c=>({uid:c.uid,flipped:true}))});const he=healing.combat.enemies[0];healing.combat.intents[he.instanceId]={type:'attack',target:'single',attackDice:0,defenseDice:0,cardPlan:{},label:'test'};confirmAll(healing);assert.equal(healer.hp,68);assert.equal(ally.hp,68);assert.equal(healer.statuses[0].remaining,2);assert(healing.combat.lastResolution.players.some(x=>x.kind==='heal'&&x.healing.length===2));ackAll(healing,'resolution');confirmAll(healing);assert.equal(healer.hp,71);assert.equal(healer.statuses[0].remaining,1);
 // A selected group attack really rolls against each enemy, preserving its original role.
 const group=fixture();const gp=group.players[0];gp.sinnerId='07';gp.learnedSkills=['heath-holiday'];group.combat.enemies.push({...structuredClone(group.combat.enemies[0]),instanceId:'second'});ackAll(group,'initiative');for(const intent of Object.values(group.combat.intents))intent.defenseDice=0;const gd=group.combat.cardDecks[gp.id];gd.hand=[['gluttony',1],['envy',2]].map(([sin,value])=>Cards.instance({name:'group',kind:'action',faces:[{sin,type:'slash',value},{sin,type:'guard',value}]}));Battle.selectCombatCards(group,gp,{picks:gd.hand.map(c=>({uid:c.uid,flipped:false}))});confirmAll(group);assert.equal(group.combat.lastResolution.players.find(x=>x.kind==='aoe').clashes.length,2);
 // Actual initiative comparator uses mobility when successes tie.
 I.order=oldOrder;D.roll=n=>Array(n).fill(0);const tie=fixture();I.order=oldOrder;tie.combat.enemies[0].mobility=99;const ordered=I.order(tie);assert.equal(ordered[0].side,'enemy');assert.equal(ordered[0].total,0);assert.equal(ordered[0].mobility,99);
 // Suggested signature effects are selective; every sinner keeps six skills.
 for(const id of ['02','06','07','08']){const skills=G.SINNER_SKILLS.filter(s=>s.sinnerId===id);assert.equal(skills.length,6);const predicate=id==='02'?s=>s.randomAllyBuff||s.randomEnemyDebuff:id==='06'?s=>s.goldBonus:id==='07'?s=>s.onHitStatus==='vulnerable':s=>s.teamShield;assert(skills.some(predicate));assert(skills.some(s=>!predicate(s)));assert(skills.some(s=>C.isOutputSkill(s)));}
 // A real server boot preserves the saved phase, selections and resolution serial.
 const waiting=fixture();assert(!waiting.combat.enemyCardDecks);R.persist();const cp=require('node:child_process');const saved=healing.combat;
 const boot=cp.spawnSync(process.execPath,['-e',`require('./server/server');const room=require('./server/room/room-manager').rooms.get(${JSON.stringify(healing.id)});console.log('RESTORED:'+JSON.stringify({rules:room.combat.rulesVersion,phase:room.combat.phase,serial:room.combat.lastResolution?.serial,phaseSerial:room.combat.phaseSerial,waitingDecks:Object.keys(require('./server/room/room-manager').rooms.get(${JSON.stringify(waiting.id)}).combat.enemyCardDecks||{}).length}));setTimeout(()=>process.exit(0),25);`],{cwd:path.join(__dirname,'..'),env:{...process.env,PORT:'0'},encoding:'utf8',timeout:10000});
 assert.equal(boot.status,0,boot.stderr);const restored=JSON.parse(boot.stdout.match(/RESTORED:(.*)\n/)[1]);assert.deepEqual(restored,{rules:29,phase:saved.phase,serial:saved.lastResolution.serial,phaseSerial:saved.phaseSerial,waitingDecks:0});
 console.log('Combat flow passed: initiative lock, multiplayer playback gates, exclusive card faces, defense-first swap, full-cycle movement, lethal first attack, mobility tiebreak and skill variety.');
}finally{D.roll=oldRoll;I.order=oldOrder;fs.rmSync(dir,{recursive:true,force:true});}
