const assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'kbm-v28-'));process.env.DATA_DIR=dir;
const G=require('../shared/game-data'),C=require('../shared/cards'),Cards=require('../server/cards/card-manager'),Battle=require('../server/combat/combat-manager'),B=require('../server/status/battle-status'),S=require('../server/status/status-manager'),Dice=require('../server/combat/opposed-dice'),I=require('../server/combat/initiative'),Effects=require('../server/skills/skill-effects'),E=require('../server/expedition/expedition-manager'),Rest=require('../server/expedition/rest-event');
const player=(id='04',pid='p')=>({id:pid,name:pid,sinnerId:id,connected:true,hp:100,maxHp:100,gold:0,temporaryShield:0,statuses:[],relics:[],equipment:{weapon:G.starterWeaponFor(id)},equipmentInventory:[],inventory:[],learnedSkills:[],explorationCards:[]});
const card=(sin='wrath',value=2,type='slash')=>Cards.instance({name:'test',kind:'action',faces:[{sin,value,type},{sin,value,type:'guard'}]});
function room(players=[player()]){const r={id:'TEST',phase:'exploration',run:1,players,areaId:'zone-1',areaIndex:0,selectedAreas:['zone-1','zone-2','zone-3'],sharedInventory:[],exploration:{danger:0,dangerMax:8,clues:0,position:0,scenes:0,route:[{selected:true,type:'combat'},{selected:true,type:'rest'}],choiceLayers:{}},combat:{round:1,kind:'combat',enemies:[{instanceId:'e',name:'test',role:'minion',attack:5,mobility:5,currentHp:1000,maxHp:1000,shield:0,statuses:[],parts:[],resistances:{slash:1,blunt:1,pierce:1}}],selections:{},cooldowns:{},intents:{e:{type:'attack',target:'single',attackDice:3,defenseDice:0,damagePerPoint:3,cardPlan:{},label:'test'}},log:[]}};Cards.initialize(r);return r;}
let cases=0;function check(fn){fn();cases++;}
const oldRoll=Dice.roll,oldOrder=I.order;
try{
 check(()=>{const hand=[card('wrath',2),card('sloth',1),card('sloth',2)],req={wrath:{exact:1},sloth:{min:2}},t=C.totals(hand,hand.map(c=>({uid:c.uid,flipped:false})));assert(!C.canUse(t,{kind:'special',cardRequirement:req}));hand[0].faces[0].value=1;assert(C.canUse(C.totals(hand,hand.map(c=>({uid:c.uid,flipped:false}))),{kind:'special',cardRequirement:req}));hand[2].faces[0].value=1;assert(!C.canUse(C.totals(hand,hand.map(c=>({uid:c.uid,flipped:false}))),{kind:'special',cardRequirement:req}));});
 check(()=>{for(const sinner of G.SINNERS){const p=player(sinner.id),deck=Cards.deckFor(p).filter(c=>c.kind==='action').map(Cards.instance),skills=G.skillsForSinner(sinner.id);assert.equal(skills.filter(s=>Object.values(C.requirement(s)).some(v=>typeof v==='object')).length,2);for(const skill of skills){const t=C.totals(deck,deck.map(c=>({uid:c.uid,flipped:!C.isOutputSkill(skill)})));assert(C.canUse(t,{...skill,cardRequirement:C.requirement(skill)}),skill.id);}}});
 check(()=>{Dice.roll=(n)=>Array(n).fill(1);const r=room(),p=r.players[0],e=r.combat.enemies[0];e.mobility=3;p.equipment={};const order=I.order(r);assert.equal(order[0].id,'p');assert.equal(order[0].total,7);B.add(p,'paralysis',2,2);B.add(e,'agile',2,6);assert.equal(I.order(r)[0].id,'e');});
 check(()=>{const r=room(),p=r.players[0],e=r.combat.enemies[0];I.order=()=>[{side:'player',id:'p',name:'p',mobility:7,total:7,rolls:[]},{side:'enemy',id:'e',name:'e',mobility:5,total:5,rolls:[]}];p.hp=1;e.currentHp=1;r.combat.cardDecks.p.hand=[card()];Battle.selectCombatCards(r,p,{picks:r.combat.cardDecks.p.hand.map(c=>({uid:c.uid,flipped:false}))});Battle.confirmCombatAction(r,p);assert.equal(p.hp,1);assert.equal(r.combat.lastResolution.enemyResults.length,0);assert(r.combat.ended);});
 check(()=>{const r=room(),p=r.players[0],e=r.combat.enemies[0];I.order=()=>[{side:'enemy',id:'e',name:'e',mobility:5,total:5,rolls:[]},{side:'player',id:'p',name:'p',mobility:7,total:2,rolls:[]}];p.hp=1;r.combat.cardDecks.p.hand=[card()];Battle.selectCombatCards(r,p,{picks:r.combat.cardDecks.p.hand.map(c=>({uid:c.uid,flipped:false}))});Battle.confirmCombatAction(r,p);assert.equal(p.hp,0);assert.equal(e.currentHp,1000);assert.equal(r.phase,'defeat');assert.equal(r.combat.lastResolution.players.length,0);});
 check(()=>{const r=room(),p=r.players[0],deck=r.combat.cardDecks.p;assert.equal(deck.hand.length,6);const keep=deck.hand[0].uid;r.combat.round++;Cards.nextRound(r);assert(deck.hand.some(c=>c.uid===keep));assert.equal(deck.hand.length,6);B.add(p,'tremor',3,6);deck.hand=[];r.combat.round++;Cards.nextRound(r);assert.equal(deck.hand.length,4);assert.equal(deck.limit,6);deck.nextDrawBonus=2;r.combat.round++;Cards.nextRound(r);assert.equal(deck.hand.length,6);});
 check(()=>{const r=room(),p=r.players[0];p.learnedSkills=['ryo-forest'];const d=r.combat.cardDecks.p;d.hand=[card('wrath'),card('lust')];const sel={picks:d.hand.map(c=>({uid:c.uid,flipped:false}))};assert(Cards.actions(r,p,sel).some(a=>a.cardSkill));B.add(p,'sealed',1);assert(!Cards.actions(r,p,sel).some(a=>a.cardSkill));});
 check(()=>{const p=player();B.add(p,'paralysis',2,3);assert(!B.skip(p));B.add(p,'paralysis',2);assert(B.skip(p));assert.equal(B.stack(p,'paralysis'),0);});
 check(()=>{const p=player();B.add(p,'sinking',2,9);assert.equal(B.probability(p),.2);B.add(p,'terror',2);assert.equal(B.outgoing(p),.5);B.add(p,'vulnerable',2,9);assert.equal(B.vulnerability(p),1.6);B.add(p,'damage-up',2,9);assert.equal(B.flatDamage(p),12);});
 check(()=>{const p=player();p.hp=50;B.add(p,'bleeding',2,2);B.add(p,'burning',2);B.add(p,'regeneration',2);B.tick(p);assert.equal(p.hp,47);assert.equal(B.stack(p,'burning'),1);assert.equal(p.statuses.find(s=>s.id==='burning').remaining,2);B.tick(p);B.tick(p);assert.equal(B.stack(p,'burning'),0);});
 check(()=>{const p=player();S.addStatus(p,'shield',1,2);assert.equal(p.temporaryShield,8);B.tick(p);B.tick(p);assert.equal(B.stack(p,'shield'),0);assert.equal(p.temporaryShield,8);p.hp=0;assert.equal(S.healPlayer(p,50),0);});
 check(()=>{const r=room(),p=r.players[0],e=r.combat.enemies[0],a={kind:'special',specialDamage:true,cardSkill:true,diceCount:1,power:1,damageType:'slash'};r.combat.diceDefense={enemies:{e:Dice.pool(0)}};const Damage=require('../server/combat/combat-damage').damageTarget;const normal=Damage(r,r.combat,p,a,e,null,1,1).dealt;B.add(p,'damage-up',2);const buffed=Damage(r,r.combat,p,a,e,null,1,1).dealt;assert(buffed>normal);B.add(p,'terror',2);assert(Damage(r,r.combat,p,a,e,null,1,1).dealt<buffed);});
 check(()=>{const r=room(),p=r.players[0],e=r.combat.enemies[0],d={hand:[card(),card(),card(),card()],draw:[card()],discard:[card()]};r.combat.enemyCardDecks={e:d};assert(Effects.alterEnemyCards(r,p,e,'hand'));assert.equal(d.hand.length,3);assert.equal(d.discard.length,2);const uid=d.draw[0].uid;assert(Effects.alterEnemyCards(r,p,e,'draw',false,true));assert(!d.draw.length);assert(r.combat.cardDecks.p.hand.some(c=>c.uid===uid));for(let i=0;i<3;i++)assert(Effects.alterEnemyCards(r,p,e,'hand',true));d.hand.push(card());assert(!Effects.alterEnemyCards(r,p,e,'hand',true));assert.equal(d.destroyed.length,3);});
 check(()=>{const r=room([player('03')]),p=r.players[0];for(let i=0;i<3;i++)Effects.applySkillUtility(r,p,{id:'don-stew',kind:'heal',heal:20,healOveruse:true});assert.equal(p.serverControl,2);assert.throws(()=>Cards.selection(r,p,{picks:[]}));Cards.prepareAutomatic(r);assert(r.combat.selections.p.confirmed);const a=Cards.actions(r,p,r.combat.selections.p);assert(!a.some(a=>a.healOveruse));});
 check(()=>{const p=player('11');for(let i=0;i<8;i++)B.imprint(p);assert.equal(B.stack(p,'imprint'),8);assert.equal(Object.values(p.markMods).reduce((a,b)=>a+b),3);assert.equal(Object.keys(p.markMods).length,1);assert(!B.add(player('04'),'imprint',99));});
 check(()=>{const r=room([player('06')]),p=r.players[0];for(let i=0;i<10;i++)Effects.applySkillUtility(r,p,{goldBonus:4});assert.equal(p.battleGoldBonus,24);const before=r.exploration.danger;require('../server/combat/combat-rewards').finishVictory(r);assert.equal(r.exploration.danger,before);assert(p.gold>=24);});
 check(()=>{const r=room([player('04','p'),player('05','q')]);r.players[1].hp=0;r.exploration.position=1;E.enterCurrentNode(r);assert.equal(r.players[1].hp,1);assert.equal(r.currentEvent.sceneType,'rest');assert.equal(r.currentEvent.scope,'personal');assert.equal(r.exploration.danger,0);});
 check(()=>{const r=room([player('04','p'),player('05','q')]);r.players[0].hp=10;r.players[1].hp=1;r.combat=null;Rest.open(r);assert(Rest.options(r,r.players[0]).some(o=>o.id==='heal:q'));Rest.choose(r,r.players[0],'heal:q');assert.equal(r.players[1].hp,35);assert(!r.eventResult);assert.throws(()=>Rest.choose(r,r.players[0],'supply'));Rest.choose(r,r.players[1],'breather');assert.equal(r.players[1].hp,69);assert(r.eventResult.rest);assert(r.exploration.route[0].resolved);assert.equal(r.exploration.danger,0);});
 check(()=>{const r=room();r.combat=null;r.players[0].hp=10;Rest.open(r);Rest.choose(r,r.players[0],'supply');assert(r.eventResult.personalResults[0].loot.item);assert.equal(r.players[0].hp,10);});
 check(()=>{const r=room([player('04','p'),player('05','q')]);r.exploration.danger=8;assert(!Battle.checkDefeat(r));r.players[0].hp=0;assert(!Battle.checkDefeat(r));r.players[1].hp=0;assert(Battle.checkDefeat(r));});
 check(()=>{for(const slot of ['weapon','armor','accessory'])for(const rarity of ['common','uncommon','rare'])assert.equal(G.EQUIPMENT.filter(e=>e.id.startsWith('eq-v28-')&&e.slot===slot&&e.rarity===rarity).length,2);for(const e of G.EQUIPMENT.filter(e=>e.slot==='armor')){assert(Object.keys(e.mods).length);assert(e.survival.maxHp>0);}for(const e of G.EQUIPMENT.filter(e=>e.slot==='weapon'))assert(['bleeding','sinking','tremor'].includes(e.onHitStatus));});
 check(()=>{for(const defs of [G.NORMAL_ENEMIES,G.ELITE_ENEMIES,G.BOSSES])assert(defs.every(e=>e.mobility>0));assert(!require('../server/expedition/danger-system').nodeWeights(room()).some(n=>n.value==='supply'));});
 check(()=>{const r=room([player('09')]),p=r.players[0],d=r.combat.cardDecks.p;p.learnedSkills=['rod-mirror'];d.hand=[card('wrath',2),card('lust',2)];const picks=d.hand.map(c=>({uid:c.uid,flipped:true}));r.combat.selections.p={actionId:'cards',picks,confirmed:true};Dice.prepare(r);assert(p.bestOfTwo);assert.equal(r.combat.diceDefense.players.p.rolls.length,4);});
 check(()=>{const r=room([player('05')]),p=r.players[0],d=r.combat.cardDecks.p;p.learnedSkills=['meur-chain'];d.hand=[card('sloth',2),card('gloom',2)];const picks=d.hand.map(c=>({uid:c.uid,flipped:true}));r.combat.selections.p={actionId:'cards',picks,confirmed:true};Dice.prepare(r);assert.equal(r.combat.diceDefense.players.p.rolls.length,7);});
 check(()=>{const r=room([player('01')]),p=r.players[0],d=r.combat.cardDecks.p;p.learnedSkills=['ys-bygone'];d.hand=[card('sloth',1),card('gloom',2)];const actions=Cards.actions(r,p,{picks:d.hand.map(c=>({uid:c.uid,flipped:false}))});assert(!actions.some(a=>a.kind==='card-attack'||a.specialDamage));assert(actions.some(a=>a.zeroAttack));});
 check(()=>{const r=room();r.exploration.route[0].type='supply';r.exploration.choiceLayers={1:[{type:'supply',label:'補給',id:'old-supply'}]};require('../server/room/room-manager').ensureRoomBuild(r);assert.equal(r.exploration.route[0].type,'rest');assert.equal(r.exploration.choiceLayers[1][0].label,'休整');assert.equal(r.exploration.choiceLayers[1][0].id,'old-supply');});
 console.log(`${cases} v0.28 battle/exploration regression scenarios passed.`);
}finally{Dice.roll=oldRoll;I.order=oldOrder;fs.rmSync(dir,{recursive:true,force:true});}
