const assert=require('node:assert/strict'),crypto=require('crypto'),D=require('../server/combat/opposed-dice'),Cards=require('../server/cards/card-manager'),J=require('../server/combat/combat-journal');
const original=crypto.randomInt;function fixed(values,fn){crypto.randomInt=()=>{assert(values.length,'unexpected roll');return values.shift()?0:9999;};try{return fn();}finally{crypto.randomInt=original;}}
for(const [values,chosen,total] of [[[0,0,1,1],1,2],[[1,1,0,0],0,2],[[1,0,0,1],0,1]]){const result=fixed(values.slice(),()=>D.bestPool(2,null,true));assert.equal(result.chosen,chosen);assert.equal(result.total,total);assert.equal(result.remaining,total);assert.equal(result.attempts.length,2);}
const p={id:'p',name:'羅佳',sinnerId:'09',connected:true,hp:100,maxHp:100,equipment:{},statuses:[],relics:[],learnedSkills:['rod-cast']},e={instanceId:'e',name:'敵方',currentHp:100,maxHp:100,statuses:[],resistances:{}};
const card=(sin,value)=>Cards.instance({kind:'action',name:sin,faces:[{sin,type:'slash',value},{sin,type:'guard',value}]});const a=card('gloom',2),b=card('pride',2),guard=card('wrath',2),deck={personalVersion:31,hand:[a,b,guard],draw:[],discard:[]};const r={phase:'exploration',players:[p],combat:{cardMode:true,flowVersion:29,phase:'attack',round:1,selections:{p:{actionId:'cards',picks:[{uid:a.uid,flipped:false},{uid:b.uid,flipped:false}],targetId:'e'}},enemies:[e],cardDecks:{p:deck},intents:{e:{cardPlan:{},defenseDice:0}},log:[]}};
D.prepare(r);assert(p.bestOfTwo);const attack=Cards.actions(r,p,r.combat.selections.p).find(a=>a.kind==='card-attack');assert.equal(attack.diceCount,6,'four card dice plus two skill dice');
const records=[];fixed([0,0,0,0,0,0,1,1,1,1,1,1],()=>require('../server/combat/combat-damage').resolvePlayerAction(r,p,r.combat.selections.p,new Set(),records));const hit=records.flatMap(x=>x.clashes||[])[0];assert.deepEqual(hit.attackAttempts.map(D.sum),[0,6]);assert.equal(hit.attackChosen,1);assert.equal(hit.attackTotal,6);J.actions(r,records);assert(r.combat.log.some(x=>x.text.includes('攻擊擲兩次')));
r.combat.phase='defense';r.combat.selections.p={picks:[{uid:guard.uid,flipped:true}]};fixed([0,0,1,1],()=>D.prepare(r));assert(p.bestOfTwo,'persists across attack/defense');const defense=r.combat.diceDefense.players.p;assert.deepEqual(defense.attempts.map(D.sum),[0,2]);assert.equal(defense.total,2);const clash=D.clash([1],defense);assert.equal(clash.defenseChosen,1);assert.equal(clash.defenseAttempts.length,2);assert.equal(clash.net,0);assert.equal(defense.remaining,1);J.actions(r,[{enemyId:'e',clashes:[{...clash,target:'羅佳'}]}],true);assert(r.combat.log.some(x=>x.text.includes('防禦擲兩次')));
r.combat.round++;D.prepare(r);assert.equal(p.bestOfTwo,false,'expires in next movement round');assert.equal(r.combat.diceDefense.players.p.attempts.length,1);
console.log('Best-of-two passed: actual six-dice attack, both attempt histories, higher/tie selection, defense carry and round expiry, complete journal.');
