const assert=require('node:assert/strict');
const os=require('os'),fs=require('fs'),path=require('path');
const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'kbm-card-test-'));process.env.DATA_DIR=dataDir;
const C=require('../shared/cards'),Cards=require('../server/cards/card-manager');
const {SINNERS,SINNER_SKILLS,EQUIPMENT}=require('../shared/game-data');
const {starterWeaponFor}=require('../shared/starter-equipment');
const Battle=require('../server/combat/combat-manager');
const {resolvePlayerAction}=require('../server/combat/combat-damage');
const {openShop,buyShopItem}=require('../server/shop/shop-manager');
function player(id='04',pid='p'){return {id:pid,name:pid,sinnerId:id,connected:true,hp:100,maxHp:100,gold:999,temporaryShield:0,equipment:{weapon:starterWeaponFor(id)},equipmentInventory:[],inventory:[],relics:[],statuses:[],learnedSkills:[],explorationCards:[]};}
function room(players=[player()]){return {id:'TEST',players,phase:'exploration',selectedAreas:['zone-1','zone-2','zone-3'],areaIndex:0,areaId:'zone-1',run:1,relicChoices:{},sharedInventory:[],exploration:{route:[{type:'combat',selected:true}],position:0,danger:0,dangerMax:10,clues:0,choiceLayers:{}},combat:{round:1,kind:'combat',enemies:[{instanceId:'e',name:'Target',currentHp:9999,maxHp:9999,defense:999,attack:0,shield:0,parts:[],statuses:[],resistances:{slash:1,blunt:1,pierce:1}}],selections:{},cooldowns:{},intents:{e:{type:'attack',target:'all',damage:0,label:'Test'}},log:[]}};}
const action=(sin='gluttony',type='slash',value=2)=>Cards.instance({kind:'action',name:'Test',faces:[{sin,type,value},{sin:'pride',type:'guard',value:1}]});
const ability=effect=>Cards.instance({...C.ABILITIES.find(a=>a.effect===effect),kind:'ability'});
function initialized(r=room()){Cards.initialize(r);return r;}
try{
 for(const sinner of SINNERS){const p=player(sinner.id),r=initialized(room([p])),d=r.combat.cardDecks.p;assert.equal(d.hand.length,5);assert.equal(d.draw.length,14);assert.equal(Cards.deckFor(p).length,19);assert.equal(Cards.deckFor(p).filter(c=>c.kind==='ability').length,3);const counts={};C.initialCards(sinner.id).forEach(c=>counts[c.faces[0].sin]=(counts[c.faces[0].sin]||0)+1);assert.equal(Object.values(counts).reduce((a,b)=>a+b,0),12);assert.equal(C.initialCards(sinner.id).reduce((n,c)=>n+c.faces[0].value,0),24);assert.equal(p.learnedSkills.length,1);}
 {const r=initialized(),p=r.players[0],d=r.combat.cardDecks.p,a=action();d.hand=[a];const s=Cards.selection(r,p,{picks:[{uid:a.uid,flipped:true}]});assert.equal(s.points.guard,1);assert.equal(s.points.slash,0);assert.equal(s.counts.pride,1);assert.throws(()=>Cards.selection(r,p,{picks:[{uid:a.uid,flipped:false},{uid:a.uid,flipped:false}]}));assert.throws(()=>Cards.selection(r,p,{picks:[{uid:'foreign',flipped:false}]}));assert.throws(()=>Cards.selection(r,p,{picks:[{uid:a.uid,flipped:'yes'}]}));assert.throws(()=>Cards.selection(r,p,{picks:[],skillId:p.learnedSkills[0]}));}
 {const r=initialized(),p=r.players[0],d=r.combat.cardDecks.p;d.hand=[action('wrath'),action('lust')];const s=Cards.selection(r,p,{picks:d.hand.map(c=>({uid:c.uid,flipped:false}))});assert.equal(s.skillId,'ryo-forest');assert(Cards.actions(r,p,s).some(a=>a.skillId==='ryo-forest'));s.confirmed=true;assert.throws(()=>Cards.selection(r,p,{picks:[]}));assert.throws(()=>Cards.useAbility(r,p,{uid:d.hand[0].uid}));}
 for(const effect of ['draw','shuffle','recover','stack','copy']){const r=initialized(),p=r.players[0],d=r.combat.cardDecks.p,a=ability(effect),cost=action(),target=action('lust');d.hand=[a,cost,target];d.draw=[action('wrath')];d.discard=[action('gloom')];const desired=effect==='recover'?d.discard[0]:effect==='stack'?d.draw[0]:target;Cards.useAbility(r,p,{uid:a.uid,costId:cost.uid,targetId:desired.uid});assert.equal(d.abilityUses,1);if(effect==='recover')assert(d.hand.some(c=>c.uid===desired.uid));if(effect==='stack')assert.equal(d.draw[0].uid,desired.uid);if(effect==='copy'){assert.equal(d.copies,1);assert.equal(d.hand.filter(c=>c.temporary).length,1);assert(!p.explorationCards.length);}}
 {const r=initialized(),p=r.players[0],d=r.combat.cardDecks.p;d.hand=[ability('recover'),action()];d.discard=[];const before=JSON.stringify(d);assert.throws(()=>Cards.useAbility(r,p,{uid:d.hand[0].uid,costId:d.hand[1].uid,targetId:'bad'}));assert.equal(JSON.stringify(d),before);d.abilityUses=2;assert.throws(()=>Cards.useAbility(r,p,{uid:d.hand[0].uid}));d.abilityUses=0;d.copies=2;d.hand=[ability('copy'),action(),action()];assert.throws(()=>Cards.useAbility(r,p,{uid:d.hand[0].uid,costId:d.hand[1].uid,targetId:d.hand[2].uid}));}
 {const d={hand:[],draw:[action()],discard:[action(),action(),action(),action()],shuffles:0};Cards.draw(d,5);assert.equal(d.hand.length,5);assert.equal(d.shuffles,1);assert.equal(new Set(d.hand.map(c=>c.uid)).size,5);}
 {const r=initialized(),d=r.combat.cardDecks.p,old=d.hand.map(c=>c.uid);r.combat.selections.p={confirmed:true,picks:[{uid:old[0],flipped:false}]};r.combat.round++;Cards.nextRound(r);assert.equal(d.hand.length,5);assert(old.slice(1).every(id=>d.hand.some(c=>c.uid===id)));assert(d.discard.some(c=>c.uid===old[0]));assert.equal(d.draw.length,13);r.combat.selections.p={confirmed:true,picks:d.hand.map(c=>({uid:c.uid,flipped:false}))};d.nextDrawBonus=9;r.combat.round++;Cards.nextRound(r);assert.equal(d.hand.length,7);}
 {const r=initialized(),p=r.players[0],d=r.combat.cardDecks.p;d.hand=[action('gluttony','slash',3)];const s=Cards.selection(r,p,{picks:[{uid:d.hand[0].uid,flipped:false}]});const records=[];resolvePlayerAction(r,p,s,new Set(),records);assert(records[0].dealt>=0);assert.equal(records[0].clashes[0].attackRolls.length,3);assert(records[0].die<=6);assert.equal(records[0].cardBased,true);assert.equal(s.preview.hit,100);assert.throws(()=>Battle.selectCombatAction(r,p,{actionId:'attack:slash'}));}
 {const r=initialized(room([player('04','p'),player('05','q')]));const p=r.players[0],q=r.players[1];Battle.selectCombatCards(r,p,{picks:[]});Battle.selectCombatCards(r,q,{picks:[]});assert.equal(Battle.confirmCombatAction(r,p),null);assert.equal(r.combat.round,1);Battle.confirmCombatAction(r,q);assert.equal(r.combat.round,2);assert.equal(r.combat.cardDecks.p.hand.length,5);assert.equal(r.combat.cardDecks.q.hand.length,5);}
 {const p=player(),r=room([p]);openShop(r);assert.equal(r.shop.stock.filter(o=>o.item.cardItem).length,3);p.inventory=[{},{},{},{}];const offer=r.shop.stock.find(o=>o.item.cardItem),before=p.gold;buyShopItem(r,p,offer.offerId);assert.equal(p.explorationCards.length,1);assert.equal(p.inventory.length,4);assert.equal(p.gold,before-offer.price);assert.throws(()=>buyShopItem(r,p,offer.offerId));p.explorationCards=Array(24).fill(C.COLLECTIBLE[0].id);const other=r.shop.stock.find(o=>o.item.cardItem&&!o.soldTo);assert.throws(()=>buyShopItem(r,p,other.offerId));}
 {const p=player();Cards.grantCard(p,C.COLLECTIBLE[0]);const a=Cards.deckFor(p);p.equipment.weapon=EQUIPMENT.find(e=>e.id==='eq-hydraulic-maul');const b=Cards.deckFor(p);assert.equal(b.length,20);assert(b.filter(c=>c.source==='武器').every(c=>c.faces[0].type==='blunt'));assert.notDeepEqual(a.filter(c=>c.source==='武器'),b.filter(c=>c.source==='武器'));const r=initialized(room([p]));r.combat.cardDecks.p.hand.push({...action(),temporary:true});Cards.initialize(r);assert(!r.combat.cardDecks.p.hand.some(c=>c.temporary));}
 {const r=initialized(),p=r.players[0],d=r.combat.cardDecks.p;p.learnedSkills=SINNER_SKILLS.filter(s=>s.sinnerId==='04').slice(0,3).map(s=>s.id);d.hand=[action('wrath'),action('lust'),action('gluttony'),action('pride','slash',1)];const s=Cards.selection(r,p,{picks:d.hand.map(c=>({uid:c.uid,flipped:false}))});assert.equal(s.skillIds.length,3);const ids=Cards.actions(r,p,s).filter(a=>a.cardSkill).map(a=>a.skillId);assert.equal(new Set(ids).size,3);assert.deepEqual(ids,s.skillIds);}
 {const R=require('../server/cards/card-rewards'),r=initialized(),p=r.players[0];r.combat.ended=true;r.eventResult={};R.createChoices(r);const ids=r.cardChoices.p;assert.equal(new Set(ids).size,3);assert(R.pending(r));assert.throws(()=>R.choose(r,p,'foreign'));R.choose(r,p,ids[0]);assert.equal(p.explorationCards.length,1);assert(!R.pending(r));assert.throws(()=>R.choose(r,p,ids[0]));R.createChoices(r);R.choose(r,p,null);assert.equal(p.explorationCards.length,1);}
 {const S=require('../server/equipment/equipment-survival'),G=require('../server/equipment/equipment-manager'),stats=require('../server/equipment/equipment-stats'),p=player(),r=room([p]);r.combat.ended=true;const baseStats=stats.equipmentStats(p);p.equipmentInventory=[EQUIPMENT.find(x=>x.slot==='armor')];G.equipFromInventory(r,p,0);assert.equal(p.maxHp,112);assert.equal(p.hp,100);assert.deepEqual(stats.equipmentStats(p),baseStats);S.sync(p);assert.equal(p.maxHp,112);p.hp=112;G.unequip(r,p,'armor');assert.equal(p.maxHp,100);assert.equal(p.hp,100);p.equipmentInventory=[EQUIPMENT.find(x=>x.id==='eq-reactive-plate')];G.equipFromInventory(r,p,0);Battle.startCombat(r,'combat');assert.equal(p.temporaryShield,8);}
 {const r=initialized(),d=r.combat.cardDecks.p;d.hand=[action(),action(),action(),action(),action(),action()];const before=d.draw.length;r.combat.round++;Cards.nextRound(r);assert.equal(d.hand.length,6);assert.equal(d.draw.length,before);d.nextDrawBonus=1;r.combat.round++;Cards.nextRound(r);assert.equal(d.hand.length,7);assert.equal(d.draw.length,before-1);}
 {const {sell}=require('../server/shop/shop-sales'),p=player(),r=room([p]);openShop(r);const c=C.COLLECTIBLE[0];p.explorationCards=[c.id,c.id];const gold=p.gold;sell(r,p,{type:'card',cardId:c.id});assert.equal(p.explorationCards.length,1);assert.equal(p.gold,gold+6);sell(r,p,{type:'card',cardId:c.id});const snapshot=JSON.stringify(p);assert.throws(()=>sell(r,p,{type:'card',cardId:c.id}));assert.equal(JSON.stringify(p),snapshot);const id=Cards.deckFor(p)[0].id;sell(r,p,{type:'card',cardId:id});assert(!Cards.deckFor(p).some(c=>c.id===id));assert.throws(()=>sell(r,p,{type:'card',cardId:id}));while(Cards.deckFor(p).length>5)sell(r,p,{type:'card',cardId:Cards.deckFor(p)[0].id});assert.throws(()=>sell(r,p,{type:'card',cardId:Cards.deckFor(p)[0].id}));}
 {const p=player(),r=room([p]);p.temporaryShield=77;p.equipment.armor=EQUIPMENT.find(x=>x.id==='eq-reactive-plate');Battle.startCombat(r,'combat');assert.equal(p.temporaryShield,8);p.temporaryShield=55;Battle.startCombat(r,'combat');assert.equal(p.temporaryShield,8);r.combat.enemies.forEach(e=>e.currentHp=0);Battle.selectCombatCards(r,p,{picks:[]});Battle.confirmCombatAction(r,p);assert.equal(p.temporaryShield,0);p.inventory=[{id:'test',kind:'guard',power:15}];assert.throws(()=>Battle.useConsumable(r,p,0));assert.equal(p.inventory.length,1);Battle.startCombat(r,'combat');Battle.useConsumable(r,p,0);assert.equal(p.temporaryShield,23);p.hp=0;Battle.checkDefeat(r);assert.equal(p.temporaryShield,0);assert(r.combat.ended);}
 {const vm=require('vm'),context={KBMCards:C,escapeHtml:s=>String(s),socket:{on:()=>{}},window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../client/js/ui/deck-ui.js'),'utf8'),context);const D=context.window.KBMDeckUI;for(const sinner of SINNERS){const p=player(sinner.id);p.explorationCards=[C.COLLECTIBLE[0].id,C.COLLECTIBLE[0].id];p.removedDeckCards=[C.initialCards(sinner.id)[0].id];const client=D.deckFor(p,{cards:C.COLLECTIBLE});assert.equal(JSON.stringify(client.map(c=>c.id)),JSON.stringify(Cards.deckFor(p).map(c=>c.id)));const groups=D.grouped(client);assert(groups.some(g=>g.card.source==='探索'&&g.count===2));assert.equal(groups.reduce((n,g)=>n+g.count,0),client.length);}}
 {const D=require('../server/combat/opposed-dice'),pool={rolls:[1,1],total:2,remaining:2};const first=D.clash([1,1,1],pool);assert.equal(first.net,1);assert.equal(first.defenseTotal,2);assert.equal(pool.remaining,0);assert.equal(D.clash([1],pool).net,1);assert.equal(D.clash([1],{rolls:[1],total:1,remaining:1}).net,0);assert.equal(D.guardCount(3,10),3);assert.equal(D.guardCount(0,99),0);for(const n of [0,1,16,99]){const rolls=D.roll(n);assert(rolls.every(x=>x===0||x===1));assert.equal(rolls.length,n);}}
 {const E=require('../server/cards/enemy-cards'),e={instanceId:'enemy-deck',name:'test',currentHp:100,maxHp:100,attack:5,defense:2},c={round:1};for(let i=0;i<15;i++){c.round=i+1;const plan=E.plan(e,c),d=c.enemyCardDecks[e.instanceId];assert(plan.picks.length<=4);assert.equal(d.hand.length+d.draw.length+d.discard.length,15);assert.equal(new Set([...d.hand,...d.draw,...d.discard].map(c=>c.uid)).size,15);assert(d.abilityUses<=2);assert(d.hand.length<=8);assert.equal(plan,E.plan(e,c));}}
 {const D=require('../server/combat/opposed-dice'),old=D.roll,r=initialized(),p=r.players[0],e=r.combat.enemies[0];p.hp=1;e.currentHp=1;e.defense=0;r.combat.cardDecks.p.hand=[action('gluttony','slash',3)];r.combat.intents.e={type:'attack',target:'single',label:'locked',attackDice:1,defenseDice:0,cardPlan:{}};try{D.roll=()=>[1];Battle.selectCombatCards(r,p,{picks:[{uid:r.combat.cardDecks.p.hand[0].uid,flipped:false}]});Battle.confirmCombatAction(r,p);assert.equal(e.currentHp,0);assert.equal(p.hp,0);assert.equal(r.phase,'defeat');assert(r.combat.lastResolution.enemyResults[0].clashes.length);}finally{D.roll=old;}}
 // Workbook requirements, card orientation and shared numeric costs.
 {assert.equal(Object.keys(require('../shared/skill-requirements')).length,72);assert.deepEqual(C.requirement({id:'ryo-match'}),{lust:2,gluttony:2,pride:1});assert.equal(SINNER_SKILLS.find(s=>s.id==='ish-bygone').name,'往昔');
  for(const sinner of SINNERS){const cards=C.initialCards(sinner.id),first=SINNER_SKILLS.find(s=>s.sinnerId===sinner.id),req=C.requirement(first),budget={};for(const c of cards){const f=c.faces[C.isOutputSkill(first)?0:1];budget[f.sin]=(budget[f.sin]||0)+f.value;}assert(C.meets(budget,req),`${sinner.name}: initial skill achievable`);}
  const attack=action('wrath','slash',2),defense=action('wrath','slash',3);defense.faces[1]={sin:'lust',type:'guard',value:3};const totals=C.totals([attack,defense],[{uid:attack.uid,flipped:false},{uid:defense.uid,flipped:true}]);assert.deepEqual(totals.attackColors,{wrath:2});assert.deepEqual(totals.guardColors,{lust:3});assert(C.canUse(totals,{kind:'heavy',cardRequirement:{wrath:2}}));assert(!C.canUse(totals,{kind:'heavy',cardRequirement:{lust:2}}));assert(C.canUse(totals,{kind:'heal',cardRequirement:{lust:3}}));assert(!C.canUse(totals,{kind:'heal',cardRequirement:{wrath:1}}));assert(!C.meets({},null));}
 // All encounter anatomies and actual part effects, including summon cancellation.
 {const P=require('../server/combat/combat-parts'),{ELITE_ENEMIES,BOSSES}=require('../shared/game-data');for(const def of [...ELITE_ENEMIES,...BOSSES]){const e={...def,instanceId:def.id,maxHp:100,currentHp:100,attackMultiplier:1,role:'boss'};e.parts=P.makeParts(e,'boss');assert(!e.parts.some(p=>['攻擊部位','外殼','核心'].includes(p.name)));assert.equal(new Set(e.parts.map(p=>p.name)).size,3);assert.equal(P.reduceAttack(e,.5),false);P.applyPartDamage({},e,e.parts[0],100);assert.equal(e.attackMultiplier,.8);assert(P.reduceAttack(e,.8));P.applyPartDamage({},e,e.parts[1],100);assert.equal(e.defenseDicePenalty,2);e.currentHp=100;P.applyPartDamage({},e,e.parts[2],100);assert.equal(require('../server/combat/combat-summon').canSummon({enemies:[e]},e),false);}}
 {const E=require('../server/combat/combat-enemies'),list=[{name:'重複',role:'minion'},{name:'重複',role:'minion'},{name:'重複',role:'minion'},{name:'其他',role:'minion'}];E.labelDuplicates(list);assert.deepEqual(list.map(e=>e.name),['重複 a','重複 b','重複 c','其他']);E.labelDuplicates(list);assert.equal(list[0].name,'重複 a');}
 // Defense cancellation happens before shield absorption, statuses and resistance damage.
 {const D=require('../server/combat/opposed-dice'),old=D.roll,r=initialized(),p=r.players[0],e=r.combat.enemies[0];try{D.roll=n=>Array(n).fill(1);r.combat.diceDefense={players:{p:{rolls:[1,1,1],total:3,remaining:3}},enemies:{e:{rolls:[1,1,1],total:3,remaining:3}}};e.shield=20;const rec=[];r.combat.cardDecks.p.hand=[action('wrath','slash',3)];resolvePlayerAction(r,p,{actionId:'cards',picks:[{uid:r.combat.cardDecks.p.hand[0].uid,flipped:false}]},new Set(),rec);assert.equal(rec[0].dealt,0);assert.equal(e.shield,20);assert.equal(rec[0].clashes[0].net,0);
   r.combat.lockedEnemyTurns=[{enemyId:'e',intent:{type:'attack',attackDice:2,damagePerPoint:3,statusId:'bleeding',target:'single'},targets:['p'],attackMultiplier:1}];p.temporaryShield=10;const result=require('../server/combat/combat-damage').resolveEnemyActions(r,new Set());assert.equal(result.total,0);assert.equal(p.temporaryShield,10);assert.equal(p.statuses.length,0);assert.equal(result.results[0].clashes[0].target,'良秀');assert.equal(result.results[0].clashes[0].sinnerColor,'#B94E52');
   const {damageTarget}=require('../server/combat/combat-damage'),a={kind:'card-attack',cardBase:10,diceCount:3,damageType:'slash',stat:'combat'};e.shield=0;r.combat.diceDefense.enemies.e=D.pool(0);e.resistances.slash=.5;const low=damageTarget(r,r.combat,p,a,e,null,1,1).dealt;e.resistances.slash=2;const high=damageTarget(r,r.combat,p,a,e,null,1,1).dealt;assert(high>low*2);
 }finally{D.roll=old;}}
 // Only elite/boss victory awards relics, including the final boss; danger carries unchanged.
 {const Reward=require('../server/combat/combat-rewards');for(const kind of ['combat','elite','boss']){const r=initialized();r.combat.kind=kind;r.areaIndex=2;const danger=r.exploration.danger=4;Reward.finishVictory(r);assert.equal(r.exploration.danger,danger);assert.equal(!!r.relicChoices.p?.length,kind!=='combat');assert(r.players[0].gold>999);}const r=initialized();r.exploration.danger=5;require('../server/room-manager').beginNextArea(r);assert.equal(r.exploration.danger,5);}
 // Reinforcements are scheduled and telegraphed; broken summon parts disable them.
 {const P=require('../server/combat/combat-parts'),I=require('../server/combat/combat-intents'),r=initialized(),e=r.combat.enemies[0];e.role='boss';e.name='逆流維修核心';e.baseName=e.name;e.parts=P.makeParts(e,'boss');r.combat.round=2;I.setEnemyIntents(r.combat);assert(r.combat.intents.e.summonAfterAttack);assert(r.combat.intents.e.description.includes('召喚'));e.parts[2].destroyed=true;I.setEnemyIntents(r.combat);assert.equal(r.combat.intents.e.summonAfterAttack,false);}
 console.log('Card tests passed: 12 decks, face colors, skill conditions, all 5 abilities, ownership/locks, cycling, multiplayer, shops, weapon replacement and temporary copies.');
}finally{fs.rmSync(dataDir,{recursive:true,force:true});}
