const assert=require('node:assert/strict');
const os=require('os'),fs=require('fs'),path=require('path');
const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'kbm-card-test-'));process.env.DATA_DIR=dataDir;
const C=require('../shared/cards'),Cards=require('../server/cards/card-manager');
const {SINNERS,SINNER_SKILLS,EQUIPMENT}=require('../shared/game-data');
const {starterWeaponFor}=require('../shared/starter-equipment');
const Battle=require('../server/combat/combat-manager');
const {resolvePlayerAction}=require('../server/combat/combat-damage');
const {openShop,buyShopItem}=require('../server/shop/shop-manager');
function player(id='04',pid='p'){return {id:pid,name:pid,sinnerId:id,connected:true,hp:100,maxHp:100,gold:999,temporaryShield:0,equipment:{weapon:starterWeaponFor(id)},equipmentInventory:[],inventory:[],relics:[],statuses:[],learnedSkills:[],explorationCards:[]};}
function room(players=[player()]){return {id:'TEST',players,phase:'exploration',selectedAreas:['zone-1','zone-2','zone-3'],areaIndex:0,areaId:'zone-1',run:1,relicChoices:{},sharedInventory:[],exploration:{route:[{type:'combat',selected:true}],position:0,danger:0,dangerMax:10,clues:0,choiceLayers:{}},combat:{round:1,kind:'combat',enemies:[{instanceId:'e',name:'Target',currentHp:9999,maxHp:9999,defense:999,attack:0,shield:0,parts:[],statuses:[],resistances:{slash:1,blunt:1,pierce:1}}],selections:{},cooldowns:{},intents:{e:{type:'attack',target:'all',damage:0,label:'Test'}},log:[]}};}
const action=(sin='gluttony',type='slash',value=2)=>Cards.instance({kind:'action',name:'Test',faces:[{sin,type,value},{sin:'pride',type:'guard',value:1}]});
const ability=effect=>Cards.instance({...C.ABILITIES.find(a=>a.effect===effect),kind:'ability'});
function initialized(r=room()){Cards.initialize(r);return r;}
try{
 for(const sinner of SINNERS){const p=player(sinner.id),r=initialized(room([p])),d=r.combat.cardDecks.p;assert.equal(d.hand.length,5);assert.equal(d.draw.length,14);assert.equal(Cards.deckFor(p).length,19);assert.equal(Cards.deckFor(p).filter(c=>c.kind==='ability').length,3);const counts={};C.initialCards(sinner.id).forEach(c=>counts[c.faces[0].sin]=(counts[c.faces[0].sin]||0)+1);assert.deepEqual(Object.values(counts),[6,4,2]);assert.equal(p.learnedSkills.length,1);}
 {const r=initialized(),p=r.players[0],d=r.combat.cardDecks.p,a=action();d.hand=[a];const s=Cards.selection(r,p,{picks:[{uid:a.uid,flipped:true}]});assert.equal(s.points.guard,1);assert.equal(s.points.slash,0);assert.equal(s.counts.pride,1);assert.throws(()=>Cards.selection(r,p,{picks:[{uid:a.uid,flipped:false},{uid:a.uid,flipped:false}]}));assert.throws(()=>Cards.selection(r,p,{picks:[{uid:'foreign',flipped:false}]}));assert.throws(()=>Cards.selection(r,p,{picks:[{uid:a.uid,flipped:'yes'}]}));assert.throws(()=>Cards.selection(r,p,{picks:[],skillId:p.learnedSkills[0]}));}
 {const r=initialized(),p=r.players[0],d=r.combat.cardDecks.p;d.hand=[action(),action()];const s=Cards.selection(r,p,{picks:d.hand.map(c=>({uid:c.uid,flipped:false}))});assert.equal(s.skillId,'ryo-forest');assert(Cards.actions(r,p,s).some(a=>a.skillId==='ryo-forest'));s.confirmed=true;assert.throws(()=>Cards.selection(r,p,{picks:[]}));assert.throws(()=>Cards.useAbility(r,p,{uid:d.hand[0].uid}));}
 for(const effect of ['draw','shuffle','recover','stack','copy']){const r=initialized(),p=r.players[0],d=r.combat.cardDecks.p,a=ability(effect),cost=action(),target=action('lust');d.hand=[a,cost,target];d.draw=[action('wrath')];d.discard=[action('gloom')];const desired=effect==='recover'?d.discard[0]:effect==='stack'?d.draw[0]:target;Cards.useAbility(r,p,{uid:a.uid,costId:cost.uid,targetId:desired.uid});assert.equal(d.abilityUses,1);if(effect==='recover')assert(d.hand.some(c=>c.uid===desired.uid));if(effect==='stack')assert.equal(d.draw[0].uid,desired.uid);if(effect==='copy'){assert.equal(d.copies,1);assert.equal(d.hand.filter(c=>c.temporary).length,1);assert(!p.explorationCards.length);}}
 {const r=initialized(),p=r.players[0],d=r.combat.cardDecks.p;d.hand=[ability('recover'),action()];d.discard=[];const before=JSON.stringify(d);assert.throws(()=>Cards.useAbility(r,p,{uid:d.hand[0].uid,costId:d.hand[1].uid,targetId:'bad'}));assert.equal(JSON.stringify(d),before);d.abilityUses=2;assert.throws(()=>Cards.useAbility(r,p,{uid:d.hand[0].uid}));d.abilityUses=0;d.copies=2;d.hand=[ability('copy'),action(),action()];assert.throws(()=>Cards.useAbility(r,p,{uid:d.hand[0].uid,costId:d.hand[1].uid,targetId:d.hand[2].uid}));}
 {const d={hand:[],draw:[action()],discard:[action(),action(),action(),action()],shuffles:0};Cards.draw(d,5);assert.equal(d.hand.length,5);assert.equal(d.shuffles,1);assert.equal(new Set(d.hand.map(c=>c.uid)).size,5);}
 {const r=initialized(),d=r.combat.cardDecks.p,old=d.hand.map(c=>c.uid);r.combat.selections.p={confirmed:true,picks:[{uid:old[0],flipped:false}]};r.combat.round++;Cards.nextRound(r);assert.equal(d.hand.length,8);assert(old.slice(1).every(id=>d.hand.some(c=>c.uid===id)));assert(d.discard.some(c=>c.uid===old[0]));assert.equal(d.draw.length,10);r.combat.selections.p={confirmed:true,picks:d.hand.map(c=>({uid:c.uid,flipped:false}))};d.nextDrawBonus=9;r.combat.round++;Cards.nextRound(r);assert.equal(d.hand.length,7);}
 {const r=initialized(),p=r.players[0],d=r.combat.cardDecks.p;d.hand=[action('gluttony','slash',3)];const s=Cards.selection(r,p,{picks:[{uid:d.hand[0].uid,flipped:false}]});const records=[];resolvePlayerAction(r,p,s,new Set(),records);assert(records[0].dealt>0);assert(records[0].die<=6);assert.equal(records[0].cardBased,true);assert.equal(s.preview.hit,100);assert.throws(()=>Battle.selectCombatAction(r,p,{actionId:'attack:slash'}));}
 {const r=initialized(room([player('04','p'),player('05','q')]));const p=r.players[0],q=r.players[1];Battle.selectCombatCards(r,p,{picks:[]});Battle.selectCombatCards(r,q,{picks:[]});assert.equal(Battle.confirmCombatAction(r,p),null);assert.equal(r.combat.round,1);Battle.confirmCombatAction(r,q);assert.equal(r.combat.round,2);assert.equal(r.combat.cardDecks.p.hand.length,8);assert.equal(r.combat.cardDecks.q.hand.length,8);}
 {const p=player(),r=room([p]);openShop(r);assert.equal(r.shop.stock.filter(o=>o.item.cardItem).length,3);p.inventory=[{},{},{},{}];const offer=r.shop.stock.find(o=>o.item.cardItem),before=p.gold;buyShopItem(r,p,offer.offerId);assert.equal(p.explorationCards.length,1);assert.equal(p.inventory.length,4);assert.equal(p.gold,before-offer.price);assert.throws(()=>buyShopItem(r,p,offer.offerId));p.explorationCards=Array(24).fill(C.COLLECTIBLE[0].id);const other=r.shop.stock.find(o=>o.item.cardItem&&!o.soldTo);assert.throws(()=>buyShopItem(r,p,other.offerId));}
 {const p=player();Cards.grantCard(p,C.COLLECTIBLE[0]);const a=Cards.deckFor(p);p.equipment.weapon=EQUIPMENT.find(e=>e.id==='eq-hydraulic-maul');const b=Cards.deckFor(p);assert.equal(b.length,20);assert(b.filter(c=>c.source==='武器').every(c=>c.faces[0].type==='blunt'));assert.notDeepEqual(a.filter(c=>c.source==='武器'),b.filter(c=>c.source==='武器'));const r=initialized(room([p]));r.combat.cardDecks.p.hand.push({...action(),temporary:true});Cards.initialize(r);assert(!r.combat.cardDecks.p.hand.some(c=>c.temporary));}
 {const r=initialized(),p=r.players[0],d=r.combat.cardDecks.p;p.learnedSkills=SINNER_SKILLS.filter(s=>s.sinnerId==='04').slice(0,3).map(s=>s.id);d.hand=[action(),action(),action('lust')];const s=Cards.selection(r,p,{picks:d.hand.map(c=>({uid:c.uid,flipped:false}))});assert.equal(s.skillIds.length,3);const ids=Cards.actions(r,p,s).filter(a=>a.cardSkill).map(a=>a.skillId);assert.equal(new Set(ids).size,3);assert.deepEqual(ids,s.skillIds);}
 {const R=require('../server/cards/card-rewards'),r=initialized(),p=r.players[0];r.combat.ended=true;r.eventResult={};R.createChoices(r);const ids=r.cardChoices.p;assert.equal(new Set(ids).size,3);assert(R.pending(r));assert.throws(()=>R.choose(r,p,'foreign'));R.choose(r,p,ids[0]);assert.equal(p.explorationCards.length,1);assert(!R.pending(r));assert.throws(()=>R.choose(r,p,ids[0]));R.createChoices(r);R.choose(r,p,null);assert.equal(p.explorationCards.length,1);}
 {const S=require('../server/equipment/equipment-survival'),G=require('../server/equipment/equipment-manager'),stats=require('../server/equipment/equipment-stats'),p=player(),r=room([p]);r.combat.ended=true;const baseStats=stats.equipmentStats(p);p.equipmentInventory=[EQUIPMENT.find(x=>x.slot==='armor')];G.equipFromInventory(r,p,0);assert.equal(p.maxHp,112);assert.equal(p.hp,100);assert.deepEqual(stats.equipmentStats(p),baseStats);S.sync(p);assert.equal(p.maxHp,112);p.hp=112;G.unequip(r,p,'armor');assert.equal(p.maxHp,100);assert.equal(p.hp,100);p.equipmentInventory=[EQUIPMENT.find(x=>x.id==='eq-reactive-plate')];G.equipFromInventory(r,p,0);Battle.startCombat(r,'combat');assert.equal(p.temporaryShield,8);}
 console.log('Card tests passed: 12 decks, face colors, skill conditions, all 5 abilities, ownership/locks, cycling, multiplayer, shops, weapon replacement and temporary copies.');
}finally{fs.rmSync(dataDir,{recursive:true,force:true});}
