const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os');
const dir=fs.mkdtempSync(os.tmpdir()+'/charge-test-');process.env.DATA_DIR=dir;
const R=require('../server/room/room-manager'),M=require('../server/combat/combat-manager'),I=require('../server/combat/combat-intents'),D=require('../server/combat/combat-damage'),Dice=require('../server/combat/opposed-dice'),E=require('../server/cards/enemy-cards'),J=require('../server/combat/combat-journal');
const roll=Dice.roll;try{
const {room:r,player:p}=R.createRoom('a','A');r.selectedAreas=['zone-1','zone-2','zone-3'];R.setSinner(r,p,'04');R.resetForStart(r);M.startCombat(r,'combat');const c=r.combat,e=c.enemies[0];e.role='boss';e.parts=[{id:'weapon',type:'weapon',maxHp:40,currentHp:40}];e.currentHp=e.maxHp=1000;e.attack=20;c.enemies=[e];c.round=3;c.phase='attack';c.phaseSerial++;I.setEnemyIntents(c);assert(c.blockChallenge);assert.equal(c.intents[e.instanceId].type,'guard');c.phase='defense';c.phaseSerial++;I.setEnemyIntents(c);const intent=c.intents[e.instanceId];assert.equal(intent.type,'charged');assert.deepEqual(intent.cardRequirement,{});Dice.roll=n=>Array(n).fill(1);c.diceDefense={players:{[p.id]:{rolls:[]}}};c.lockedEnemyTurns=[{enemyId:e.instanceId,intent,targets:[p.id],attackMultiplier:1}];p.hp=p.maxHp=100;p.temporaryShield=0;p.statuses=[];
let result=D.resolveEnemyActions(r,new Set());assert(result.total>0&&result.total<=32);assert(result.results[0].clashes[0].stabilityReduction>0);assert.equal(c.blockChallenge,null);
c.blockChallenge={enemyId:e.instanceId,partId:'weapon',currentDamage:20,requiredDamage:20};p.hp=100;result=D.resolveEnemyActions(r,new Set());assert.equal(result.total,0);assert(result.results[0].blocked);assert.equal(p.hp,100);
c.blockChallenge={enemyId:e.instanceId,partId:'weapon',currentDamage:0,requiredDamage:20};e.parts[0].destroyed=true;result=D.resolveEnemyActions(r,new Set());assert(result.results[0].blocked);
for(let chapter=0;chapter<3;chapter++){const values=role=>E.deckFor({...e,role},chapter).filter(x=>x.kind==='action').map(x=>x.faces[0].value);const sum=a=>a.reduce((a,b)=>a+b,0);assert(sum(values('normal'))<sum(values('elite')));assert(sum(values('elite'))<sum(values('boss')));assert(Math.max(...values('boss'))<=5);}
J.actions(r,[{enemyId:e.instanceId,label:'蓄力',damage:20,clashes:[{target:p.name,attackRolls:[1],attackTotal:1,defenseRolls:[],defenseTotal:0,net:1,chargedBase:24,stability:5,stabilityReduction:5,damage:19}]}],true);for(let i=0;i<150;i++)J.write(r,'歷程 '+i);assert(c.log.some(x=>x.text.includes('穩定 5 減傷 5')));assert(c.log.some(x=>x.text==='歷程 0'));assert(c.log.some(x=>x.text==='歷程 149'));
const Reward=require('../server/events/event-rewards'),oldRandom=Math.random;try{Math.random=()=>.99;p.equipmentInventory=[];p.pendingEquipment=[];for(let i=0;i<5;i++){const reward=Reward.grantRewardToPlayer(r,{rewardByAction:{gear:{type:'equipment',chance:.01}}},{degree:'critical',actionId:'gear'},p);assert.equal(reward.type,'equipment');assert(reward.item.name);}assert.equal(p.equipmentInventory.length,4);assert.equal(p.pendingEquipment.length,1);assert.equal(Reward.grantRewardToPlayer(r,{rewardByAction:{gear:{type:'equipment',chance:.01}}},{degree:'success',actionId:'gear'},p),null);}finally{Math.random=oldRandom;}
console.log('Charge regression passed: telegraph survives phase swap, real balanced damage and stability reduction, threshold/part interruption, role card progression and persistent battle journal.');
}finally{Dice.roll=roll;fs.rmSync(dir,{recursive:true,force:true});}
