const assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'kbm31-'));process.env.DATA_DIR=dir;
const C=require('../shared/cards'),Cards=require('../server/cards/card-manager'),R=require('../server/room/room-manager'),Battle=require('../server/combat/combat-manager'),Flow=require('../server/combat/combat-flow'),EnemyCards=require('../server/cards/enemy-cards'),Rewards=require('../server/events/event-rewards'),Checks=require('../server/events/event-checks'),G=require('../shared/game-data');
const card=()=>Cards.instance({kind:'action',name:'test',faces:[{sin:'wrath',type:'slash',value:2},{sin:'lust',type:'guard',value:2}]});
function fixture(){const {room:r,player:p}=R.createRoom('p','p');r.selectedAreas=['zone-1','zone-2','zone-3'];R.setSinner(r,p,'04');R.resetForStart(r);Battle.startCombat(r,'combat');r.combat.enemies=[r.combat.enemies[0]];r.combat.enemies[0].currentHp=r.combat.enemies[0].maxHp=9999;p.learnedSkills=[];p.hp=p.maxHp=9999;return {r,p,d:r.combat.cardDecks[p.id]};}
try{
 for(const s of G.SINNERS){const p={sinnerId:s.id,equipment:{weapon:G.starterWeaponFor(s.id)}};assert.equal(Cards.deckFor(p).length,19);assert.equal(Cards.deckFor(p).filter(c=>c.kind==='ability').length,3);const exclusive=C.extraPersonalAbilities(s.id)[4];assert(Cards.grantCard(p,exclusive));assert(Cards.grantCard(p,exclusive));assert.equal(p.explorationCards.length,2);assert.equal(Cards.deckFor(p).filter(c=>c.id===exclusive.id).length,2);assert(C.rewardPool(s.id).every(c=>!c.sinnerId||c.sinnerId===s.id));assert(!Cards.grantCard(p,C.extraPersonalAbilities(s.id==='01'?'02':'01')[2]));}
 for(const sin of Object.keys(C.SINS))for(const type of ['slash','blunt','pierce']){const levels=['common','uncommon','rare'].map(r=>C.COLLECTIBLE.find(c=>c.id===(r==='uncommon'?`card-${sin}-${type}`:`card-${r}-${sin}-${type}`)));assert.deepEqual(levels.map(c=>c.faces[0].value),[3,4,5]);assert.deepEqual(levels.map(c=>c.faces[1].value),[3,4,5]);}
 const starter=G.starterWeaponFor('04');assert(C.weaponCards(starter,'04').every(c=>c.faces[0].value<=3));for(const rarity of ['common','uncommon','rare']){const e=G.EQUIPMENT.find(e=>e.slot==='weapon'&&e.rarity===rarity);assert(C.weaponCards(e,'04').every(c=>c.faces[0].value>=({common:3,uncommon:4,rare:5}[rarity])));}
 const {room:l,player:lp}=R.createRoom('l','l');assert.throws(()=>R.setSinner(l,lp,'04'),/地區/);l.selectedAreas=['zone-1','zone-2','zone-3'];R.setSinner(l,lp,'04');assert.equal(lp.sinnerId,'04');
 // Both attacking orders discard after each exchange, refill only after the second.
 for(const first of ['player','enemy']){const {r,p,d}=fixture(),c=r.combat,e=c.enemies[0];c.initiative=[{side:'player',id:p.id},{side:'enemy',id:e.instanceId}];c.firstSide=first;c.exchange=1;Flow.open(r);d.hand=Array.from({length:6},card);d.draw=Array.from({length:12},card);d.discard=[];d.nextDrawBonus=1;const original=d.hand.map(c=>c.uid);const pick=()=>{const uid=d.hand[0].uid;Battle.selectCombatCards(r,p,{picks:[{uid,flipped:c.phase==='defense'}]});Battle.confirmCombatAction(r,p);};pick();assert.equal(d.hand.length,5);assert.equal(d.draw.length,12);assert.equal(d.nextDrawBonus,1);assert(d.hand.every(c=>original.includes(c.uid)));Flow.ready(r,p,'resolution',c.lastResolution.serial);pick();assert.equal(d.hand.length,7);assert.equal(d.draw.length,9);assert.equal(d.nextDrawBonus,0);Flow.ready(r,p,'resolution',c.lastResolution.serial);assert.equal(c.phase,'initiative');assert.equal(c.round,2);}
 // Enemy also keeps the same remaining hand for the second exchange.
 {const e={instanceId:'e',name:'test',currentHp:100,maxHp:100},c={flowVersion:29,phase:'attack',phaseSerial:'a',round:1,exchange:1,chapterIndex:0};EnemyCards.plan(e,c);const d=c.enemyCardDecks.e;d.hand=Array.from({length:6},card);d.draw=Array.from({length:9},card);d.plan={picks:d.hand.slice(0,3).map(c=>({uid:c.uid,flipped:true}))};const remaining=d.hand.slice(3).map(c=>c.uid);c.phase='defense';c.phaseSerial='b';c.exchange=2;EnemyCards.plan(e,c);assert.equal(d.draw.length,9);assert.deepEqual(d.hand.map(c=>c.uid),remaining);c.round=2;c.exchange=1;c.phaseSerial='c';EnemyCards.plan(e,c);assert.equal(d.hand.length,6);assert.equal(d.draw.length,3);}
 assert(EnemyCards.deckFor({name:'test'},2).filter(c=>c.kind==='action').every(c=>c.faces.every(f=>f.value>=3&&f.value<=4)));
 // Every event option advertises its category; successful economic rewards never mix.
 // Waiting prompt accounts for other players rather than comparing the same ID.
 {const vm=require('vm'),context={state:{selfId:'p'},window:{},escapeHtml:String,socket:{on(){}},requestAnimationFrame(){}};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../client/js/ui/progression-ui.js'),'utf8'),context);const r={phase:'lobby',hostId:'p',selectedAreas:['a','b','c'],players:[{id:'p',connected:true,sinnerId:'04',hp:100},{id:'q',connected:true,sinnerId:'',hp:100}]};assert(context.window.KBMProgressionUI.waiting(r));r.players[1].sinnerId='13';assert(!context.window.KBMProgressionUI.waiting(r));r.phase='exploration';r.combat={phase:'defense',selections:{p:{confirmed:true}}};assert(context.window.KBMProgressionUI.waiting(r));r.combat.selections.q={confirmed:true};assert(!context.window.KBMProgressionUI.waiting(r));}
 const old=Math.random;Math.random=()=>0;try{for(const event of G.EVENTS){for(const option of Checks.eventOptions(event)){assert(option.rewardHint.includes('可能獲得'));const {r,p}=fixture();r.currentEvent=event;p.hp=5000;const rule=event.rewardByAction[option.id],check={degree:'success',actionId:option.id,die:20,total:20,dc:5,balance:{eventDamage:1}};const before={gold:p.gold,inv:p.inventory.length,eq:p.equipmentInventory.length,cards:p.explorationCards.length};const out=Rewards.personalOutcome(r,p,check);assert.equal(out.loot.type,rule.type);assert.equal(p.gold>before.gold,rule.type==='gold');assert.equal(p.inventory.length>before.inv,rule.type==='consumable');assert.equal(p.equipmentInventory.length>before.eq,rule.type==='equipment');assert.equal(p.explorationCards.length>before.cards,rule.type==='card');}}}finally{Math.random=old;}
 console.log('v0.31 passed: three starter abilities, duplicate exclusive rewards, rarity growth, map gate, both combat orders with whole-cycle refills, enemy refill parity, chapter card scaling, all event option reward categories.');
}finally{fs.rmSync(dir,{recursive:true,force:true});}
