let v10DraftTarget=null,v10DraftPart=null;
function v10Esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function v10Me(room){return room.players.find(p=>p.id===state.selfId);}
function v10Skill(id){return state.gameData?.sinnerSkills?.find(s=>s.id===id);}
function v10PlayerStat(p,key){const s=sinnerById(p.sinnerId);if(!s)return 0;const eq=equipmentMods(p),sm=statusMods(p);return Number(s.stats?.[key]||0)+Number(eq[key]||0)+Number(sm[key]||0);}
function v10EnsureCombatPanels(){
  const combat=document.getElementById('combatPanel');if(!combat)return;
  if(!document.getElementById('v10EnemyRoster')){const d=document.createElement('div');d.id='v10EnemyRoster';d.className='v10-enemy-roster';document.getElementById('combatStage')?.after(d);}
  if(!document.getElementById('v10TeamActions')){const d=document.createElement('div');d.id='v10TeamActions';d.className='v10-team-actions';document.getElementById('combatOptions')?.after(d);}
  if(!document.getElementById('v10ConfirmBar')){const d=document.createElement('div');d.id='v10ConfirmBar';d.className='v10-confirm-bar';document.getElementById('v10TeamActions')?.after(d);}
}
function v10AliveEnemies(c){return (c?.enemies||[]).filter(e=>e.currentHp>0);}
function v10CurrentTarget(room){const c=room.combat,me=v10Me(room),sel=c?.selections?.[me?.id];return v10AliveEnemies(c).find(e=>e.instanceId===(sel?.targetId||v10DraftTarget))||v10AliveEnemies(c)[0];}
function v10Estimate(player,action,target,part){
  if(!action||['guard','analyze'].includes(action.id)||['heal','team-buff'].includes(action.kind))return action?.id==='guard'?'減傷約 52%':action?.id==='analyze'?'降低防禦／取得線索':'輔助技能';
  const stat=Math.max(1,v10PlayerStat(player,action.stat||'combat')),mult=Number(action.power||1.35);let min=Math.max(1,Math.round(stat*mult)+(action.id==='attack'?0:2)),max=min+6;
  if(action.partBonus&&part){min=Math.round(min*(1+action.partBonus));max=Math.round(max*(1+action.partBonus));}if(action.minionBonus&&target?.role==='minion'){min=Math.round(min*(1+action.minionBonus));max=Math.round(max*(1+action.minionBonus));}if(action.bossBonus&&['boss','elite'].includes(target?.role)){min=Math.round(min*(1+action.bossBonus));max=Math.round(max*(1+action.bossBonus));}
  const def=Math.max(5,Number(target?.defense||10)-Number(action.ignoreDefense||0)-Number(target?.defensePenalty||0)),mod=Math.round(stat/2);let hits=0;for(let d=1;d<=20;d++)if(d===20||d+mod>=def)hits++;return `${min}～${max} 傷害 · 命中約 ${Math.round(hits/20*100)}%`;
}
function v10RenderEnemies(room){
  const c=room.combat,root=document.getElementById('v10EnemyRoster');if(!root||!c)return;const me=v10Me(room),sel=c.selections?.[me?.id],targetId=sel?.targetId||v10DraftTarget||v10AliveEnemies(c)[0]?.instanceId;
  if(c.blockChallenge){const b=c.blockChallenge;const enemy=v10AliveEnemies(c).find(e=>e.instanceId===b.enemyId),part=enemy?.parts?.find(p=>p.id===b.partId);root.innerHTML=`<div class="v10-block-warning"><strong>阻擋要求</strong><span>本回合對「${v10Esc(part?.name||'指定部位')}」造成至少 <b>${b.requiredDamage}</b> 傷害，可阻止「${v10Esc(b.label)}」</span></div>`;}else root.innerHTML='';
  root.innerHTML+=`<div class="v10-enemy-grid">${v10AliveEnemies(c).map(e=>{const intent=c.intents?.[e.instanceId],pct=Math.max(0,e.currentHp/e.maxHp*100),selected=e.instanceId===targetId;return `<article class="v10-enemy ${selected?'selected':''} ${e.role}" data-v10-target="${e.instanceId}"><div class="v10-enemy-head"><div><strong>${v10Esc(e.name)}</strong><small>${e.role==='boss'?'BOSS':e.role==='elite'?'精英':'小怪'}</small></div><span>${e.currentHp}/${e.maxHp}</span></div><div class="v10-hp"><i style="width:${pct}%"></i></div><div class="v10-intent"><span>下一行動</span><b>${v10Esc(intent?.label||'觀察中')}</b><small>${v10Esc(intent?.description||'')}</small></div>${(e.parts||[]).length?`<div class="v10-parts">${e.parts.map(p=>`<button data-v10-part="${p.id}" data-enemy="${e.instanceId}" ${p.destroyed?'disabled':''}><span>${v10Esc(p.name)}</span><b>${p.destroyed?'已破壞':`${p.currentHp}/${p.maxHp}`}</b><small>${v10Esc(p.effect)}</small></button>`).join('')}</div>`:''}</article>`}).join('')}</div>`;
  root.querySelectorAll('[data-v10-target]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-v10-part]'))return;v10DraftTarget=el.dataset.v10Target;v10DraftPart=null;const actionId=c.selections?.[me.id]?.actionId;if(actionId)action('combat:select',{roomId:room.id,actionId,targetId:v10DraftTarget,partId:null});else v10RenderCombat(room);});
  root.querySelectorAll('[data-v10-part]').forEach(btn=>btn.onclick=e=>{e.stopPropagation();v10DraftTarget=btn.dataset.enemy;v10DraftPart=btn.dataset.v10Part;const actionId=c.selections?.[me.id]?.actionId;if(actionId)action('combat:select',{roomId:room.id,actionId,targetId:v10DraftTarget,partId:v10DraftPart});else v10RenderCombat(room);});
}
function v10Actions(room,me){const basic=[{id:'attack',label:'攻擊',stat:'combat',statLabel:'戰鬥',desc:'直接攻擊指定敵人。'},{id:'guard',label:'防禦',stat:'stability',statLabel:'穩定',desc:'降低本回合受到的傷害。'},{id:'analyze',label:'觀察弱點',stat:'observe',statLabel:'觀察',desc:'降低敵人防禦並取得線索。'}];return [...basic,...(me.learnedSkills||[]).map(v10Skill).filter(Boolean)];}
function v10RenderActions(room){
  const c=room.combat,root=document.getElementById('combatOptions'),me=v10Me(room);if(!root||!c||!me)return;const sel=c.selections?.[me.id],target=v10CurrentTarget(room),part=target?.parts?.find(p=>p.id===(sel?.partId||v10DraftPart)&&!p.destroyed)||null;
  root.innerHTML=v10Actions(room,me).map(a=>{const cd=Number(c.cooldowns?.[me.id]?.[a.id]||0),selected=sel?.actionId===a.id,locked=!!sel?.confirmed||cd>0;return `<button class="event-option v10-action ${selected?'selected':''}" data-v10-action="${a.id}" ${locked?'disabled':''}><div class="option-head"><span>${v10Esc(a.label||a.name)}</span><em>${v10Esc(a.statLabel||a.stat||'技能')}</em></div><p>${v10Esc(a.desc||a.description||'')}</p><div class="v10-damage-preview">${cd>0?`冷卻 ${cd} 回合`:v10Esc(v10Estimate(me,a,target,part))}</div></button>`}).join('');
  root.querySelectorAll('[data-v10-action]').forEach(btn=>btn.onclick=()=>{const actionId=btn.dataset.v10Action,targetNow=v10CurrentTarget(room)||v10AliveEnemies(c)[0];v10DraftTarget=targetNow?.instanceId||null;action('combat:select',{roomId:room.id,actionId,targetId:v10DraftTarget,partId:v10DraftPart});});
}
function v10RenderTeam(room){
  const c=room.combat,root=document.getElementById('v10TeamActions');if(!root||!c)return;root.innerHTML=`<div class="v10-team-title">隊伍行動</div>${room.players.filter(p=>p.connected&&p.hp>0).map(p=>{const s=c.selections?.[p.id];return `<div class="v10-team-row ${s?.confirmed?'confirmed':''}"><span>${v10Esc(sinnerById(p.sinnerId)?.name||p.name)}</span><b>${v10Esc(s?.label||'尚未選擇')}</b><em>${s?.confirmed?'已確認':s?'可更改':'思考中'}</em></div>`}).join('')}`;
}
function v10RenderConfirm(room){const c=room.combat,root=document.getElementById('v10ConfirmBar'),me=v10Me(room);if(!root||!c||!me)return;const s=c.selections?.[me.id];root.innerHTML=s?.confirmed?`<button id="v10CancelConfirm" class="secondary">取消確認</button><span>等待其他隊員確認…</span>`:`<button id="v10Confirm" ${s?'':'disabled'}>確認本回合行動</button><span>${s?`已選：${v10Esc(s.label)}${s.preview?.max?` · ${s.preview.min}～${s.preview.max} 傷害`:''}`:'先選擇行動與目標'}</span>`;root.querySelector('#v10Confirm')?.addEventListener('click',()=>action('combat:confirm',{roomId:room.id}));root.querySelector('#v10CancelConfirm')?.addEventListener('click',()=>action('combat:cancel-confirm',{roomId:room.id}));}
function v10RenderCombat(room){if(!room.combat)return;v10EnsureCombatPanels();document.getElementById('enemyName').textContent=room.combat.kind==='boss'?'Boss 戰':room.combat.kind==='elite'?'精英遭遇':'敵對遭遇';document.getElementById('enemyTrait').textContent=`敵方單位 ${v10AliveEnemies(room.combat).length} · ROUND ${room.combat.round}`;const main=v10AliveEnemies(room.combat)[0];if(main){document.getElementById('enemyHpText').textContent=`${main.currentHp} / ${main.maxHp}`;document.getElementById('enemyHpBar').style.width=`${Math.max(0,main.currentHp/main.maxHp*100)}%`;}document.getElementById('enemyIntent')?.classList.add('hidden');v10RenderEnemies(room);v10RenderActions(room);v10RenderTeam(room);v10RenderConfirm(room);}
function v10RenderSkills(room){
  const me=v10Me(room),root=document.getElementById('mySinner');if(!me||!root||!me.sinnerId)return;root.querySelector('.v10-skill-fold')?.remove();const skills=(state.gameData?.sinnerSkills||[]).filter(s=>s.sinnerId===me.sinnerId),learned=me.learnedSkills||[];const details=document.createElement('details');details.className='inventory-fold v10-skill-fold';details.innerHTML=`<summary>罪人技能 <span>${learned.length}/3</span></summary><div class="v10-skill-list">${skills.map(s=>{const has=learned.includes(s.id),can=!has&&learned.length<3&&Number(me.gold||0)>=Number(s.cost||0)&&!room.combat;return `<div class="v10-skill ${has?'learned':''}"><div><strong>${v10Esc(s.name)}</strong><small>${v10Esc(s.description)}</small><em>${v10Esc(s.stat)} · ${s.cost} 金幣</em></div><button data-learn-skill="${s.id}" ${can?'':'disabled'}>${has?'已學會':learned.length>=3?'已滿':`${s.cost} 金幣`}</button></div>`}).join('')}</div>`;root.appendChild(details);details.querySelectorAll('[data-learn-skill]').forEach(btn=>btn.onclick=()=>action('skill:learn',{roomId:room.id,skillId:btn.dataset.learnSkill}));
}
function v10Enhance(room){if(room.combat)v10RenderCombat(room);v10RenderSkills(room);}
socket.on('room:update',room=>requestAnimationFrame(()=>v10Enhance(room)));
requestAnimationFrame(()=>state?.room&&v10Enhance(state.room));
