(()=>{
 const C=KBMCards,esc=escapeHtml;
 const preferences={sort:'acquired',side:'attack'};
 function ordered(cards){const list=grouped(cards);if(preferences.sort==='sin'){const sins=Object.keys(C.SINS);list.sort((a,b)=>{const index=c=>c.kind==='ability'?sins.length:sins.indexOf(c.faces[preferences.side==='defense'?1:0].sin);return index(a.card)-index(b.card);});}return list;}
 function controls(){return `<div class="deck-controls"><label>排列 <select data-deck-sort><option value="acquired" ${preferences.sort==='acquired'?'selected':''}>獲得順序</option><option value="sin" ${preferences.sort==='sin'?'selected':''}>罪孽順序</option></select></label><label>上方卡面 <select data-deck-side><option value="attack" ${preferences.side==='attack'?'selected':''}>攻擊牌</option><option value="defense" ${preferences.side==='defense'?'selected':''}>防禦牌</option></select></label></div>`;}
 function expeditionMarkup(cards){return controls()+`<div class="deck-card-grid">${ordered(cards).map(g=>cardMarkup({...g.card,source:g.sources.join("／")},g.count,preferences.side==='defense')).join('')}</div>`;}
 function bind(root,refresh){root.querySelectorAll('[data-deck-sort],[data-deck-side]').forEach(el=>el.onchange=()=>{preferences[el.hasAttribute('data-deck-sort')?'sort':'side']=el.value;refresh();});}
 function deckFor(player,gameData=state.gameData){const removed=new Set(player.removedDeckCards||[]),a=C.starterPersonalAbilities(player.sinnerId);return [...C.initialCards(player.sinnerId),...C.weaponCards(player.equipment?.weapon,player.sinnerId),...C.ABILITIES.slice(0,1).map(c=>({...c,kind:'ability',source:'通用'})),...a.map(card=>({...card,kind:'ability',source:'罪人限定'})),...(player.explorationCards||[]).map(id=>(gameData.cards||C.COLLECTIBLE).find(c=>c.id===id)).filter(Boolean).map(c=>({...c,source:'探索'}))].filter(c=>c.source==='探索'||!removed.has(c.id));}
 function grouped(cards){const groups=new Map();for(const c of cards){const key=JSON.stringify([c.kind,c.name,c.faces,c.effect,c.shield,c.heal]);const g=groups.get(key);if(g){g.count++;g.ids.push(c.id);if(!g.sources.includes(c.source))g.sources.push(c.source);}else groups.set(key,{card:c,count:1,ids:[c.id],sources:[c.source]});}return [...groups.values()];}
 function cardMarkup(c,count=1,flipped=false){const source=c.source||'探索',cls=source==='初始'?'initial':source==='武器'?'weapon':source==='戰鬥複製'?'copy':'explore';return `<div class="deck-card"><span class="deck-card-count">×${count}</span><div class="card-surface">${c.kind==='ability'?`<div class="ability-face"><span>無色 · ${esc(source)}</span><b>◇</b><strong>${esc(c.name)}</strong><small>${esc(c.description)}</small></div>`:`${KBMCardUI.half(c.faces[flipped?1:0],'top')}<div class="card-center source-${cls}">${esc(source)}</div>${KBMCardUI.half(c.faces[flipped?0:1],'bottom')}`}</div><small>${KBMCardUI.colorText(c.name)}</small></div>`;}
 function apply(room){const root=document.getElementById('mySinner'),player=room.players.find(p=>p.id===state.selfId);if(!root||!player?.sinnerId)return;const old=root.querySelector('.card-collection'),open=old?.open;old?.remove();const cards=deckFor(player),details=document.createElement('details');details.className='inventory-fold card-collection';details.open=!!open;details.innerHTML=`<summary>遠征牌組 <span>${cards.length} 張</span></summary>${expeditionMarkup(cards)}<small>同款牌合併顯示數量。武器牌於下場戰鬥組入；暫存複製牌不計入。</small>`;root.appendChild(details);bind(details,()=>{apply(room);window.KBMMobileInfo?.refresh(room);});}
 socket.on('room:update',room=>requestAnimationFrame(()=>apply(room)));window.KBMDeckUI={apply,deckFor,grouped,cardMarkup,expeditionMarkup,bind,ordered,preferences};
})();
