(()=>{
 const esc=escapeHtml,C=KBMCards;let cached=null,pending=null,query='',kind='rewards',sinner='01';const opened=new Set();
 function data(){return state.gameData?.sinners?.length?state.gameData:cached;}
 function cards(d){if(kind==='initial')return C.initialCards(sinner);if(kind==='weapon')return (d.equipment||[]).filter(e=>e.slot==='weapon').flatMap(e=>C.weaponCards(e,sinner));return d.cards||C.COLLECTIBLE;}
 function renderCards(root,d){const list=cards(d).filter(c=>{const text=[c.name,c.description,c.sinnerId&&(d.sinners||[]).find(s=>s.id===c.sinnerId)?.name,...(c.faces||[]).map(f=>C.SINS[f.sin].name+' '+C.TYPES[f.type])].join(' ');return text.includes(query.trim());});root.innerHTML=`<p class="encyclopedia-count">共 ${list.length} 張</p><div class="encyclopedia-cards">${list.map(c=>`<article><strong>${KBMCardUI.colorText(c.name)}</strong><small>${esc(c.source||({common:'普通',uncommon:'少見',rare:'稀有'}[c.rarity]||'通用'))}${c.sinnerId?' · '+esc(d.sinners.find(s=>s.id===c.sinnerId)?.name||''):''}</small>${c.kind==='ability'?`<p>${KBMCardUI.colorText(c.description||'')}</p>`:`<div class="encyclopedia-card-faces">${c.faces.map((f,i)=>`<span class="sin-cost" style="--sin:${C.SINS[f.sin].color}">${i?'下':'上'}：${esc(C.SINS[f.sin].name)} ${esc(C.TYPES[f.type])} ${f.value}</span>`).join('')}</div>`}</article>`).join('')||'<p>沒有符合的卡牌。</p>'}</div>`;}
 function fold(title,body){return `<details class="manual-section" ${opened.has(title)?'open':''}><summary>${esc(title)}</summary><div>${body}</div></details>`;}
 function enemySkill(sk,d){const status=(d.statusEffects||[]).find(s=>s.id===sk.statusId);return `<article class="encyclopedia-enemy-skill"><strong>${esc(sk.label||'技能')}</strong><p>${esc(sk.description||'')}</p><div class="enemy-catalog-tags">${sk.mult?`<span>威力 ×${Number(sk.mult)}</span>`:''}${sk.shield?`<span>護盾 +${Number(sk.shield)}</span>`:''}${sk.defenseBoost?`<span>防禦 +${Number(sk.defenseBoost)}</span>`:''}${sk.attackBoost?`<span>攻擊強化 +${Math.round(sk.attackBoost*100)}%</span>`:''}${sk.statusId?`<span>${esc(status?.name||sk.statusId)}</span>`:''}</div></article>`;}
 function enemies(d,key,label){return fold(label,(d.enemyCatalog?.[key]||[]).map(e=>{const area=d.areas.find(a=>a.id===e.area);return fold(e.name,`<p>${esc(area?.name||e.area)}</p><div class="enemy-catalog-tags"><span>基礎 HP ${Number(e.hp)}</span><span>攻擊 ${Number(e.attack)}</span><span>防禦 ${Number(e.defense)}</span><span>機動 ${Number(e.mobility)}</span></div><p>${esc(e.trait||'')}</p><div class="enemy-catalog-tags">${Object.entries(e.resistances||{}).map(([type,value])=>`<span>${esc(C.TYPES[type]||type)} 傷害 ×${Number(value)}</span>`).join('')}</div>${(e.skills||[]).map(sk=>enemySkill(sk,d)).join('')}${(e.phases||[]).map(phase=>`<h4>${esc(phase.label)} · HP ≤ ${Math.round(phase.at*100)}%</h4>${phase.skills.map(sk=>enemySkill(sk,d)).join('')}`).join('')}`);}).join('')||'<p>暫無敵人資料。</p>');}
 function render(root){root.querySelectorAll('details').forEach(el=>{const name=el.querySelector('summary').textContent;if(el.open)opened.add(name);else opened.delete(name);});const d=data();if(!d){root.innerHTML='<p>正在載入圖鑑…</p>';if(!pending)pending=fetch('/api/game-data').then(r=>{if(!r.ok)throw Error();return r.json();}).then(value=>{cached=value;window.KBMTutorialManual?.render();}).catch(()=>{pending=null;root.innerHTML='<p>圖鑑載入失敗，請重新展開圖鑑。</p>';});return;}
 root.innerHTML=fold('敵人圖鑑',`<p>以下為基礎資料；實戰數值會依地區難度、危險度與隊伍人數調整。抗性倍率低於 1 代表減傷，高於 1 代表傷害加重。</p>${enemies(d,'normal','小怪')}${enemies(d,'elite','精英')}${enemies(d,'boss','Boss')}`)+fold('地方資訊',(d.areas||[]).map(a=>`<article class="encyclopedia-area"><strong>${esc(a.name)}</strong><span>${esc({LOW:'低風險',MEDIUM:'中風險',HIGH:'高風險',EXTREME:'極高風險'}[a.risk]||a.risk)}</span><p>${esc(a.desc)}</p></article>`).join(''))+fold('罪人技能',(d.sinners||[]).map(s=>fold(s.name,(d.sinnerSkills||[]).filter(sk=>sk.sinnerId===s.id).map(sk=>`<article class="encyclopedia-skill">${KBMCardUI.skillMeta(sk)}<strong>${esc(sk.name)}</strong><p>${KBMCardUI.colorText(sk.description)}</p><div class="skill-card-cost">${KBMCardUI.requirementLine(sk)}</div><small>學習費用：${sk.cost} 金幣</small></article>`).join(''))).join(''))+fold('卡牌資訊',`<div class="encyclopedia-filters"><label>卡牌類別<select data-catalog-kind><option value="rewards">探索可獲得卡牌</option><option value="initial">罪人初始行動牌</option><option value="weapon">武器行動牌</option></select></label><label>初始／武器適用罪人<select data-catalog-sinner>${d.sinners.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select></label><label>搜尋<input data-catalog-search type="search" placeholder="卡牌名稱、罪孽或罪人" value="${esc(query)}"></label></div><div data-catalog-results></div>`);
 root.querySelectorAll('details').forEach(el=>el.ontoggle=()=>{if(!el.isConnected)return;const key=el.querySelector('summary').textContent;el.open?opened.add(key):opened.delete(key);});const results=root.querySelector('[data-catalog-results]'),select=root.querySelector('[data-catalog-kind]'),who=root.querySelector('[data-catalog-sinner]');select.value=kind;who.value=sinner;select.onchange=()=>{kind=select.value;renderCards(results,d);};who.onchange=()=>{sinner=who.value;renderCards(results,d);};root.querySelector('[data-catalog-search]').oninput=e=>{query=e.target.value;renderCards(results,d);};renderCards(results,d);
 }
 window.KBMEncyclopedia={render};
})();
