(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
  const degreeLabel=d=>({critical:'大成功',success:'成功',mixed:'代價成功',failure:'失敗','critical-failure':'大失敗'}[d]||d||'結果');
  function personalResultHtml(room,r){const player=room.players.find(p=>p.id===r.playerId),s=sinnerById(player?.sinnerId),mine=r.playerId===state.selfId;return `<div class="personal-event-result ${mine?'mine':''}"><div><strong>${esc(s?.name||player?.name||'玩家')}</strong><span>${esc(degreeLabel(r.degree))}</span></div><small>d20 ${Number(r.die||0)} · ${Number(r.total||0)} / DC ${Number(r.dc||0)}</small>${Number(r.damage||0)>0?`<em>HP -${Number(r.damage)}</em>`:''}${Number(r.gold||0)>0?`<em>+${Number(r.gold)} 金幣</em>`:''}${r.loot?`<em>取得 ${esc(r.loot.item?.name||'戰利品')}</em>`:''}${r.statusApplied?`<em>${esc(r.statusApplied.name)}</em>`:''}</div>`;}
  function render(room){
    const panel=document.getElementById('eventPanel');if(!panel)return;
    if(room.phase!=='exploration'||room.combat||room.shop||(!room.currentEvent&&!room.nodeReward&&!room.eventResult)){panel.classList.add('hidden');return;}
    panel.classList.remove('hidden');const event=room.currentEvent,resolved=!!room.eventResult,scope=event?.scope||room.eventResult?.scope||'group';
    const area=areaById(room.areaId),scopeLabel=scope==='personal'?'個人事件':'團體事件';document.getElementById('eventArea').textContent=`${area?.name||''} · ${room.exploration?.difficultyLabel||''} · ${scopeLabel}`;
    document.getElementById('eventName').textContent=event?.name||room.nodeReward?.title||'節點結算';document.getElementById('eventDescription').textContent=event?.description||room.nodeReward?.text||room.eventResult?.text||'';
    const options=document.getElementById('eventOptions');if(options){options.innerHTML=event&&!resolved?(event.options||[]).map(o=>`<button class="event-option${room.votes?.[state.selfId]===o.id?' selected':''}" data-option="${esc(o.id)}"><div class="option-head"><span>${esc(o.label)}</span><em>${esc(o.statLabel)}檢定</em></div><p>${esc(o.desc)}</p>${o.rewardHint?`<div class="event-reward-hint">◆ ${esc(o.rewardHint)}</div>`:''}</button>`).join(''):'';options.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>action('event:vote',{roomId:room.id,optionId:b.dataset.option}));}
    const result=document.getElementById('eventResult');if(result){result.classList.toggle('hidden',!resolved);if(resolved){const r=room.eventResult||{};if(r.degree==='personal'){result.innerHTML=`<strong>個人事件結算</strong><div class="personal-event-results">${(r.personalResults||[]).map(x=>personalResultHtml(room,x)).join('')}</div>`;}else{const status=r.statusApplied?`<div class="status-alert">${esc(r.statusApplied.name)} 被施加。</div>`:'',loot=r.loot?`<div class="event-loot-result">獲得：${esc(r.loot.item?.name||'戰利品')}</div>`:'',supplies=Array.isArray(r.rewards)?`<div class="personal-event-results">${r.rewards.map(x=>`<div class="personal-event-result"><strong>${esc(x.playerName)}</strong><em>取得 ${esc(x.reward?.name||'補給')}</em>${x.statusName?`<em>${esc(x.statusName)}</em>`:''}</div>`).join('')}</div>`:'';result.innerHTML=`<strong>${r.degree==='supply'?'取得補給':r.degree==='rest'?'休整完成':r.degree==='shop'?'採購完成':'團體事件結算'}</strong><p>${esc(r.text||'節點完成。')}</p>${r.damage?`<small>隊伍受到傷害：${r.damage}</small>`:''}${Number(r.gold||0)>0?`<small>獲得金幣：${r.gold}</small>`:''}${loot}${supplies}${status}`;}}}
  }
  socket.on('room:update',room=>requestAnimationFrame(()=>render(room)));requestAnimationFrame(()=>state?.room&&render(state.room));window.KBMEventUI={render};
})();
