(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
  const degreeLabel=d=>({critical:'大成功',success:'成功',mixed:'代價成功',failure:'失敗','critical-failure':'大失敗'}[d]||d||'結果');
  function lootHtml(loot){if(!loot)return '';const label={card:'卡牌',equipment:'裝備',consumable:'消耗品',gold:'金幣'}[loot.type]||'補給';return `<div class="event-loot-result reward-${loot.type||'item'}"><span class="reward-kind">${label}</span><b>${esc(loot.type==='gold'?'+'+loot.amount+' 金幣':loot.item?.name||'補給')}</b>${loot.item?.description?`<small>${esc(loot.item.description)}</small>`:''}</div>`;}
  function personalResultHtml(room,r){const player=room.players.find(p=>p.id===r.playerId),s=sinnerById(player?.sinnerId),mine=r.playerId===state.selfId;return `<div class="personal-event-result ${mine?'mine':''}"><div><strong>${esc(s?.name||player?.name||'玩家')}</strong><span>${esc(r.degree==='rest'?'完成':degreeLabel(r.degree))}</span></div>${r.choice?`<small>${esc(r.choice)}${r.healed?` · ${esc(r.targetName)} HP +${r.healed}`:''}</small>`:`<small>d20 ${Number(r.die||0)} · ${Number(r.total||0)} / DC ${Number(r.dc||0)}</small>`}${Number(r.damage||0)>0?`<em>HP -${Number(r.damage)}</em>`:''}${Number(r.gold||0)>0&&!r.loot?`<em>+${Number(r.gold)} 金幣</em>`:''}${lootHtml(r.loot)}${r.statusApplied?`<em>${esc(r.statusApplied.name)}</em>`:''}</div>`;}
  function render(room){
    const panel=document.getElementById('eventPanel');if(!panel)return;
    if(room.phase!=='exploration'||room.combat||room.shop||(!room.currentEvent&&!room.nodeReward&&!room.eventResult)){panel.classList.add('hidden');return;}
    panel.classList.remove('hidden');const event=room.currentEvent,resolved=!!room.eventResult,scope=event?.scope||room.eventResult?.scope||'group';
    const area=areaById(room.areaId),scopeLabel=scope==='personal'?'個人事件':'危機事件';document.getElementById('eventArea').innerHTML=`${esc(area?.name||'')} · ${esc(room.exploration?.difficultyLabel||'')} · <span class="event-scope ${scope==='personal'?'personal':'group'}">${scopeLabel}</span>`;
    document.getElementById('eventName').textContent=event?.name||room.nodeReward?.title||'節點結算';document.getElementById('eventDescription').textContent=(event?.description?event.description+(room.restChoices?.[state.selfId]?' 已完成選擇，等待隊友。':''):'')||room.nodeReward?.text||room.eventResult?.text||'';
    const options=document.getElementById('eventOptions');if(options){options.innerHTML=event&&!resolved?(event.sceneType==='rest'?(event.optionsByPlayer?.[state.selfId]||[]):event.options||[]).map(o=>`<button class="event-option${room.votes?.[state.selfId]===o.id?' selected':''}" data-option="${esc(o.id)}" ${room.restChoices?.[state.selfId]?'disabled':''}><div class="option-head"><span>${esc(o.label)}</span>${event.sceneType==='rest'?'<em>個人選擇</em>':`<em>${esc(o.statLabel)}檢定</em>`}</div><p>${esc(o.desc)}</p>${o.rewardHint?`<div class="event-reward-hint">◆ ${esc(o.rewardHint.replace(/；只獲得(?:此類獎勵|卡牌)。?/g,'。'))}</div>`:''}</button>`).join(''):'';options.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>action('event:vote',{roomId:room.id,optionId:b.dataset.option}));}
    const result=document.getElementById('eventResult');if(result){result.classList.toggle('hidden',!resolved||!!window.KBMDice?.eventPending(room));if(resolved&&!window.KBMDice?.eventPending(room)){const r=room.eventResult||{};if(r.degree==='personal'){result.innerHTML=`<strong>個人事件結算</strong><div class="personal-event-results">${(r.personalResults||[]).map(x=>personalResultHtml(room,x)).join('')}</div>`;}else{const status=r.statusApplied?`<div class="status-alert">${esc(r.statusApplied.name)} 被施加。</div>`:'',loot=Object.values(r.lootByPlayer||{}).map(l=>`<div class="group-event-loot"><small>${esc(l.playerName)}</small>${lootHtml(l)}</div>`).join('')||lootHtml(r.loot),supplies=Array.isArray(r.rewards)?`<div class="personal-event-results">${r.rewards.map(x=>`<div class="personal-event-result"><strong>${esc(x.playerName)}</strong><em>取得 ${esc(x.reward?.name||'補給')}</em>${x.statusName?`<em>${esc(x.statusName)}</em>`:''}</div>`).join('')}</div>`:'';result.innerHTML=`<strong>${r.degree==='supply'?'取得補給':r.degree==='rest'?'休整完成':r.degree==='shop'?'採購完成':'危機事件結算'}</strong><p>${esc(r.text||'節點完成。')}</p>${r.damage?`<small>隊伍受到傷害：${r.damage}</small>`:''}${Number(r.gold||0)>0?`<small>獲得金幣：${r.gold}</small>`:''}${loot}${supplies}${status}`;}}}
  }
  socket.on('room:update',room=>requestAnimationFrame(()=>render(room)));requestAnimationFrame(()=>state?.room&&render(state.room));window.KBMEventUI={render,lootHtml};
})();
