(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const routeClass=type=>`route-type-${['event','combat','supply','elite','rest','shop','boss'].includes(type)?type:'unknown'}`;
  function playerStat(player,key){const sinner=sinnerById(player.sinnerId);if(!sinner)return 0;const eq=equipmentMods(player),sm=statusMods(player);return Number(sinner.stats?.[key]||0)+Number(eq[key]||0)+Number(sm[key]||0);}
  function successChance(mod,dc){let ok=0;for(let d=1;d<=20;d++)if(d===20||d+mod>=dc)ok++;return Math.round(ok/20*100);}
  function chanceRange(room,option){const event=room.currentEvent;if(!event)return null;const active=room.players.filter(p=>p.connected&&p.hp>0);if(!active.length)return null;const chapterDc=[-2,0,2][Math.max(0,Math.min(2,room.areaIndex||0))]||0,dc=Math.max(8,Math.round(11+Number(event.difficulty||0)+Number(room.exploration?.danger||0)*.7+chapterDc));let low=0,high=0;for(const p of active){if(p.id===state.selfId){const v=playerStat(p,option.stat)+Number(option.bonus||0);low+=v;high+=v;continue;}const voted=event.options.find(o=>o.id===room.votes?.[p.id]);if(voted){const v=playerStat(p,voted.stat)+Number(voted.bonus||0);low+=v;high+=v;continue;}const vals=event.options.map(o=>playerStat(p,o.stat)+Number(o.bonus||0));low+=Math.min(...vals);high+=Math.max(...vals);}const a=successChance(Math.round((low/active.length)/2),dc),b=successChance(Math.round((high/active.length)/2),dc);return {min:Math.min(a,b),max:Math.max(a,b),dc};}
  function addProbabilities(room){if(!room.currentEvent||room.eventResult)return;document.querySelectorAll('#eventOptions [data-option]').forEach(btn=>{const o=room.currentEvent.options.find(x=>x.id===btn.dataset.option);if(!o)return;const r=chanceRange(room,o);if(!r)return;btn.querySelector('.success-range')?.remove();const d=document.createElement('div');d.className='success-range';d.innerHTML=r.min===r.max?`估計成功率 <strong>${r.min}%</strong>`:`估計成功率 <strong>${r.min}%～${r.max}%</strong>`;btn.appendChild(d);});}
  function ensurePanels(){const meters=document.getElementById('explorationMeters');if(!meters)return;if(!document.getElementById('routeChoicePanel')){const p=document.createElement('section');p.id='routeChoicePanel';p.className='route-choice-panel hidden';meters.after(p);}if(!document.getElementById('shopPanel')){const p=document.createElement('section');p.id='shopPanel';p.className='shop-panel hidden';document.getElementById('routeChoicePanel')?.after(p);}}
  function targetIndex(room){const ex=room.exploration||{},pos=Number(ex.position||0),node=ex.route?.[pos];if(node?.selected&&!node?.resolved)return null;if(node?.selected&&node?.resolved)return pos+1<14?pos+1:null;return pos;}
  function voteCounts(room,choices){const out={};choices.forEach(c=>out[c.id]=0);Object.values(room.routeVotes||{}).forEach(id=>{if(id in out)out[id]++});return out;}
  function renderChoices(room){const panel=document.getElementById('routeChoicePanel');if(!panel)return;const index=targetIndex(room);if(index===null||room.phase!=='exploration'){panel.classList.add('hidden');panel.innerHTML='';return;}const choices=room.exploration?.choiceLayers?.[index]||[];if(!choices.length){panel.classList.add('hidden');return;}const my=room.routeVotes?.[state.selfId],counts=voteCounts(room,choices),online=room.players.filter(p=>p.connected).length;panel.classList.remove('hidden');panel.innerHTML=`<div class="route-choice-head"><div><span>NEXT ROUTE</span><strong>選擇第 ${index+1} / 14 層</strong></div><small>${Object.keys(room.routeVotes||{}).length}/${online} 已投票</small></div><div class="route-choice-grid">${choices.map(c=>`<button class="route-choice ${routeClass(c.type)} ${my===c.id?'selected':''}" data-route-choice="${esc(c.id)}"><span>${esc(c.label)}</span><small>${counts[c.id]||0} 票</small></button>`).join('')}</div><div class="route-color-legend"><span class="route-type-event">事件</span><span class="route-type-combat">小怪</span><span class="route-type-supply">補給</span><span class="route-type-elite">精英</span><span class="route-type-rest">休整</span><span class="route-type-shop">商店</span></div><p class="route-forecast-note">下一層已知；下下層仍受迷霧遮蔽。這一節點結算後的危險度，會影響下下層的候選內容與風險。</p>`;panel.querySelectorAll('[data-route-choice]').forEach(b=>b.onclick=()=>action('route:vote',{roomId:room.id,choiceId:b.dataset.routeChoice}));}
  function renderRoute(room){const ex=room.exploration||{},route=ex.route||[],target=targetIndex(room),panel=document.getElementById('routePanel');if(!panel)return;panel.innerHTML=`<div class="route-caption"><span>${esc(ex.difficultyLabel||'')}路線</span><b>${Math.min(14,Number(ex.position||0)+1)} / 14</b></div><div class="route-scroll"><div class="route-track">${route.map((n,i)=>{const done=n.selected&&n.resolved,current=n.selected&&i===ex.position&&!n.resolved,next=i===target;let label='迷霧';if(n.selected)label=n.label;else if(next)label='可選擇';else if(i===13)label='BOSS';const type=n.selected?n.type:(i===13?'boss':'unknown');return `<div class="route-node ${routeClass(type)} ${done?'done':''} ${current?'current':''} ${next?'next':''} ${!n.selected&&!next?'fogged':''}"><div class="route-node-box"><b>${i+1}</b><span>${esc(label)}</span></div></div>${i<route.length-1?'<i class="route-link"></i>':''}`}).join('')}</div></div>`;requestAnimationFrame(()=>panel.querySelector('.route-node.current,.route-node.next')?.scrollIntoView({block:'nearest',inline:'center'}));}
  function renderShop(room){const panel=document.getElementById('shopPanel');if(!panel)return;if(!room.shop){panel.classList.add('hidden');panel.innerHTML='';return;}const p=room.players.find(x=>x.id===state.selfId);if(!p)return;document.getElementById('eventPanel')?.classList.add('hidden');document.getElementById('combatPanel')?.classList.add('hidden');panel.classList.remove('hidden');const ready=!!room.shop.ready?.[p.id],done=!!room.eventResult;panel.innerHTML=`<div class="shop-head"><div><span>SHOP / 商店</span><strong>${esc(room.shop.title||'行商補給站')}</strong></div><div class="shop-gold">金幣 <b>${Number(p.gold||0)}</b></div></div><div class="shop-stock">${(room.shop.stock||[]).map(o=>{const sold=!!o.soldTo,can=Number(p.gold||0)>=Number(o.price||0)&&!sold&&!ready;return `<div class="shop-item ${sold?'sold':''}"><div><strong>${esc(o.item?.name||'商品')}</strong><small>${esc(o.item?.description||'')}</small><em>${esc(o.item?.rarity||'common')}</em></div><button data-shop-buy="${esc(o.offerId)}" ${can?'':'disabled'}>${sold?'已售出':`${o.price} 金幣`}</button></div>`}).join('')}</div><button id="shopReadyBtn" class="shop-ready" ${ready||done?'disabled':''}>${done?'已完成採購':ready?'等待其他玩家…':'完成購物'}</button>`;panel.querySelectorAll('[data-shop-buy]').forEach(b=>b.onclick=()=>action('shop:buy',{roomId:room.id,offerId:b.dataset.shopBuy}));panel.querySelector('#shopReadyBtn')?.addEventListener('click',()=>action('shop:ready',{roomId:room.id}));}
  function gold(room){const p=room.players.find(x=>x.id===state.selfId),root=document.getElementById('mySinner');if(!p||!root)return;root.querySelector('.sinner-gold')?.remove();const d=document.createElement('div');d.className='sinner-gold';d.innerHTML=`<span>金幣</span><strong>${Number(p.gold||0)}</strong>`;root.prepend(d);}
  function collapseInventory(){const root=document.getElementById('mySinner');if(!root)return;[...root.querySelectorAll('.mini-heading')].forEach((h,i)=>{const grid=h.nextElementSibling;if(!grid||grid.closest('details'))return;const d=document.createElement('details');d.className='inventory-fold';const s=document.createElement('summary');s.innerHTML=i===0?'裝備':'消耗品';h.parentNode.insertBefore(d,h);d.appendChild(s);d.appendChild(grid);h.remove();});}
  function fixHost(room){document.getElementById('forgetSession')?.classList.toggle('hidden',state.selfId!==room.hostId);}
  function fixNext(room){const boss=!!room.eventResult?.nextAreaAvailable&&state.selfId===room.hostId;for(const id of ['nextEvent','nextCombatNode']){const b=document.getElementById(id);if(!b)continue;b.classList.toggle('hidden',!boss);if(boss)b.textContent='前往下一個地區';}}
  function apply(room){ensurePanels();fixHost(room);if(room.phase!=='lobby'){renderRoute(room);renderChoices(room);renderShop(room);const rn=document.getElementById('runNumber');if(rn)rn.textContent=`第 ${room.areaIndex+1} 圖 · ${Math.min(14,Number(room.exploration?.position||0)+1)}/14`;if(!room.currentEvent&&!room.combat&&!room.shop&&!room.eventResult)document.getElementById('eventPanel')?.classList.add('hidden');}gold(room);collapseInventory();addProbabilities(room);fixNext(room);}
  socket.on('room:update',room=>requestAnimationFrame(()=>apply(room)));
  requestAnimationFrame(()=>state?.room&&apply(state.room));
  window.KBMExpeditionUI={apply,renderRoute,renderChoices,renderShop};
})();
