(()=>{
 const mobile=window.matchMedia('(max-width:640px)'),tabs={sinner:'罪人',equipment:'裝備',skills:'技能',deck:'牌組',relics:'遺物'},esc=escapeHtml;
 let active=null,lastContent='';
 const self=room=>room?.players?.find(p=>p.id===state.selfId);
 function statText(item){const labels={combat:'戰鬥',observe:'觀察',mobility:'機動',stability:'穩定'};return Object.entries(item?.mods||{}).filter(([,n])=>n).map(([k,n])=>`${labels[k]||k} ${n>0?'+':''}${n}`).join(' · ');}
 function cardGrid(cards){return `<div class="mobile-deck-grid">${KBMDeckUI.grouped(cards).map(g=>KBMDeckUI.cardMarkup(g.card,g.count)).join('')||'<p>目前沒有卡牌。</p>'}</div>`;}
 function content(room,key){
  const p=self(room),s=sinnerById(p?.sinnerId);if(!p||!s)return '<p>尚未選擇罪人。</p>';
  if(key==='sinner'){const eq=equipmentMods(p),mods=statusMods(p),labels={combat:'戰鬥',observe:'觀察',mobility:'機動',stability:'穩定'};return `<section class="mobile-sinner-detail"><h3>${esc(s.name)}</h3><p><b>HP ${p.hp}/${p.maxHp}</b> · 護盾 ${p.temporaryShield||0} · 金幣 ${p.gold||0}</p><div class="mobile-stat-grid">${Object.entries(labels).map(([k,label])=>`<span>${label}<b>${Math.max(0,Number(s.stats[k]||0)+Number(eq[k]||0)+Number(mods[k]||0))}</b></span>`).join('')}</div>${p.serverControl?`<p>伺服器接管：剩餘 ${p.serverControl} 組攻守</p>`:''}<h4>當前狀態</h4>${(p.statuses||[]).map(st=>{const d=statusById(st.id);return `<article class="mobile-info-item"><b>${esc(d?.name||st.id)} ${st.stacks||1} 層</b><small>${st.id==='imprint'?'本場戰鬥':`剩餘 ${st.remaining} 組攻守`}</small><p>${esc(d?.description||'')}</p></article>`;}).join('')||'<p>目前沒有狀態。</p>'}</section>`;}
  if(key==='equipment'){const labels={weapon:'武器',armor:'防具',accessory:'飾品'},item=(e,slot)=>`<article class="mobile-info-item"><small>${esc(labels[slot]||labels[e?.slot]||'裝備')}</small><b>${esc(e?.name||'空')}</b>${e?`<p>${esc(e.description||'')}</p><small>${esc(statText(e))}${e.slot==='armor'?` · HP +${e.survival?.maxHp||0} · 初始護盾 +${e.survival?.startShield||0}`:''}</small>${e.slot==='weapon'?`<p>武器卡：${esc(KBMCards.weaponSummary(e,p.sinnerId))}</p>${e.onHitStatus?`<small>命中狀態：${esc(statusById(e.onHitStatus)?.name||e.onHitStatus)} ${e.statusStacks||1} 層</small>`:''}`:''}`:''}</article>`;return `<h3>當前裝備</h3>${Object.keys(labels).map(k=>item(p.equipment?.[k],k)).join('')}<h4>裝備庫 ${p.equipmentInventory?.length||0}</h4>${(p.equipmentInventory||[]).map(e=>item(e,e.slot)).join('')||'<p>沒有備用裝備。</p>'}`;}
  if(key==='skills')return `<h3>罪人技能 · 已學 ${p.learnedSkills?.length||0}/3</h3>${(state.gameData.sinnerSkills||[]).filter(sk=>sk.sinnerId===p.sinnerId).map(sk=>{const upgrade=(state.gameData.skillUpgradeOptions?.[sk.id]||[]).find(u=>u.id===p.skillUpgrades?.[sk.id]);return `<article class="mobile-info-item">${KBMCardUI.skillMeta(sk)}<div class="skill-title-line"><b>${esc(sk.name)}</b><span class="skill-description">${KBMCardUI.colorText(sk.description)}</span></div><small class="skill-learn-state">${p.learnedSkills?.includes(sk.id)?'已學會':'未學會'} · ${sk.cost} 金幣</small><div class="skill-card-cost">${KBMCardUI.requirementLine(sk)}</div>${upgrade?`<p>升級：${esc(upgrade.name)} · ${esc(upgrade.description)}</p>`:''}</article>`;}).join('')}`;
  if(key==='deck'){const d=room.combat&&!room.combat.ended?room.combat.cardDecks?.[p.id]:null,picked=new Set((room.combat?.selections?.[p.id]?.confirmed?room.combat.selections[p.id].picks||[]:[]).map(x=>x.uid));return `${d?`<h3>本場戰鬥牌組</h3><details open><summary>未出手牌 ${d.hand.filter(c=>!picked.has(c.uid)).length} · 已出 ${picked.size}</summary>${cardGrid(d.hand.filter(c=>!picked.has(c.uid)))}</details><details><summary>抽牌堆 ${d.draw.length}</summary>${cardGrid(d.draw)}</details><details><summary>回收堆 ${d.discard.length}</summary>${cardGrid(d.discard)}</details>`:''}<h3>遠征牌組 ${KBMDeckUI.deckFor(p).length} 張</h3>${KBMDeckUI.expeditionMarkup(KBMDeckUI.deckFor(p))}`;}
  return `<h3>遺物 ${p.relics?.length||0}</h3>${(p.relics||[]).map(id=>(state.gameData.relics||[]).find(r=>r.id===id)).filter(Boolean).map(relic=>`<article class="mobile-info-item"><b>${esc(relic.name)}</b><p>${esc(relic.description)}</p></article>`).join('')||'<p>目前沒有遺物。</p>'}`;
 }
 function ensure(){
  if(document.getElementById('mobileInfoRail'))return;
  const nav=document.createElement('nav');nav.id='mobileInfoRail';nav.setAttribute('aria-label','罪人資訊');nav.innerHTML=Object.entries(tabs).map(([key,label])=>`<button type="button" data-mobile-info="${key}" aria-expanded="false">${label}</button>`).join('');document.body.appendChild(nav);
  nav.querySelectorAll('button').forEach(b=>b.onclick=()=>open(b.dataset.mobileInfo));
  const dialog=document.createElement('dialog');dialog.id='mobileInfoDialog';dialog.className='mobile-info-dialog';dialog.setAttribute('aria-labelledby','mobileInfoTitle');dialog.innerHTML='<header><strong id="mobileInfoTitle"></strong><button type="button" data-close aria-label="關閉資訊">×</button></header><div class="mobile-info-tabs"></div><div class="mobile-info-content"></div>';document.body.appendChild(dialog);
  dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.onclose=()=>{active=null;nav.querySelectorAll('button').forEach(b=>b.setAttribute('aria-expanded','false'));};dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}};
  dialog.querySelector('.mobile-info-tabs').innerHTML=Object.entries(tabs).map(([key,label])=>`<button type="button" data-info-tab="${key}">${label}</button>`).join('');dialog.querySelectorAll('[data-info-tab]').forEach(b=>b.onclick=()=>open(b.dataset.infoTab));
 }
 function open(key){if(!mobile.matches||!self(state.room)?.sinnerId)return;ensure();active=key;lastContent='';const dialog=document.getElementById('mobileInfoDialog');refresh(state.room);if(!dialog.open)dialog.showModal();}
 function refresh(room){const dialog=document.getElementById('mobileInfoDialog');if(!active||!dialog)return;dialog.querySelector('#mobileInfoTitle').textContent=tabs[active];document.querySelectorAll('[data-mobile-info]').forEach(b=>b.setAttribute('aria-expanded',String(b.dataset.mobileInfo===active)));dialog.querySelectorAll('[data-info-tab]').forEach(b=>b.classList.toggle('active',b.dataset.infoTab===active));const html=content(room,active);if(html!==lastContent){const root=dialog.querySelector('.mobile-info-content'),scroll=root.scrollTop;root.innerHTML=html;root.scrollTop=scroll;lastContent=html;KBMDeckUI.bind(root,()=>{KBMDeckUI.apply(room);refresh(room);});}}
 function apply(room){ensure();const enabled=mobile.matches&&room.phase!=='lobby'&&!!self(room)?.sinnerId;document.getElementById('mobileInfoRail').hidden=!enabled;document.body.classList.toggle('mobile-info-enabled',enabled);if(!enabled)document.getElementById('mobileInfoDialog')?.close();else refresh(room);}
 mobile.addEventListener('change',()=>{if(state.room){apply(state.room);window.KBMCombatUI?.render(state.room);}});socket.on('room:update',room=>requestAnimationFrame(()=>apply(room)));requestAnimationFrame(()=>state.room&&apply(state.room));window.KBMMobileInfo={apply,open,refresh};
})();
