(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const hpState=p=>{const r=Number(p?.hp||0)/Math.max(1,Number(p?.maxHp||100));return r<=.3?'critical':r<=.5?'warning':'safe';};
  function renderSelf(player){
    const root=document.getElementById('mySinner'),s=sinnerById(player?.sinnerId);if(!root)return;if(!s){root.innerHTML='<p class="muted">尚未選擇罪人。</p>';return;}
    const eq=equipmentMods(player),sm=statusMods(player),inv=[...(player.inventory||[])];while(inv.length<4)inv.push(null);const val=k=>Number(s.stats[k]||0)+Number(eq[k]||0)+Number(sm[k]||0),health=hpState(player);
    const statuses=(player.statuses||[]).map(a=>{const d=statusById(a.id);return d?`<span class="status-chip ${d.type}" title="${esc(d.description)}">${esc(d.name)} ${a.stacks||1}層 · ${a.id==='imprint'?'本場':a.remaining+'回合'}</span>`:''}).join('');
    root.innerHTML=`<div class="sinner-profile health-${health}" style="--sinner-color:${esc(s.color||'#63bdb0')};--sinner-soft:${esc(s.colorSoft||'#eef8f6')}"><div class="character-header"><div><strong>${esc(s.name)}</strong></div>${health!=='safe'?`<em class="hp-alert">${health==='critical'?'瀕危':'警戒'}</em>`:''}</div><div class="character-hp"><span>HP</span><b>${player.hp}/${player.maxHp}</b><div class="hp-track"><i style="width:${Math.max(0,player.hp/player.maxHp*100)}%"></i></div></div>${statuses?`<div class="status-list">${statuses}</div>`:''}<div class="stat-grid"><div><span>戰鬥</span><b>${val('combat')}</b></div><div><span>觀察</span><b>${val('observe')}</b></div><div><span>機動</span><b>${val('mobility')}</b></div><div><span>穩定</span><b>${val('stability')}</b></div></div><div class="mini-heading">裝備</div><div class="equipment-grid"></div><div class="mini-heading">消耗品 <span>${inv.filter(Boolean).length}/4</span></div><div class="inventory-grid">${inv.map((x,i)=>x?`<button class="inventory-slot filled" data-item-index="${i}" title="${esc(x.description||'')}"><span>${i+1}</span><b>${esc(x.name||'道具')}</b><small>使用</small></button>`:`<div class="inventory-slot"><span>${i+1}</span><b>空</b></div>`).join('')}</div></div>`;
  }
  function renderTeam(room){const root=document.getElementById('teamInfo');if(!root)return;root.innerHTML=room.players.map(p=>{const s=sinnerById(p.sinnerId),st=(p.statuses||[]).map(a=>statusById(a.id)?.name).filter(Boolean).join('、'),health=hpState(p);return `<div data-player-id="${esc(p.id)}" class="team-row health-${health}" style="--sinner-color:${esc(s?.color||'#9ba3a7')};--sinner-soft:${esc(s?.colorSoft||'#f3f3f3')}"><div><b>${esc(s?.name||p.name)}</b><small>${p.connected?'在線':'離線'}${st?` · ${esc(st)}`:''}</small></div><span>${p.hp}/${p.maxHp}${health==='critical'?' · 瀕危':health==='warning'?' · 警戒':''}</span></div>`}).join('');}
  function apply(room){const player=room?.players?.find(p=>p.id===state.selfId);if(!player)return;renderSelf(player);renderTeam(room);}
  socket.on('room:update',room=>requestAnimationFrame(()=>apply(room)));requestAnimationFrame(()=>state?.room&&apply(state.room));window.KBMSinnerUI={apply,renderSelf,renderTeam};
})();
