(()=>{
  const STAT={combat:'戰鬥',observe:'觀察',mobility:'機動',stability:'穩定'},TYPE={slash:'斬擊',blunt:'鈍擊',pierce:'突擊'};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function apply(room){
    const player=room?.players?.find(p=>p.id===state.selfId),root=document.getElementById('mySinner');if(!player||!root||!player.sinnerId)return;
    root.querySelector('.skill-fold')?.remove();const list=(state.gameData?.sinnerSkills||[]).filter(s=>s.sinnerId===player.sinnerId),learned=player.learnedSkills||[],locked=!!room.combat&&!room.combat.ended,upgrades=player.skillUpgrades||{},options=state.gameData?.skillUpgradeOptions||{};
    const details=document.createElement('details');details.className='inventory-fold skill-fold';details.innerHTML=`<summary>罪人技能 <span>${learned.length}/3</span></summary>${locked?'<p class="equipment-lock-note">戰鬥進行中，不能學習或升級技能。</p>':''}<div class="skill-list">${list.map(s=>{const has=learned.includes(s.id),full=learned.length>=3,can=!locked&&!has&&!full&&Number(player.gold||0)>=Number(s.cost||0),type=s.kind!=='heal'?TYPE[s.damageType]||'':'',chosen=upgrades[s.id],branches=options[s.id]||[];return `<div class="skill-row ${has?'learned':''}"><div class="skill-main"><strong>${esc(s.name)}</strong>${type?`<span class="skill-damage-type type-${esc(s.damageType)}">${esc(type)}</span>`:''}<small>${KBMCardUI.colorText(s.description||'')}</small><small class="skill-card-cost">發動：${KBMCardUI.conditions(s.cardRequirement)}（本回合出牌）</small><em>${esc(STAT[s.stat]||s.stat||'技能')} · ${Number(s.cost||0)} 金幣${Number(s.power||0)>0&&s.kind!=='heal'?` · 威力 ×${Number(s.power).toFixed(2)}`:''}</em></div><button data-learn-skill="${esc(s.id)}" ${can?'':'disabled'}>${has?'已學會':full?'已滿':locked?'戰鬥鎖定':`${Number(s.cost||0)} 金幣`}</button>${has?`<div class="skill-upgrade-zone">${chosen?`<div class="skill-upgraded">已升級：${esc((branches.find(b=>b.id===chosen)||{}).name||chosen)}</div>`:branches.map(b=>`<button class="skill-upgrade-branch" data-upgrade-skill="${esc(s.id)}" data-upgrade-id="${esc(b.id)}" ${locked||Number(player.gold||0)<Number(b.cost||0)?'disabled':''}><b>${esc(b.name)}</b><span>${esc(b.description)}</span><em>${Number(b.cost||0)} 金幣</em></button>`).join('')}</div>`:''}</div>`}).join('')}</div>`;
    root.appendChild(details);details.querySelectorAll('[data-learn-skill]').forEach(b=>b.onclick=()=>action('skill:learn',{roomId:room.id,skillId:b.dataset.learnSkill}));details.querySelectorAll('[data-upgrade-skill]').forEach(b=>b.onclick=()=>action('skill:upgrade',{roomId:room.id,skillId:b.dataset.upgradeSkill,upgradeId:b.dataset.upgradeId}));
  }
  socket.on('room:update',room=>requestAnimationFrame(()=>apply(room)));requestAnimationFrame(()=>state?.room&&apply(state.room));window.KBMSkillUI={apply};
})();
