(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  let activeTab=null;const openSections=new Set();
  function ensure(){if(document.getElementById('manualMenuToggle'))return;const toggle=document.createElement('button');toggle.id='manualMenuToggle';toggle.className='manual-menu-toggle';toggle.setAttribute('aria-label','開啟選單');toggle.innerHTML='<i></i><i></i><i></i>';const backdrop=document.createElement('div');backdrop.id='manualBackdrop';backdrop.className='manual-backdrop hidden';const drawer=document.createElement('aside');drawer.id='manualDrawer';drawer.className='manual-drawer';drawer.setAttribute('aria-hidden','true');drawer.innerHTML=`<div class="manual-drawer-head"><div><span>EXPEDITION GUIDE</span><strong>遠征選單</strong></div><button id="manualClose" aria-label="關閉選單">×</button></div><nav class="manual-nav"><button aria-expanded="false" data-manual-tab="guide">教學手冊</button><button aria-expanded="false" data-manual-tab="settings">設定</button></nav><div id="manualContent" class="manual-content"></div>`;document.body.append(toggle,backdrop,drawer);const close=()=>{drawer.classList.remove('open');backdrop.classList.add('hidden');drawer.setAttribute('aria-hidden','true');};const open=()=>{render();drawer.classList.add('open');backdrop.classList.remove('hidden');drawer.setAttribute('aria-hidden','false');};drawer.querySelectorAll('[data-manual-tab]').forEach(b=>b.onclick=()=>{activeTab=activeTab===b.dataset.manualTab?null:b.dataset.manualTab;drawer.querySelectorAll('[data-manual-tab]').forEach(x=>{const expanded=x.dataset.manualTab===activeTab;x.classList.toggle('active',expanded);x.setAttribute('aria-expanded',String(expanded));});render();});toggle.onclick=()=>drawer.classList.contains('open')?close():open();backdrop.onclick=close;drawer.querySelector('#manualClose').onclick=close;}
  function statusRows(type){const list=(state?.gameData?.statusEffects||[]).filter(s=>s.type===type);if(!list.length)return '<p>進入房間後會在這裡顯示目前所有狀態效果。</p>';return `<div class="manual-status-list">${list.map(s=>`<div class="manual-status ${esc(s.type)}"><b>${esc(s.name)}</b><span>${esc(s.type==='buff'?'增益':'負面')}</span><p>${esc(s.description)}</p></div>`).join('')}</div>`;}
  function sinnerRows(){const list=state?.gameData?.sinners||[];return `<div class="manual-sinner-colors">${list.map(s=>`<span style="--manual-color:${esc(s.color||'#999')}"><i></i>${esc(s.name)}</span>`).join('')}</div>`;}
  function section(title,body){return `<details class="manual-section" ${openSections.has(title)?'open':''}><summary>${esc(title)}</summary><div>${body}</div></details>`;}
  function render(){const root=document.getElementById('manualContent');if(!root)return;root.querySelectorAll('details').forEach(d=>{const key=d.querySelector('summary').textContent;if(d.open)openSections.add(key);else openSections.delete(key);});root.hidden=!activeTab;if(!activeTab){root.replaceChildren();return;}if(activeTab==='settings'){root.innerHTML='<section class="manual-section"><h3>演出設定</h3><label class="dice-setting"><input type="checkbox" id="diceAnimationSetting"> 播放骰子動畫</label><p>關閉後直接顯示結算結果；不改變骰子或戰鬥規則。設定保留在此裝置。</p></section>';const box=root.querySelector('#diceAnimationSetting');box.checked=window.KBMDice?.enabled()!==false;box.onchange=()=>window.KBMDice?.setEnabled(box.checked);return;}root.innerHTML=[
    section('第一次玩：我要做什麼？',`<p>一場遠征會依序通過三張地圖：初級 → 中級 → 高級。每張地圖共有 14 層，第 14 層固定為 Boss。</p><p>每一層通常提供 2～3 條路線。隊伍投票決定方向；有明確高票就採高票，完全平票則由伺服器隨機決定。</p><p>目標是在資源耗盡前建立裝備、消耗品、技能、遺物，擊敗第三張地圖 Boss。</p>`),
    section('四大屬性',`<div class="manual-stat-grid"><article><b>戰鬥</b><p>強行制壓、近戰判定與多數直接傷害技能。</p></article><article><b>觀察</b><p>辨識異常規律、弱點、陷阱與線索。</p></article><article><b>機動</b><p>每回合先擲與有效機動值相同數量的雙面骰；正面數高者先行動。同點先比較有效機動屬性；仍相同才隨機決定。</p></article><article><b>穩定</b><p>承受壓力、防禦、固定危險源與部分支援技能。</p></article></div><p class="manual-note">裝備與狀態效果都可能使四大屬性上升或下降。</p>`),
    section('斬擊／鈍擊／突擊',`<p>所有敵人都有三種物理耐性。倍率高於 1 代表弱點，低於 1 代表抗性。</p><div class="manual-damage-types"><span>斬擊：適合軟質、接縫、纜線</span><span>鈍擊：適合甲殼、機械、結構體</span><span>突擊：適合狹小核心、深層弱點</span></div><p>雙屬性武器會直接提供不同攻擊選項。</p>`),
    section('護盾',`<p>玩家與敵人都可能取得護盾。受到傷害時會先扣除護盾，護盾歸零後才開始扣 HP。</p><p>防禦骰抵消當回合攻擊；護盾則是額外防護，兩者分開計算。敵方也可能把「取得護盾」列為下一行動，因此可以提前調整本回合策略。</p>`),
    section('節點、迷霧與遭遇池',`<div class="manual-node-grid"><span class="event">事件</span><span class="combat">小怪</span><span class="elite">精英</span><span class="rest">休整</span><span class="shop">商店</span><span class="boss">BOSS</span></div><p>下一層候選直接可見，更深層仍被迷霧遮蔽。每個地區有 3 種 Boss；進入該地區後會隨機抽出其中 1 種作為第 14 層 Boss。</p><p>每區有 5 種精英，同一張地圖已經遇過的精英不會再次出現。</p>`),
    section('探索與牌卡來源',`<p>探索是整趟遠征的推進方式：選擇事件、戰鬥、休整與商店，累積金幣、裝備、遺物及新牌，最後挑戰每張地圖的 Boss。</p><p>卡牌上的「探索」只代表來源，表示遠征途中透過戰鬥獎勵、事件、補給或商店取得的牌；不提供額外倍率。牌的效果取決於朝上的性質、數值及罪孽顏色。</p><p>「線索」目前只累積記錄，尚未用於兌換、解鎖路線或戰鬥加成。</p>`),
    section('危險度',`<p>只有危機事件能提高或降低危險度；休整、技能與換地圖不改變危險度。危險度越高，危機事件 DC、敵人威脅與精英出現機率越高；同時稀有裝備、稀有消耗品與高品質增益機率也提高。</p>`),
    section('危機事件與個人事件',`<p><b>危機事件：</b>所有玩家共同參與，結果可能提高或降低全隊危險度。</p><p><b>個人事件：</b>每個人各自選擇、各自擲骰、各自承擔傷害、狀態與獎勵；個人事件不改變全隊危險度。</p><p>如果某個選項成功後可能取得裝備或消耗品，選項會直接標示。</p>`),
    section('卡牌戰鬥',`<ol><li>一組攻擊與防守完成後才將手牌補到 6 張；已持有 6 張以上不補牌。震顫可能降低補牌目標與上限。能力牌與遺物可額外抽牌，手牌上限 8 張。初始能力牌為 1 張通用卡、2 張罪人專屬卡；一般初始牌組共 19 張，其餘能力牌由探索獲得，允許重複。能力牌每個攻擊或防守回合最多 2 張，高強度效果另有棄牌代價與每場限制。</li><li>卡牌上下各有罪孽顏色、行動與數值；旋轉後朝上的一半生效。</li><li>點擊行動牌旋轉，再按選擇；選中的卡牌向上移動，確認出牌後才隱藏；確認前可按卡牌上的取消收回；滑動只用來捲動畫面。抽牌與回收堆可點開查看卡牌圖示。</li><li>選擇敵人與部位；所有在線存活玩家確認後結算。</li><li>雙方都使用卡牌；每輪畫面依序顯示移動回合、機動投骰與先手結果，再進行攻擊／防守；向上箭頭代表我方攻擊，向下代表我方防守。先完成機動投骰，再開放攻擊或防守回合選牌。正面數較高的一方先攻；同點時比較機動屬性，連機動也相同才隨機決定。多人模式由雙方最高排名的單位決定隊伍先手。攻擊與防守回合皆可自由選擇行動牌；結算及技能條件只採計當前回合對應的牌面：攻擊回合只計輸出牌與輸出技能，防守回合只計防禦牌與支援技能。不符合回合的牌不提供數值或技能條件，但確認後仍會回收。完成一方回合後重新選牌，交換攻守；兩方都完成後才進入下一次移動與機動投骰。被先手擊殺者不再攻擊。攻擊骰總和減去目標剩餘防禦骰點，最低0；防禦骰每次防守回合重擲，該回合被攻擊時逐次消耗。防禦卡不再產生持續護盾；防具、能力與道具護盾仍可吸收剩餘傷害。</li><li>每次攻擊或防守回合結束只回收已出的牌，未用牌留在手上；抽牌堆耗盡才洗回收堆，補滿本次抽牌。</li></ol><p>技能由本回合出的顏色組合發動，每個技能每回合最多 1 次；同時達成的技能全部發動。數字「點（累計）」按罪孽加總；「單張＝」必須有一張卡面恰好等於數字，「單張≥」需要一張卡面達到門檻，不可用數張相加代替。每名罪人有兩個指定卡面條件技能。例：要求暴怒 1 與怠惰 2 以上時，暴怒 2＋怠惰 1＋怠惰 2 無法觸發。攻擊與特殊技能只計輸出卡，治療、防禦與支援技能只計防禦卡。每點擲一顆雙面骰，正面 1／反面 0；按罪人代表色演出，先抵消雙方正面骰，再加骰後增傷，套用抗性、易傷、恐怖與護盾。狀態持續時間與流血、燒傷、再生於一組攻守完成後結算一次。新施加或重新施加的狀態，當前組結束時不扣持續時間；之後每組攻守結束減 1。選單設定可關閉骰子動畫。</p>`),
    section('能力卡與牌組',`<p>每個罪人帶 12 張罪孽行動牌、4 張武器牌及 3 張無色能力牌。初始牌配色依各罪人的技能罪孽需求分配：攻擊面對應輸出技能，防禦面對應支援技能；物理性質保留 LCB 武器特色。</p><p>每個攻擊或防守回合最多使用 2 張能力牌。抽牌、棄牌換手、從回收堆取回行動牌、將抽牌堆的指定牌置頂、複製手中行動牌。除整備抽牌外，其餘能力須棄 1 張未出的手牌。複製每場最多 2 次，僅該場戰鬥有效。</p><p>補給・卡牌以及標示卡牌獎勵的成功事件可取得新牌；戰鬥勝利可從三張新牌選一張或放棄，商店固定提供 3 件卡牌商品，也能每次賣出 1 張自己的卡牌。探索牌最多 24 張，加入本次遠征，重新開始後清空。</p>`),
    section('裝備、金幣與商店',`<p>武器帶入 4 張指定性質與配色的雙向牌；防具與飾品會改變能力值，有些強力裝備同時降低另一項能力。</p><p>探索中可自由換裝，戰鬥開始後裝備鎖定。金幣可用於商店、學習技能與技能升級。</p>`),
    section('休整：個人選擇',`<p>補給與休整合併為「休整」，每位玩家各選一次：補給、小歇或替隊友療傷。所有存活在線玩家完成後才能前進。</p><p><b>補給：</b>取得 1 件隨機武器、防具、飾品或消耗品，品質受目前危險度影響。消耗品欄满時放入共享背包。</p><p><b>小歇：</b>初級恢復生命上限 34%、中級 28%、高級 24%；受污染影響，選項顯示實際可回復 HP。替隊友療傷按隊友生命上限採相同比例，使用自己的本次選擇。</p>`),
    section('罪人技能與升級分支',`<p>每名罪人共有 6 個技能，第一個技能免費學會，一場遠征最多學 3 個。攻擊技能增加當下攻擊骰數；特殊技能施加狀態、改動卡堆或進行額外攻擊。部分技能直接在骰點傷害後加傷害；封印時所有技能不觸發。</p><p>學會技能後可以再選擇 <b>A / B 其中一條升級分支</b>，例如提高直接威力、轉成流血、提高部位破壞、增加無視防禦、擴大治療範圍或強化技能循環。技能不再使用冷卻按鈕，需達成卡牌配色。每個技能只能選一次分支。</p>${sinnerRows()}`),
    section('遠征遺物',`<p>遺物不占武器／防具／飾品欄，而是整趟遠征持續生效的被動效果。裝備庫中的裝備及已取得的遺物可在商店出售；出售遺物會失去效果，同一趟遠征不會再次抽到已出售遺物。</p><p>小怪不掉落遺物，有 55% 機率掉落裝備。精英及 Boss 保證提供三選一遺物；遺物已收集完時改發裝備。戰鬥勝利必定獲得金幣。完成選擇前無法推進下一條路線。</p><p>遺物可強化流血、護盾、部位破壞、標記、危險度、金幣、消耗品、技能循環等不同玩法。</p>`),
    section('狀態效果',`<p>可累積狀態最多 9 層。新施加狀態在當回合末開始流血、燒傷與再生，但不扣持續時間；之後每回合末倒數。麻痺只跳過行動，防禦骰仍可抵擋。刻印只在辛克萊本場戰鬥有效。</p>${section('增益狀態',statusRows('buff'))}${section('負面狀態',statusRows('debuff'))}`),
    section('多人遊戲',`<p>節點選擇採多數決；完全平票由伺服器在平票選項中隨機。戰鬥則需每位在線且存活玩家確認；由伺服器接管的玩家自動出牌。多人模式倒下隊友在下一個節點以 1 HP 復活，當前節點無法藉治療復活；所有玩家死亡才失敗。</p>`),
    section('勝利與失敗',`<p>初級及中級 Boss 擊破後，全隊先完成卡牌與遺物獎勵選擇，再由房主點擊「前往中級挑戰」或「前往高級挑戰」。</p><p><b>勝利：</b>完成三張地圖並擊敗第三張地圖 Boss。</p><p><b>失敗：</b>所有玩家死亡。危險度達到上限只影響遭遇強度，不直接判定失敗。</p><p>結束時會播放 VICTORY / FAIL；約三秒後房主可在同一房間「再來一把」。</p>`)
  ].join('');root.querySelectorAll('details').forEach(d=>d.addEventListener('toggle',()=>{if(!d.isConnected)return;const key=d.querySelector('summary').textContent;if(d.open)openSections.add(key);else openSections.delete(key);}));}
  ensure();socket.on('room:update',()=>{if(document.getElementById('manualDrawer')?.classList.contains('open'))render();});window.KBMTutorialManual={render};
})();
