(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function ensure(){if(document.getElementById('manualMenuToggle'))return;const toggle=document.createElement('button');toggle.id='manualMenuToggle';toggle.className='manual-menu-toggle';toggle.setAttribute('aria-label','開啟選單');toggle.innerHTML='<i></i><i></i><i></i>';const backdrop=document.createElement('div');backdrop.id='manualBackdrop';backdrop.className='manual-backdrop hidden';const drawer=document.createElement('aside');drawer.id='manualDrawer';drawer.className='manual-drawer';drawer.setAttribute('aria-hidden','true');drawer.innerHTML=`<div class="manual-drawer-head"><div><span>EXPEDITION GUIDE</span><strong>遠征選單</strong></div><button id="manualClose" aria-label="關閉選單">×</button></div><nav class="manual-nav"><button class="active" data-manual-tab="guide">教學手冊</button></nav><div id="manualContent" class="manual-content"></div>`;document.body.append(toggle,backdrop,drawer);const close=()=>{drawer.classList.remove('open');backdrop.classList.add('hidden');drawer.setAttribute('aria-hidden','true');};const open=()=>{render();drawer.classList.add('open');backdrop.classList.remove('hidden');drawer.setAttribute('aria-hidden','false');};toggle.onclick=()=>drawer.classList.contains('open')?close():open();backdrop.onclick=close;drawer.querySelector('#manualClose').onclick=close;}
  function statusRows(){const list=state?.gameData?.statusEffects||[];if(!list.length)return '<p>進入房間後會在這裡顯示目前所有狀態效果。</p>';return `<div class="manual-status-list">${list.map(s=>`<div class="manual-status ${esc(s.type)}"><b>${esc(s.name)}</b><span>${esc(s.type==='buff'?'增益':'負面')}</span><p>${esc(s.description)}</p></div>`).join('')}</div>`;}
  function sinnerRows(){const list=state?.gameData?.sinners||[];return `<div class="manual-sinner-colors">${list.map(s=>`<span style="--manual-color:${esc(s.color||'#999')}"><i></i>${esc(s.name)}</span>`).join('')}</div>`;}
  function section(title,body,open=false){return `<details class="manual-section" ${open?'open':''}><summary>${esc(title)}</summary><div>${body}</div></details>`;}
  function render(){const root=document.getElementById('manualContent');if(!root)return;root.innerHTML=[
    section('第一次玩：我要做什麼？',`<p>一場遠征會依序通過三張地圖：初級 → 中級 → 高級。每張地圖共有 14 層，第 14 層固定為 Boss。</p><p>每一層通常提供 2～3 條路線。隊伍投票決定方向；有明確高票就採高票，完全平票則由伺服器隨機決定。</p><p>目標是在資源耗盡前建立裝備、消耗品、技能、遺物與 Build，擊敗第三張地圖 Boss。</p>`,true),
    section('四大屬性',`<div class="manual-stat-grid"><article><b>戰鬥</b><p>強行制壓、近戰判定與多數直接傷害技能。</p></article><article><b>觀察</b><p>辨識異常規律、弱點、陷阱與線索。</p></article><article><b>機動</b><p>閃避、穿越地形、快速突入與高速技能。</p></article><article><b>穩定</b><p>承受壓力、防禦、固定危險源與部分支援技能。</p></article></div><p class="manual-note">裝備與狀態效果都可能使四大屬性上升或下降。</p>`),
    section('斬擊／鈍擊／突擊',`<p>所有敵人都有三種物理耐性。倍率高於 1 代表弱點，低於 1 代表抗性。</p><div class="manual-damage-types"><span>斬擊：適合軟質、接縫、纜線</span><span>鈍擊：適合甲殼、機械、結構體</span><span>突擊：適合狹小核心、深層弱點</span></div><p>雙屬性武器會直接提供不同攻擊選項。</p>`),
    section('護盾',`<p>玩家與敵人都可能取得護盾。受到傷害時會先扣除護盾，護盾歸零後才開始扣 HP。</p><p>只有部分罪人技能能產生護盾；並非每名罪人都有護盾技能。敵方也可能把「取得護盾」列為下一行動，因此可以提前調整本回合策略。</p>`),
    section('節點、迷霧與遭遇池',`<div class="manual-node-grid"><span class="event">事件</span><span class="combat">小怪</span><span class="supply">補給</span><span class="elite">精英</span><span class="rest">休整</span><span class="shop">商店</span><span class="boss">BOSS</span></div><p>下一層候選直接可見，更深層仍被迷霧遮蔽。每個地區有 3 種 Boss；進入該地區後會隨機抽出其中 1 種作為第 14 層 Boss。</p><p>每區有 5 種精英，同一張地圖已經遇過的精英不會再次出現。</p>`),
    section('危險度',`<p>危險度越高，團體事件 DC、敵人威脅與精英出現機率越高；同時稀有裝備、稀有消耗品與高品質增益機率也提高。</p>`),
    section('團體事件與個人事件',`<p><b>團體事件：</b>所有玩家共同參與，結果可能提高或降低全隊危險度。</p><p><b>個人事件：</b>每個人各自選擇、各自擲骰、各自承擔傷害、狀態與獎勵；個人事件不改變全隊危險度。</p><p>如果某個選項成功後可能取得裝備或消耗品，選項會直接標示。</p>`),
    section('卡牌戰鬥',`<ol><li>每回合將手牌補到 5 張；已持有 5 張以上不補牌。能力牌與遺物可額外抽牌，手牌上限 8 張。</li><li>卡牌上下各有罪孽顏色、行動與數值；旋轉後朝上的一半生效。</li><li>點擊卡牌旋轉，再向上滑出牌；再次上滑可收回。也可用出牌按鈕或鍵盤 ↑，R 旋轉。</li><li>選擇敵人與部位；所有在線存活玩家確認後結算。</li><li>雙方都使用卡牌；選牌完成後同時結算。攻擊骰總和減去目標剩餘防禦骰點，最低0；防禦骰每回合重擲，該回合被攻擊時逐次消耗。防禦卡不再產生持續護盾；防具、能力與道具護盾仍可吸收剩餘傷害。</li><li>回合結束只回收已出的牌，未用牌留在手上；抽牌堆耗盡才洗回收堆，補滿本次抽牌。</li></ol><p>技能由本回合出的顏色組合發動，每個技能每回合最多 1 次；同時達成的技能全部發動。條件按卡牌張數計算，不按數字。</p>`),
    section('能力卡與牌組',`<p>每個罪人帶 12 張 LCB 配色行動牌、4 張武器牌及 3 張無色能力牌。初始行動配色參考 LCB 的 3：2：1；上下行動及數值是本遊戲的平衡改編。</p><p>每回合最多使用 2 張能力牌。抽牌、棄牌換手、從回收堆取回行動牌、將抽牌堆的指定牌置頂、複製手中行動牌。除整備抽牌外，其餘能力須棄 1 張未出的手牌。複製每場最多 2 次，僅該場戰鬥有效。</p><p>補給及成功事件有機率取得新牌；戰鬥勝利可從三張新牌選一張或放棄，商店固定提供 3 件卡牌商品，也能每次賣出 1 張自己的卡牌。探索牌最多 24 張，加入本次遠征，重新開始後清空。</p>`),
    section('裝備、金幣與商店',`<p>武器帶入 4 張指定性質與配色的雙向牌；防具與飾品會改變能力值，有些強力裝備同時降低另一項能力。</p><p>探索中可自由換裝，戰鬥開始後裝備鎖定。金幣可用於商店、學習技能與技能升級。</p>`),
    section('補給節點',`<p>多人遊戲的補給不是搶一件物品：每位在線玩家都會各自取得 1 份補給。背包滿時會依現有規則轉入共享處理。</p>`),
    section('罪人技能與升級分支',`<p>每名罪人共有 6 個技能，第一個技能免費學會，一場遠征最多學 3 個。攻擊型技能具有斬／鈍／突屬性，會受到敵人抗性影響。</p><p>學會技能後可以再選擇 <b>A / B 其中一條升級分支</b>，例如提高直接威力、轉成流血、提高部位破壞、增加無視防禦、擴大治療範圍或強化技能循環。技能不再使用冷卻按鈕，需達成卡牌配色。每個技能只能選一次分支。</p>${sinnerRows()}`),
    section('遠征遺物',`<p>遺物不占武器／防具／飾品欄，而是整趟遠征持續生效的被動效果。裝備庫中的裝備及已取得的遺物可在商店出售；出售遺物會失去效果，同一趟遠征不會再次抽到已出售遺物。</p><p>小怪戰有 18% 機率提供遺物三選一；未取得遺物時，有 55% 機率掉落裝備。精英及前兩張地圖的 Boss 保證提供三選一遺物；遺物已收集完時改發裝備。戰鬥勝利必定獲得金幣。完成選擇前無法推進下一條路線。</p><p>遺物可強化流血、護盾、部位破壞、標記、危險度、金幣、消耗品、技能循環等不同玩法。</p>`),
    section('Build 標籤與流派',`<p>遊戲會依你目前的技能、裝備與遺物判斷流派傾向，例如：流血、護盾、部位破壞、弱點獵殺、標記集火、異常控制、低血狂戰、危險賭徒、技能循環、金幣、消耗品與群體清場。</p><p>這些標籤會讓相關裝備、商店商品與遺物的出現權重略微提高，但最高只提供有限導向，不會保證出現指定物品，也不會鎖死其他流派。</p>`),
    section('狀態效果',statusRows()),
    section('多人遊戲',`<p>節點選擇採多數決；完全平票由伺服器在平票選項中隨機。戰鬥則需每位在線且存活玩家確認。</p>`),
    section('勝利與失敗',`<p><b>勝利：</b>完成三張地圖並擊敗第三張地圖 Boss。</p><p><b>失敗：</b>隊伍全滅，或危險度達到章節上限。</p><p>結束時會播放 VICTORY / FAIL；約三秒後房主可在同一房間「再來一把」。</p>`)
  ].join('');}
  ensure();socket.on('room:update',()=>{if(document.getElementById('manualDrawer')?.classList.contains('open'))render();});window.KBMTutorialManual={render};
})();
