const crypto = require('crypto');
const { AREAS, SINNERS } = require('../shared/game-data');
const { loadRooms, saveRooms } = require('./persistence');

const rooms = new Map();
const MAX_PLAYERS = 4;
const RECONNECT_GRACE_MS = 10 * 60 * 1000;
const ROOM_SIGNING_SECRET = process.env.ROOM_SIGNING_SECRET || 'local-dev-v0.8-signing-secret-change-me';
const NODE_LABELS = { event:'事件', combat:'小怪', supply:'補給', elite:'精英', rest:'休整', boss:'BOSS', unknown:'未確認' };

function cleanName(name){const value=String(name||'').trim().slice(0,16);return value||'探索者';}
function clamp(n,min,max){return Math.max(min,Math.min(max,Number(n)||0));}
function makeRoomId(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(let attempt=0;attempt<100;attempt++){let id='';for(let i=0;i<4;i++)id+=alphabet[crypto.randomInt(0,alphabet.length)];if(!rooms.has(id))return id;}throw new Error('暫時無法建立房間，請重試。');}
function emptyEquipment(){return {weapon:null,armor:null,accessory:null};}
function makePlayer(socketId,playerName,reconnectToken){return {id:crypto.randomUUID(),reconnectToken:reconnectToken||crypto.randomUUID(),socketId,connected:true,disconnectedAt:null,name:cleanName(playerName),hp:100,maxHp:100,sinnerId:'',ready:false,inventory:[],equipment:emptyEquipment(),statuses:[],temporaryShield:0};}
function makeNode(index,type='unknown'){return {index,type,label:NODE_LABELS[type],resolved:false,revealed:type!=='unknown'};}
function blankRoute(){const route=Array.from({length:10},(_,i)=>makeNode(i,'unknown'));route[9]=makeNode(9,'boss');return route;}
function freshExploration(danger=0){return {danger:clamp(danger,0,6),dangerMax:6,clues:0,scenes:0,route:blankRoute(),position:0,chapter:0};}
function signRecovery(room){return crypto.createHmac('sha256',ROOM_SIGNING_SECRET).update(`${room.id}:${room.hostId}`).digest('hex');}
function verifyRecovery(roomId,hostId,token){const expected=crypto.createHmac('sha256',ROOM_SIGNING_SECRET).update(`${roomId}:${hostId}`).digest('hex');const a=Buffer.from(String(expected)),b=Buffer.from(String(token||''));return a.length===b.length&&crypto.timingSafeEqual(a,b);}
function recoverySnapshot(room){return JSON.parse(JSON.stringify(room));}
function persist(){saveRooms(rooms);}
function sanitizeEquipment(raw){const source=raw&&typeof raw==='object'?raw:{};return {weapon:source.weapon||null,armor:source.armor||null,accessory:source.accessory||null};}
function sanitizeStatuses(raw){if(!Array.isArray(raw))return[];return raw.slice(0,12).map((s)=>({id:String(s?.id||''),remaining:clamp(s?.remaining,0,20)})).filter((s)=>s.id&&s.remaining>0);}
function sanitizeRoute(raw){if(!Array.isArray(raw)||raw.length!==10)return blankRoute();return raw.map((n,i)=>{const type=i===9?'boss':['event','combat','supply','elite','rest','unknown'].includes(n?.type)?n.type:'unknown';return {...makeNode(i,type),resolved:!!n?.resolved,revealed:i===9||!!n?.revealed||type!=='unknown'};});}

function sanitizeRestoredRoom(snapshot){
  if(!snapshot||typeof snapshot!=='object')throw new Error('存檔格式不正確。');
  const id=String(snapshot.id||'').toUpperCase();if(!/^[A-Z2-9]{4}$/.test(id))throw new Error('房號格式不正確。');
  if(!Array.isArray(snapshot.players)||snapshot.players.length<1||snapshot.players.length>MAX_PLAYERS)throw new Error('玩家資料不正確。');
  const selectedAreas=(Array.isArray(snapshot.selectedAreas)?snapshot.selectedAreas:Array.isArray(snapshot.mapOptions)?snapshot.mapOptions:[]).filter((x,i,a)=>AREAS.some((area)=>area.id===x)&&a.indexOf(x)===i).slice(0,3);
  const areaIndex=clamp(snapshot.areaIndex,0,Math.max(0,selectedAreas.length-1));
  const areaId=selectedAreas[areaIndex]||selectedAreas[0]||'';
  const players=snapshot.players.map((p)=>({id:String(p.id||crypto.randomUUID()),reconnectToken:String(p.reconnectToken||crypto.randomUUID()),socketId:'',connected:false,disconnectedAt:Date.now(),name:cleanName(p.name),hp:clamp(p.hp??100,0,100),maxHp:100,sinnerId:SINNERS.some((s)=>s.id===p.sinnerId)?p.sinnerId:'',ready:!!p.ready,inventory:Array.isArray(p.inventory)?p.inventory.slice(0,4):[],equipment:sanitizeEquipment(p.equipment),statuses:sanitizeStatuses(p.statuses),temporaryShield:clamp(p.temporaryShield,0,99)}));
  const hostId=players.some((p)=>p.id===snapshot.hostId)?snapshot.hostId:players[0].id;
  const ex=snapshot.exploration||{};const exploration={danger:clamp(ex.danger,0,6),dangerMax:6,clues:clamp(ex.clues,0,999),scenes:clamp(ex.scenes,0,999),route:sanitizeRoute(ex.route),position:clamp(ex.position,0,9),chapter:areaIndex};
  const votes={};for(const p of players)if(typeof snapshot.votes?.[p.id]==='string')votes[p.id]=snapshot.votes[p.id];
  return {id,createdAt:Number(snapshot.createdAt||Date.now()),phase:['exploration','victory','defeat'].includes(snapshot.phase)?snapshot.phase:'lobby',hostId,players,selectedAreas,areaIndex,areaId,run:Math.max(0,Number(snapshot.run||0)),sharedInventory:Array.isArray(snapshot.sharedInventory)?snapshot.sharedInventory.slice(0,100):[],currentEvent:snapshot.currentEvent&&typeof snapshot.currentEvent==='object'?snapshot.currentEvent:null,eventResult:snapshot.eventResult&&typeof snapshot.eventResult==='object'?snapshot.eventResult:null,combat:snapshot.combat&&typeof snapshot.combat==='object'?snapshot.combat:null,nodeReward:snapshot.nodeReward&&typeof snapshot.nodeReward==='object'?snapshot.nodeReward:null,votes,exploration};
}
function restoreRoom(snapshot,recoveryToken,socketId,playerId,reconnectToken){const candidate=sanitizeRestoredRoom(snapshot);if(rooms.has(candidate.id))throw new Error('房間已經存在。');if(!verifyRecovery(candidate.id,candidate.hostId,recoveryToken))throw new Error('房間復原授權無效。');const player=candidate.players.find((p)=>p.id===playerId&&p.reconnectToken===reconnectToken);if(!player||player.id!==candidate.hostId)throw new Error('只有原房主可以復原房間。');player.socketId=socketId;player.connected=true;player.disconnectedAt=null;rooms.set(candidate.id,candidate);persist();return {room:candidate,player};}
function createRoom(socketId,playerName,reconnectToken){const player=makePlayer(socketId,playerName,reconnectToken);const room={id:makeRoomId(),createdAt:Date.now(),phase:'lobby',hostId:player.id,players:[player],selectedAreas:[],areaIndex:0,areaId:'',run:0,sharedInventory:[],currentEvent:null,eventResult:null,combat:null,nodeReward:null,votes:{},exploration:freshExploration()};rooms.set(room.id,room);persist();return {room,player};}
function joinRoom(roomId,socketId,playerName,reconnectToken){const id=String(roomId||'').trim().toUpperCase(),room=rooms.get(id);if(!room)throw new Error('找不到房間。');if(room.phase!=='lobby')throw new Error('遊戲已經開始。請使用原本的瀏覽器重新連線。');if(room.players.length>=MAX_PLAYERS)throw new Error('房間已滿。');const player=makePlayer(socketId,playerName,reconnectToken);room.players.push(player);persist();return {room,player};}
function resumeRoom(roomId,socketId,playerId,reconnectToken){const room=rooms.get(String(roomId||'').trim().toUpperCase());if(!room)throw new Error('房間已不存在。');const player=room.players.find((p)=>p.id===playerId&&p.reconnectToken===reconnectToken);if(!player)throw new Error('無法驗證原本的玩家席位。');player.socketId=socketId;player.connected=true;player.disconnectedAt=null;persist();return {room,player};}
function markDisconnected(socketId){for(const room of rooms.values()){const player=room.players.find((p)=>p.socketId===socketId);if(!player)continue;player.socketId='';player.connected=false;player.disconnectedAt=Date.now();persist();return {room,player};}return null;}
function removeExpiredPlayer(roomId,playerId,disconnectedAt){const room=rooms.get(roomId);if(!room)return null;const index=room.players.findIndex((p)=>p.id===playerId);if(index<0)return null;const player=room.players[index];if(player.connected||player.disconnectedAt!==disconnectedAt||Date.now()-disconnectedAt<RECONNECT_GRACE_MS)return null;room.players.splice(index,1);delete room.votes[player.id];if(!room.players.length){rooms.delete(room.id);persist();return {room:null,player};}if(room.hostId===player.id)room.hostId=room.players.find((p)=>p.connected)?.id||room.players[0].id;persist();return {room,player};}
function toggleArea(room,player,areaId){if(player.id!==room.hostId)throw new Error('只有房主可以選擇地區。');if(room.phase!=='lobby')throw new Error('探索開始後不能更換地區。');if(!AREAS.some((a)=>a.id===areaId))throw new Error('找不到地區。');const idx=room.selectedAreas.indexOf(areaId);if(idx>=0)room.selectedAreas.splice(idx,1);else{if(room.selectedAreas.length>=3)throw new Error('最多只能選擇 3 個地區。');room.selectedAreas.push(areaId);}room.areaId=room.selectedAreas[0]||'';persist();}
function setSinner(room,player,sinnerId){if(room.phase!=='lobby')throw new Error('探索開始後不能更換罪人。');const sinner=SINNERS.find((s)=>s.id===sinnerId);if(!sinner)throw new Error('找不到罪人。');if(room.players.some((p)=>p.id!==player.id&&p.sinnerId===sinner.id))throw new Error('這名罪人已被其他玩家選擇。');player.sinnerId=sinner.id;player.ready=true;persist();}
function resetForStart(room){if(room.selectedAreas.length!==3)throw new Error('房主必須先選滿 3 個探索地區。');room.run=1;room.areaIndex=0;room.areaId=room.selectedAreas[0];room.phase='exploration';room.exploration=freshExploration(0);room.currentEvent=null;room.eventResult=null;room.combat=null;room.nodeReward=null;room.votes={};room.players.forEach((p)=>{p.hp=p.maxHp;p.statuses=[];p.temporaryShield=0;});persist();}
function beginNextArea(room){if(room.areaIndex>=room.selectedAreas.length-1)return false;room.areaIndex+=1;room.areaId=room.selectedAreas[room.areaIndex];const carryDanger=Math.max(0,room.exploration.danger-1);const carryClues=room.exploration.clues;room.exploration=freshExploration(carryDanger);room.exploration.clues=carryClues;room.exploration.chapter=room.areaIndex;room.run+=1;room.currentEvent=null;room.eventResult=null;room.combat=null;room.nodeReward=null;room.votes={};persist();return true;}
function publicRoom(room){return {id:room.id,phase:room.phase,hostId:room.hostId,players:room.players.map(({socketId,reconnectToken,disconnectedAt,...p})=>p),selectedAreas:room.selectedAreas,areaIndex:room.areaIndex,areaId:room.areaId,run:room.run,sharedInventory:room.sharedInventory,currentEvent:room.currentEvent,eventResult:room.eventResult,combat:room.combat,nodeReward:room.nodeReward,votes:room.votes,exploration:room.exploration||freshExploration()};}
function loadPersistedRooms(){const snapshots=loadRooms();for(const raw of snapshots){try{const room=sanitizeRestoredRoom(raw);room.players.forEach((p)=>{p.connected=false;p.socketId='';p.disconnectedAt=Date.now();});rooms.set(room.id,room);}catch(error){console.warn('Skipped invalid persisted room:',error.message);}}if(rooms.size)persist();return rooms.size;}

module.exports={rooms,RECONNECT_GRACE_MS,signRecovery,recoverySnapshot,restoreRoom,persist,createRoom,joinRoom,resumeRoom,markDisconnected,removeExpiredPlayer,toggleArea,setSinner,publicRoom,loadPersistedRooms,freshExploration,resetForStart,beginNextArea,NODE_LABELS};
