const Cards=require('../cards/card-manager');
const legacy=require('../room-manager');
const {starterWeaponFor}=require('../../shared/starter-equipment');
const {loadRooms}=require('../persistence');
const {profileForPlayer}=require('../builds/build-affinity');

function cloneItem(item){return item?JSON.parse(JSON.stringify(item)):null;}
function ensureEncounterMemory(room,source=null){room.exploration=room.exploration||legacy.freshExploration(0,room.areaIndex||0);const from=source?.exploration||source||{};room.exploration.bossId=String(from.bossId??room.exploration.bossId??'');room.exploration.seenEliteIds=Array.isArray(from.seenEliteIds)?from.seenEliteIds.map(String).slice(0,20):(Array.isArray(room.exploration.seenEliteIds)?room.exploration.seenEliteIds:[]);return room;}
function resetEncounterMemory(room){ensureEncounterMemory(room);room.exploration.bossId='';room.exploration.seenEliteIds=[];return room;}
function ensurePlayerEquipment(player){player.equipment=player.equipment&&typeof player.equipment==='object'?player.equipment:{weapon:null,armor:null,accessory:null};player.equipmentInventory=Array.isArray(player.equipmentInventory)?player.equipmentInventory:[];const starter=starterWeaponFor(player.sinnerId);if(starter&&player.equipment.weapon?.id===starter.id)player.equipment.weapon=cloneItem(starter);require('../equipment/equipment-survival').sync(player);return player;}
function ensurePlayerBuild(player,source=null){const src=source||player;if(source)player.hp=Math.min(player.maxHp,Math.max(0,Number(source.hp)||0));player.explorationCards=Array.isArray(src.explorationCards)?src.explorationCards.slice(0,24):[];Cards.ensureCollection(player);player.soldRelics=Array.isArray(src?.soldRelics)?src.soldRelics.map(String).slice(0,30):[];player.relics=Array.isArray(src?.relics)?src.relics.map(String).slice(0,30):(Array.isArray(player.relics)?player.relics:[]);player.skillUpgrades=src?.skillUpgrades&&typeof src.skillUpgrades==='object'?{...src.skillUpgrades}:(player.skillUpgrades&&typeof player.skillUpgrades==='object'?player.skillUpgrades:{});return player;}
function ensureRoomBuild(room,source=null){room.cardChoices=source?.cardChoices||room.cardChoices||{};const src=source||room;room.relicChoices=src?.relicChoices&&typeof src.relicChoices==='object'?JSON.parse(JSON.stringify(src.relicChoices)):(room.relicChoices||{});return room;}
function applyStarterWeapon(player,{resetInventory=false}={}){ensurePlayerEquipment(player);if(resetInventory)player.equipmentInventory=[];const starter=starterWeaponFor(player.sinnerId);if(starter)player.equipment.weapon=cloneItem(starter);require('../equipment/equipment-survival').sync(player);return player;}
function createRoom(...args){const result=legacy.createRoom(...args);ensurePlayerEquipment(result.player);ensurePlayerBuild(result.player);ensureEncounterMemory(result.room);ensureRoomBuild(result.room);return result;}
function joinRoom(...args){const result=legacy.joinRoom(...args);ensurePlayerEquipment(result.player);ensurePlayerBuild(result.player);ensureEncounterMemory(result.room);ensureRoomBuild(result.room);return result;}
function resumeRoom(...args){const result=legacy.resumeRoom(...args);ensurePlayerEquipment(result.player);ensurePlayerBuild(result.player);ensureEncounterMemory(result.room);ensureRoomBuild(result.room);return result;}
function restoreRoom(snapshot,...args){const result=legacy.restoreRoom(snapshot,...args);const savedPlayers=new Map((snapshot?.players||[]).map(p=>[String(p.id),p]));for(const player of result.room.players){ensurePlayerEquipment(player);const saved=savedPlayers.get(String(player.id));if(saved)player.hp=Math.min(player.maxHp,Math.max(0,Number(saved.hp)||0));player.equipmentInventory=Array.isArray(saved?.equipmentInventory)?saved.equipmentInventory.slice(0,40).map(cloneItem):[];ensurePlayerBuild(player,saved);if(!player.equipment.weapon&&player.sinnerId)applyStarterWeapon(player);}ensureEncounterMemory(result.room,snapshot);ensureRoomBuild(result.room,snapshot);if(result.room.combat&&!result.room.combat.ended&&!result.room.combat.cardMode)Cards.initialize(result.room);legacy.persist();return result;}
function setSinner(room,player,sinnerId){legacy.setSinner(room,player,sinnerId);applyStarterWeapon(player,{resetInventory:true});player.relics=[];player.soldRelics=[];player.skillUpgrades={};player.explorationCards=[];Cards.starterSkill(player);legacy.persist();}
function resetForStart(room){for(const p of room.players){p.maxHp=p.baseMaxHp||100;p.armorHpBonus=0;}legacy.resetForStart(room);resetEncounterMemory(room);room.cardChoices={};room.relicChoices={};for(const player of room.players){ensurePlayerEquipment(player);player.relics=[];player.soldRelics=[];player.skillUpgrades={};player.explorationCards=[];Cards.starterSkill(player);if(!player.equipment.weapon&&player.sinnerId)applyStarterWeapon(player);}legacy.persist();}
function beginNextArea(room){const ok=legacy.beginNextArea(room);if(ok){resetEncounterMemory(room);room.cardChoices={};room.relicChoices={};legacy.persist();}return ok;}
function restartRoom(room,player){if(player.id!==room.hostId)throw new Error('只有房主可以重新開始。');if(!['victory','defeat'].includes(room.phase))throw new Error('目前還不能重新開始。');room.phase='lobby';room.selectedAreas=[];room.areaIndex=0;room.areaId='';room.run=0;room.sharedInventory=[];room.currentEvent=null;room.eventResult=null;room.combat=null;room.shop=null;room.nodeReward=null;room.votes={};room.routeVotes={};room.cardChoices={};room.relicChoices={};room.exploration=legacy.freshExploration(0,0);resetEncounterMemory(room);for(const p of room.players){p.maxHp=p.baseMaxHp||100;p.armorHpBonus=0;p.hp=p.maxHp;p.gold=0;p.sinnerId='';p.ready=false;p.inventory=[];p.equipment={weapon:null,armor:null,accessory:null};p.equipmentInventory=[];p.statuses=[];p.temporaryShield=0;p.learnedSkills=[];p.relics=[];p.soldRelics=[];p.skillUpgrades={};p.explorationCards=[];}legacy.persist();return room;}
function loadPersistedRooms(){const rawSnapshots=loadRooms(),rawById=new Map(rawSnapshots.map(r=>[String(r?.id||''),r]));const count=legacy.loadPersistedRooms();for(const room of legacy.rooms.values()){const raw=rawById.get(room.id);ensureEncounterMemory(room,raw);ensureRoomBuild(room,raw);const savedPlayers=new Map((raw?.players||[]).map(p=>[String(p.id),p]));for(const player of room.players){ensurePlayerEquipment(player);ensurePlayerBuild(player,savedPlayers.get(String(player.id)));if(!player.equipment.weapon&&player.sinnerId)applyStarterWeapon(player);}if(room.combat&&!room.combat.ended&&!room.combat.cardMode)Cards.initialize(room);}if(count)legacy.persist();return count;}
function publicRoom(room){const base=legacy.publicRoom(room);return {...base,visualEffect:room.visualEffect||null,cardChoices:room.cardChoices||{},relicChoices:room.relicChoices||{},buildProfiles:Object.fromEntries(room.players.map(p=>[p.id,profileForPlayer(p)]))};}

module.exports={...legacy,createRoom,joinRoom,resumeRoom,restoreRoom,setSinner,resetForStart,beginNextArea,restartRoom,loadPersistedRooms,publicRoom,ensurePlayerEquipment,applyStarterWeapon,ensureEncounterMemory,resetEncounterMemory,ensurePlayerBuild,ensureRoomBuild};
