const C=require('../../shared/cards'),{getStatus}=require('../../shared/status-effects');
function write(room,text){const c=room.combat;if(c)(c.log=c.log||[]).push({round:c.round,text});}
function name(room,id){return room.players.find(p=>p.id===id)?.name||room.combat.enemies.find(e=>e.instanceId===id)?.name||id;}
function effects(room,events){for(const e of events||[])write(room,e.eventType==='card'?name(room,e.targetId)+' '+({discard:'丟棄',destroy:'破壞',steal:'偷取'}[e.kind]||e.kind)+'「'+(e.card?.name||'卡牌')+'」。':name(room,e.targetId)+' 獲得 '+(getStatus(e.statusId)?.name||e.statusId)+' '+(e.stacks||1)+' 層／'+e.duration+' 回合。');}
function actions(room,records,enemy=false){for(const r of records){const who=enemy?name(room,r.enemyId):r.sinner;write(room,who+'：'+(r.action||r.label)+'。'+(r.target?'目標 '+r.target+(r.part?'／'+r.part:'')+'。':'')+(r.blocked?'蓄力被中斷。':'')+'傷害 '+Number(r.dealt??r.damage??0)+'，護盾吸收 '+Number(r.shieldAbsorbed||0)+'。'+(r.partDestroyed?'部位已破壞。':'')+(r.gainedShield||r.shieldGained?'新增護盾 '+Number(r.gainedShield||r.shieldGained)+'。':'')+(r.summoned?'召喚 '+r.summoned+'。':''));
 for(const x of r.clashes||[])write(room,who+' → '+x.target+'：攻擊骰 ['+x.attackRolls.join(',')+']＝'+x.attackTotal+'，防禦骰 ['+x.defenseRolls.join(',')+'] 剩餘 '+x.defenseTotal+'，淨骰點 '+x.net+(x.chargedBase!=null?'；蓄力基礎傷害 '+x.chargedBase+'，穩定 '+x.stability+' 減傷 '+x.stabilityReduction+'，實際 HP 傷害 '+x.damage:'')+'。');
 for(const h of r.healing||[])write(room,name(room,h.playerId)+' 恢復 '+h.amount+' HP。');if(r.defenseRolls?.length)write(room,who+' 防禦骰 ['+r.defenseRolls.join(',')+']。');effects(room,r.statusEvents);
 for(const id of r.defeatedTargets||[])write(room,name(room,id)+' 被擊敗。');}}
function picks(room){for(const p of room.players.filter(p=>p.connected&&p.hp>0)){const d=room.combat.cardDecks?.[p.id],s=room.combat.selections[p.id];write(room,p.name+' 出牌：'+((s?.picks||[]).map(x=>{const card=d?.hand.find(c=>c.uid===x.uid),f=card&&C.face(card,x.flipped);return f?(card.name||'行動牌')+'（'+C.SINS[f.sin].name+' '+C.TYPES[f.type]+f.value+'）':'無效牌';}).join('、')||'空過')+'。');}}
function snapshot(room){for(const e of [...room.players,...room.combat.enemies])write(room,(e.name||'單位')+'：HP '+Number(e.hp??e.currentHp)+'/'+e.maxHp+'，護盾 '+Number(e.temporaryShield??e.shield??0)+'，狀態 '+((e.statuses||[]).map(s=>(getStatus(s.id)?.name||s.id)+' '+(s.stacks||1)+'層／'+s.remaining+'回合').join('、')||'無')+'。');}
module.exports={write,actions,effects,picks,snapshot};
