const BOSSES = [
  {area:'zone-1',id:'z1-boss-cashier',name:'永不結帳的收銀員',hp:220,attack:20,defense:15,trait:'會把累積的「帳款」轉為全體傷害。',phases:[{at:1,label:'營業中',skills:[{label:'找零錯誤',type:'status',mult:.55,statusId:'marked',weight:22,description:'將一名隊員列為未結清帳款。'},{label:'結帳掃擊',type:'sweep',mult:.68,weight:20,description:'收銀帶橫掃全隊。'}]},{at:.5,label:'最後結帳',skills:[{label:'帳款清算',type:'sweep',mult:.95,weight:30,description:'把累積帳款化為全體高傷害。'},{label:'拒絕退款',type:'enrage',attackBoost:.25,weight:18,description:'拒絕結束營業，攻擊提高。'}]}]},
  {area:'zone-2',id:'z2-boss-core',name:'逆流維修核心',hp:260,attack:23,defense:17,trait:'高壓階段會交替封鎖不同類型行動。',phases:[{at:1,label:'穩壓模式',skills:[{label:'逆流脈衝',type:'sweep',mult:.72,weight:22,description:'管線壓力反向衝擊全隊。'},{label:'維修鎖定',type:'status',mult:.6,statusId:'slowed',weight:20,description:'鎖死一名隊員的行動節奏。'}]},{at:.55,label:'超壓模式',skills:[{label:'全線洩壓',type:'sweep-status',mult:.75,statusId:'weakened',weight:28,description:'全區洩壓並削弱隊伍。'},{label:'壓力超載',type:'enrage',attackBoost:.3,weight:20,description:'核心過載，後續攻擊更強。'}]}]},
  {area:'zone-3',id:'z3-boss-observer',name:'鏡後觀測者',hp:285,attack:25,defense:18,trait:'會生成錯誤鏡像；觀察可找出本體。',phases:[{at:1,label:'觀測階段',skills:[{label:'鏡像誤導',type:'guard',defenseBoost:4,weight:22,description:'大量鏡像遮蔽本體。'},{label:'反射刺擊',type:'heavy',mult:1.45,weight:20,description:'從錯位鏡面中突刺。'}]},{at:.5,label:'鏡後顯形',skills:[{label:'萬面同視',type:'sweep-status',mult:.62,statusId:'shaken',weight:28,description:'所有鏡面同時注視，造成傷害與動搖。'},{label:'本體重合',type:'heavy',mult:1.75,weight:22,description:'鏡像與本體重合後重擊。'}]}]},
  {area:'zone-4',id:'z4-boss-darkness',name:'失照吞行者',hp:320,attack:28,defense:19,trait:'HP 越低，場景照明越弱。',phases:[{at:1,label:'殘光區',skills:[{label:'吞光撕咬',type:'heavy',mult:1.45,weight:22,description:'吞噬照明後撲擊。'},{label:'熄燈',type:'status',mult:.5,statusId:'shaken',weight:20,description:'使目標失去方向感。'}]},{at:.45,label:'完全失照',skills:[{label:'黑域吞沒',type:'sweep',mult:.9,weight:30,description:'黑暗吞沒全隊。'},{label:'獵殺標記',type:'status',mult:.65,statusId:'marked',weight:22,description:'在黑暗中標記獵物。'}]}]},
  {area:'zone-5',id:'z5-boss-tide',name:'沉潮母體',hp:350,attack:30,defense:20,trait:'潮位會週期性改變安全區域。',phases:[{at:1,label:'退潮',skills:[{label:'潮肢掃蕩',type:'sweep',mult:.72,weight:22,description:'潮肢掃過甲板。'},{label:'拖入潮溝',type:'status',mult:.58,statusId:'slowed',weight:20,description:'拖慢一名隊員。'}]},{at:.5,label:'滿潮',skills:[{label:'沉潮覆頂',type:'sweep-status',mult:.76,statusId:'contaminated',weight:28,description:'黑潮覆蓋全場並造成污染。'},{label:'母體震潮',type:'heavy',mult:1.7,weight:22,description:'以潮壓震擊單一目標。'}]}]},
  {area:'zone-6',id:'z6-boss-corridor',name:'第零號房間',hp:380,attack:32,defense:21,trait:'每階段改寫戰場規則與出口方向。',phases:[{at:1,label:'可辨識房間',skills:[{label:'錯門夾擊',type:'sweep',mult:.7,weight:22,description:'兩側錯門同時閉合。'},{label:'路徑抹除',type:'status',mult:.5,statusId:'slowed',weight:20,description:'抹除目標的移動路徑。'}]},{at:.5,label:'第零房',skills:[{label:'空間摺疊',type:'sweep-status',mult:.72,statusId:'shaken',weight:28,description:'房間摺疊，造成全隊傷害與動搖。'},{label:'出口歸零',type:'guard',defenseBoost:6,weight:18,description:'所有出口消失，防禦大幅提高。'}]}]},
  {area:'zone-7',id:'z7-boss-cure',name:'被宣布痊癒者',hp:410,attack:34,defense:22,trait:'會吸收感染標記恢復生命。',phases:[{at:1,label:'觀察期',skills:[{label:'病徵轉移',type:'status',mult:.55,statusId:'contaminated',weight:22,description:'將污染轉移到隊員。'},{label:'隔離抓擊',type:'heavy',mult:1.45,weight:20,description:'強制拖離一名隊員。'}]},{at:.5,label:'痊癒宣告',skills:[{label:'集體復發',type:'sweep-status',mult:.72,statusId:'bleeding',weight:28,description:'全隊病徵同時復發。'},{label:'錯誤康復',type:'enrage',attackBoost:.32,weight:20,description:'異常「康復」讓力量進一步上升。'}]}]},
  {area:'zone-8',id:'z8-boss-star',name:'寂星回應體',hp:450,attack:37,defense:23,trait:'會預先回應下一回合的玩家選擇。',phases:[{at:1,label:'延遲回應',skills:[{label:'遠訊預答',type:'status',mult:.58,statusId:'marked',weight:22,description:'先標記一個尚未發生的行動。'},{label:'星間回波',type:'sweep',mult:.75,weight:22,description:'遠距回波掃過全隊。'}]},{at:.4,label:'即時回應',skills:[{label:'因果先行',type:'sweep-status',mult:.8,statusId:'shaken',weight:30,description:'回應在選擇之前發生。'},{label:'寂星坍縮',type:'heavy',mult:1.85,weight:24,description:'將遠訊壓縮為高強度單體打擊。'}]}]}
];
module.exports = { BOSSES };
