const R=(slash,blunt,pierce)=>({slash,blunt,pierce});
const P=(at,label,skills)=>({at,label,skills});
const B=(area,id,name,hp,attack,defense,trait,resistances,phases)=>({area,id,name,hp,attack,defense,trait,resistances,phases});
const BOSSES=[
 B('zone-1','z1-boss-cashier','永不結帳的收銀員',220,20,15,'會把累積的「帳款」轉成全體傷害。',R(.75,1.35,1),[P(1,'營業中',[{label:'結帳掃擊',type:'sweep',mult:.68,weight:20,description:'收銀帶橫掃全隊。'},{label:'找零護欄',type:'shield',shield:28,weight:16,description:'升起櫃檯護板，獲得護盾。'}]),P(.5,'最後結帳',[{label:'帳款清算',type:'sweep',mult:.95,weight:30,description:'把累積帳款化為全體高傷害。'},{label:'拒絕退款',type:'enrage',attackBoost:.25,weight:18,description:'拒絕結束營業，攻擊提高。'}])]),
 B('zone-1','z1-boss-customer','櫥窗中的最後顧客',205,21,16,'會在櫥窗與走道之間交換位置。',R(1.35,.75,1),[P(1,'試穿',[{label:'玻璃割裂',type:'heavy',mult:1.4,weight:22,description:'從櫥窗碎片間突進。'},{label:'展示櫃封鎖',type:'shield',shield:24,weight:18,description:'以櫥窗殘片構成護盾。'}]),P(.45,'閉店後',[{label:'整排櫥窗崩落',type:'sweep-status',mult:.72,statusId:'bleeding',weight:28,description:'大量玻璃崩落並造成流血。'},{label:'最後試穿',type:'heavy',mult:1.75,weight:22,description:'鎖定一名隊員猛烈衝撞。'}])]),
 B('zone-1','z1-boss-broadcast','百貨閉店廣播塔',230,19,17,'廣播會反覆宣告不存在的撤離路線。',R(1,.75,1.35),[P(1,'閉店廣播',[{label:'錯誤疏散',type:'sweep-status',mult:.48,statusId:'shaken',weight:24,description:'錯誤指示讓全隊陷入動搖。'},{label:'廣播防火門',type:'shield',shield:32,weight:15,description:'落下防火門形成護盾。'}]),P(.5,'永久營業',[{label:'全館警報',type:'sweep',mult:.9,weight:28,description:'高強度警報震盪全場。'},{label:'強制留店',type:'status',mult:.6,statusId:'marked',weight:20,description:'標記一名隊員為留店對象。'}])]),
 B('zone-2','z2-boss-core','逆流維修核心',260,23,17,'高壓階段會交替封鎖不同類型行動。',R(.75,1.35,1),[P(1,'穩壓模式',[{label:'逆流脈衝',type:'sweep',mult:.72,weight:22,description:'管線壓力反向衝擊全隊。'},{label:'穩壓護殼',type:'shield',shield:34,weight:18,description:'壓力閥閉合並產生護盾。'}]),P(.55,'超壓模式',[{label:'全線洩壓',type:'sweep-status',mult:.75,statusId:'weakened',weight:28,description:'全區洩壓並削弱隊伍。'},{label:'壓力超載',type:'enrage',attackBoost:.3,weight:20,description:'核心過載，後續攻擊更強。'}])]),
 B('zone-2','z2-boss-pump','無限加壓泵組',275,22,19,'每次蓄壓都會增加下一次衝擊。',R(.7,1.35,1.1),[P(1,'增壓循環',[{label:'活塞重壓',type:'heavy',mult:1.5,weight:22,description:'大型活塞向單一目標砸下。'},{label:'壓力壁',type:'shield',shield:42,weight:20,description:'蒸汽壓力形成短暫護盾。'}]),P(.5,'失控增壓',[{label:'泵組共振',type:'sweep',mult:.86,weight:28,description:'整組泵浦同時震動。'},{label:'爆管噴射',type:'sweep-status',mult:.64,statusId:'bleeding',weight:22,description:'破裂管線掃過全隊。'}])]),
 B('zone-2','z2-boss-chain','牽引鏈主機',245,24,16,'牽引鏈會把隊員拖到危險機構前。',R(1,1.3,.75),[P(1,'牽引作業',[{label:'鏈鉤拖行',type:'status',mult:.62,statusId:'slowed',weight:24,description:'拖慢一名隊員。'},{label:'鏈網防護',type:'shield',shield:26,weight:16,description:'交錯鏈條形成護盾。'}]),P(.45,'過載捲收',[{label:'全線捲收',type:'sweep',mult:.92,weight:30,description:'所有牽引鏈同時收緊。'},{label:'斷鏈飛擊',type:'heavy',mult:1.78,weight:20,description:'斷裂鏈條高速抽擊單體。'}])]),
 B('zone-3','z3-boss-observer','鏡後觀測者',285,25,18,'會生成錯誤鏡像；觀察可找出本體。',R(1.35,.75,1),[P(1,'觀測階段',[{label:'鏡像誤導',type:'shield',shield:36,weight:22,description:'鏡像遮蔽本體並形成護盾。'},{label:'反射刺擊',type:'heavy',mult:1.45,weight:20,description:'從錯位鏡面中突刺。'}]),P(.5,'鏡後顯形',[{label:'萬面同視',type:'sweep-status',mult:.62,statusId:'shaken',weight:28,description:'所有鏡面同時注視。'},{label:'本體重合',type:'heavy',mult:1.75,weight:22,description:'鏡像與本體重合後重擊。'}])]),
 B('zone-3','z3-boss-specimen','無標籤母樣本',300,26,17,'會在受傷後散布污染組織。',R(.75,1,1.35),[P(1,'隔離培養',[{label:'樣本增殖',type:'shield',shield:30,weight:18,description:'增生組織包覆本體。'},{label:'培養液噴濺',type:'sweep-status',mult:.5,statusId:'contaminated',weight:24,description:'污染液噴向全隊。'}]),P(.48,'破艙逸散',[{label:'母體撕裂',type:'heavy',mult:1.72,weight:24,description:'伸展異常肢體撕裂單體。'},{label:'整層污染',type:'sweep-status',mult:.74,statusId:'contaminated',weight:28,description:'污染覆蓋整個戰場。'}])]),
 B('zone-3','z3-boss-seat','第七隔離觀測席',270,24,20,'觀測席會依玩家行動調整防護層。',R(1,1.35,.7),[P(1,'記錄中',[{label:'觀測光束',type:'heavy',mult:1.42,weight:22,description:'高能觀測光束集中於一人。'},{label:'隔離屏障',type:'shield',shield:46,weight:22,description:'隔離玻璃升起並形成厚重護盾。'}]),P(.5,'資料溢位',[{label:'記錄覆寫',type:'sweep-status',mult:.58,statusId:'marked',weight:24,description:'把全隊標記為觀測樣本。'},{label:'觀測終止',type:'heavy',mult:1.8,weight:24,description:'鎖定單一樣本執行終止。'}])]),
 B('zone-4','z4-boss-darkness','失照吞行者',320,28,19,'HP 越低，場景照明越弱。',R(1.35,1,.75),[P(1,'殘光區',[{label:'吞光撕咬',type:'heavy',mult:1.45,weight:22,description:'吞噬照明後撲擊。'},{label:'暗膜',type:'shield',shield:34,weight:18,description:'黑暗凝聚成防護膜。'}]),P(.45,'完全失照',[{label:'黑域吞沒',type:'sweep',mult:.9,weight:30,description:'黑暗吞沒全隊。'},{label:'獵殺標記',type:'status',mult:.65,statusId:'marked',weight:22,description:'在黑暗中標記獵物。'}])]),
 B('zone-4','z4-boss-train','黑軌列車殘影',335,29,18,'沿不存在的軌道高速來回衝撞。',R(.75,1.35,1),[P(1,'進站',[{label:'殘影撞擊',type:'sweep',mult:.74,weight:24,description:'列車殘影橫掃全隊。'},{label:'車體殘像',type:'shield',shield:38,weight:18,description:'多重車體殘像形成護盾。'}]),P(.5,'不停靠',[{label:'末班直行',type:'heavy',mult:1.82,weight:24,description:'高速直線撞擊單體。'},{label:'隧道真空',type:'sweep-status',mult:.62,statusId:'slowed',weight:26,description:'真空拖慢全隊。'}])]),
 B('zone-4','z4-boss-beast','無燈巡行巨獸',305,30,17,'會循著聲音尋找最近的獵物。',R(1,.75,1.35),[P(1,'巡行',[{label:'循聲撲殺',type:'heavy',mult:1.5,weight:24,description:'朝聲源猛烈撲擊。'},{label:'角質暗甲',type:'shield',shield:30,weight:16,description:'暗色角質層形成護盾。'}]),P(.42,'狂獵',[{label:'無燈奔襲',type:'sweep',mult:.94,weight:30,description:'在完全黑暗中橫衝直撞。'},{label:'獵物定位',type:'status',mult:.55,statusId:'marked',weight:20,description:'鎖定下一個獵物。'}])]),
 B('zone-5','z5-boss-tide','沉潮母體',350,30,20,'潮位會週期性改變安全區域。',R(.75,1.35,1),[P(1,'退潮',[{label:'潮肢掃蕩',type:'sweep',mult:.72,weight:22,description:'潮肢掃過甲板。'},{label:'潮膜',type:'shield',shield:40,weight:18,description:'厚重潮膜形成護盾。'}]),P(.5,'滿潮',[{label:'沉潮覆頂',type:'sweep-status',mult:.76,statusId:'contaminated',weight:28,description:'黑潮覆蓋全場。'},{label:'母體震潮',type:'heavy',mult:1.7,weight:22,description:'以潮壓震擊單一目標。'}])]),
 B('zone-5','z5-boss-whale','錨鏈鯨骸',370,31,22,'巨大骨骸拖著整串鏽蝕錨鏈。',R(1.35,.7,1),[P(1,'擱淺',[{label:'錨鏈橫掃',type:'sweep',mult:.76,weight:24,description:'鏽蝕錨鏈橫掃碼頭。'},{label:'肋骨護籠',type:'shield',shield:50,weight:22,description:'骨架收攏形成護盾。'}]),P(.5,'再度下沉',[{label:'鯨骸翻覆',type:'sweep',mult:.96,weight:28,description:'巨大骨骸翻覆全場。'},{label:'深海拖曳',type:'status',mult:.62,statusId:'slowed',weight:22,description:'拖走一名隊員。'}])]),
 B('zone-5','z5-boss-beacon','溺港引潮燈',330,29,21,'燈光會把黑潮與漂流物引向隊伍。',R(1,1.35,.75),[P(1,'引潮',[{label:'潮光聚焦',type:'status',mult:.55,statusId:'marked',weight:22,description:'以燈光標記目標。'},{label:'防浪罩',type:'shield',shield:44,weight:20,description:'厚玻璃罩形成護盾。'}]),P(.45,'燈塔傾覆',[{label:'引潮爆閃',type:'sweep-status',mult:.68,statusId:'shaken',weight:26,description:'強光與黑潮同時襲來。'},{label:'燈柱倒塌',type:'heavy',mult:1.85,weight:24,description:'整根燈柱向單體砸落。'}])]),
 B('zone-6','z6-boss-corridor','第零號房間',380,32,21,'每階段改寫戰場規則與出口方向。',R(1,.75,1.35),[P(1,'可辨識房間',[{label:'錯門夾擊',type:'sweep',mult:.7,weight:22,description:'兩側錯門同時閉合。'},{label:'牆面閉合',type:'shield',shield:46,weight:20,description:'牆面收攏形成護盾。'}]),P(.5,'第零房',[{label:'空間摺疊',type:'sweep-status',mult:.72,statusId:'shaken',weight:28,description:'房間摺疊。'},{label:'出口歸零',type:'shield',shield:58,weight:18,description:'所有出口消失，防護大幅提高。'}])]),
 B('zone-6','z6-boss-warden','無窗管理員',365,33,20,'會把隊員分配到不存在的房間。',R(.75,1.35,1),[P(1,'查房',[{label:'門牌點名',type:'status',mult:.52,statusId:'marked',weight:22,description:'標記一名隊員。'},{label:'管理門',type:'shield',shield:40,weight:18,description:'重門封閉形成護盾。'}]),P(.48,'封樓',[{label:'整層鎖閉',type:'sweep',mult:.88,weight:28,description:'所有門同時關閉。'},{label:'錯房處置',type:'heavy',mult:1.78,weight:22,description:'把單體壓入錯誤房間。'}])]),
 B('zone-6','z6-boss-fold','迴廊摺疊體',395,31,22,'本體就是一段不斷折疊的走廊。',R(1.35,1,.7),[P(1,'折角',[{label:'牆角切斷',type:'heavy',mult:1.48,weight:22,description:'走廊折角像刀刃般切下。'},{label:'重疊空間',type:'shield',shield:52,weight:20,description:'重疊空間吸收傷害。'}]),P(.5,'無限迴圈',[{label:'全域折返',type:'sweep-status',mult:.72,statusId:'slowed',weight:28,description:'全隊被拉回錯誤位置。'},{label:'空間壓扁',type:'sweep',mult:.92,weight:26,description:'整段迴廊向內壓縮。'}])]),
 B('zone-7','z7-boss-cure','被宣布痊癒者',410,34,22,'會吸收感染標記恢復力量。',R(1.35,.75,1),[P(1,'觀察期',[{label:'病徵轉移',type:'status',mult:.55,statusId:'contaminated',weight:22,description:'將污染轉移到隊員。'},{label:'隔離護衣',type:'shield',shield:44,weight:18,description:'隔離層形成護盾。'}]),P(.5,'痊癒宣告',[{label:'集體復發',type:'sweep-status',mult:.72,statusId:'bleeding',weight:28,description:'全隊病徵同時復發。'},{label:'錯誤康復',type:'enrage',attackBoost:.32,weight:20,description:'異常康復提高力量。'}])]),
 B('zone-7','z7-boss-doctor','封鎖區廣播醫師',390,35,21,'透過全城廣播發布錯誤醫療指令。',R(.75,1,1.35),[P(1,'遠端診療',[{label:'錯誤處方',type:'status',mult:.55,statusId:'weakened',weight:24,description:'錯誤醫療指令削弱目標。'},{label:'隔離簾',type:'shield',shield:38,weight:18,description:'層層隔離簾形成護盾。'}]),P(.45,'強制痊癒',[{label:'全區廣播',type:'sweep-status',mult:.68,statusId:'shaken',weight:28,description:'廣播覆蓋整個區域。'},{label:'緊急處置',type:'heavy',mult:1.82,weight:22,description:'對單一目標執行激烈處置。'}])]),
 B('zone-7','z7-boss-incubator','灰疫孵化塔',430,33,23,'持續製造感染組織與孵化物。',R(1,1.35,.75),[P(1,'孵化',[{label:'孢囊爆裂',type:'sweep-status',mult:.52,statusId:'contaminated',weight:24,description:'孢囊破裂污染全隊。'},{label:'孵化殼',type:'shield',shield:56,weight:22,description:'外層孵化殼形成厚盾。'}]),P(.5,'群落成熟',[{label:'灰疫潮',type:'sweep-status',mult:.78,statusId:'bleeding',weight:28,description:'成熟感染組織席捲全場。'},{label:'群落收縮',type:'heavy',mult:1.72,weight:22,description:'整座孵化塔向單體收縮。'}])]),
 B('zone-8','z8-boss-star','寂星回應體',450,37,23,'會預先回應下一回合的玩家選擇。',R(.75,1,1.35),[P(1,'延遲回應',[{label:'遠訊預答',type:'status',mult:.58,statusId:'marked',weight:22,description:'先標記一個尚未發生的行動。'},{label:'星幕',type:'shield',shield:50,weight:18,description:'星間訊號形成護盾。'}]),P(.4,'即時回應',[{label:'因果先行',type:'sweep-status',mult:.8,statusId:'shaken',weight:30,description:'回應在選擇之前發生。'},{label:'寂星坍縮',type:'heavy',mult:1.85,weight:24,description:'遠訊壓縮為高強度單體打擊。'}])]),
 B('zone-8','z8-boss-orrery','逆時天文儀',465,36,25,'齒輪會逆轉已發生的攻擊軌跡。',R(1.35,.75,1),[P(1,'逆行觀測',[{label:'逆時針刺',type:'heavy',mult:1.5,weight:22,description:'逆向齒輪刺向單體。'},{label:'時間殼層',type:'shield',shield:62,weight:22,description:'時間層疊形成厚盾。'}]),P(.5,'時間倒灌',[{label:'昨日重演',type:'sweep',mult:.9,weight:28,description:'重演上一輪衝擊。'},{label:'秒針斷裂',type:'sweep-status',mult:.65,statusId:'slowed',weight:24,description:'破碎秒針拖慢全隊。'}])]),
 B('zone-8','z8-boss-satellite','最後觀測衛星',440,38,22,'持續從不可見軌道修正攻擊落點。',R(1,.7,1.35),[P(1,'軌道鎖定',[{label:'軌道標定',type:'status',mult:.52,statusId:'marked',weight:22,description:'標記一名隊員。'},{label:'再入護罩',type:'shield',shield:48,weight:18,description:'熱障形成護盾。'}]),P(.42,'墜落軌道',[{label:'衛星殘骸雨',type:'sweep',mult:.94,weight:30,description:'大量殘骸墜落。'},{label:'最終觀測束',type:'heavy',mult:1.9,weight:24,description:'高能光束貫穿單體。'}])])
];
module.exports={BOSSES};
