const R=(slash,blunt,pierce)=>({slash,blunt,pierce});
const ELITE_ENEMIES = [
  {area:'zone-1',id:'z1-elite-mannequin',name:'封店模特',hp:92,attack:15,defense:14,resistances:R(1.35,.75,1),trait:'接縫與布料結構怕斬擊。',skills:[{label:'展示櫃突進',type:'heavy',mult:1.45,weight:22,description:'高速撞向一名隊員。'},{label:'無人注視',type:'guard',defenseBoost:4,weight:18,description:'姿態凝固，提高防禦。'}]},
  {area:'zone-2',id:'z2-elite-boiler',name:'過壓鍋爐獸',hp:108,attack:18,defense:15,resistances:R(.7,1.4,1),trait:'厚重金屬殼抗斬，鈍擊可震裂壓力結構。',skills:[{label:'蒸汽噴發',type:'sweep',mult:.75,weight:24,description:'高壓蒸汽掃過全隊。'},{label:'超壓蓄能',type:'enrage',attackBoost:.24,weight:16,description:'持續升壓，提高後續攻擊。'}]},
  {area:'zone-3',id:'z3-elite-twin',name:'雙生觀測體',hp:116,attack:19,defense:16,resistances:R(1,.75,1.35),trait:'觀測核心狹窄，突擊能精準刺穿。',skills:[{label:'雙重投影',type:'sweep-status',mult:.55,statusId:'shaken',weight:22,description:'錯位影像攻擊全隊並擾亂精神。'},{label:'觀測鎖定',type:'status',mult:.6,statusId:'marked',weight:20,description:'鎖定一名隊員。'}]},
  {area:'zone-4',id:'z4-elite-stalker',name:'無燈追獵者',hp:128,attack:22,defense:17,resistances:R(1.35,1,.75),trait:'高速獵殺型態怕大範圍斬擊，突擊容易落空。',skills:[{label:'熄燈獵殺',type:'heavy',mult:1.6,weight:24,description:'利用黑暗進行致命突襲。'},{label:'遁入失照',type:'guard',defenseBoost:5,weight:18,description:'消失在失照區，提高防禦。'}]},
  {area:'zone-5',id:'z5-elite-anchor',name:'沉錨巨殼',hp:142,attack:24,defense:19,resistances:R(.7,1.4,1),trait:'極厚甲殼抗斬，鈍擊能打碎承力層。',skills:[{label:'沉錨橫掃',type:'sweep',mult:.8,weight:24,description:'巨大的錨肢橫掃全隊。'},{label:'深殼閉鎖',type:'guard',defenseBoost:5,weight:18,description:'封閉外殼。'}]},
  {area:'zone-6',id:'z6-elite-room',name:'活動房間',hp:150,attack:25,defense:18,resistances:R(.75,1.35,1),trait:'整體空間結構可被鈍擊震鬆，刃器難以造成有效破壞。',skills:[{label:'牆面合攏',type:'sweep',mult:.72,weight:24,description:'整個房間向內擠壓。'},{label:'出口錯置',type:'sweep-status',mult:.45,statusId:'slowed',weight:20,description:'錯置出口並使全隊遲滯。'}]},
  {area:'zone-7',id:'z7-elite-doctor',name:'灰疫宣告者',hp:158,attack:27,defense:18,resistances:R(1.35,1,.75),trait:'污染組織脆化，斬擊能有效切除異變部位。',skills:[{label:'診斷：惡化',type:'status',mult:.65,statusId:'contaminated',weight:25,description:'施加污染。'},{label:'強制隔離',type:'status',mult:.7,statusId:'marked',weight:20,description:'標記一名隊員為隔離目標。'}]},
  {area:'zone-8',id:'z8-elite-oracle',name:'逆時預報機',hp:172,attack:29,defense:20,resistances:R(.75,1,1.4),trait:'核心深藏於機殼內，突擊最容易穿透。',skills:[{label:'預報命中',type:'heavy',mult:1.65,weight:24,description:'先宣告結果，再執行高傷害打擊。'},{label:'時序覆寫',type:'enrage',attackBoost:.28,weight:18,description:'改寫攻擊序列，提升後續威力。'}]}
];
module.exports = { ELITE_ENEMIES };
