const R=(id,name,rarity,buildTags,description,effects={})=>({id,name,rarity,buildTags,description,effects});
const EXPEDITION_RELICS=[
  R('relic-whetstone','破碎磨刀石','common',['weakness'],'斬擊命中弱點時傷害提高。',{damageTypeBonus:{slash:.14},weaknessOnly:true}),
  R('relic-impact-core','裂紋衝擊核','common',['weakness','break'],'鈍擊對部位與護盾更有效。',{damageTypeBonus:{blunt:.10},partBonus:.14,shieldBreakBonus:.18}),
  R('relic-needle-eye','穿芯針眼','common',['weakness','break'],'突擊無視部分防禦，對部位額外增傷。',{damageTypeBonus:{pierce:.08},ignoreDefense:1,partBonus:.12}),
  R('relic-blood-contract','血色契約','uncommon',['bleed','lowhp'],'HP 越低攻擊越高；受到治療略微降低。',{lowHpDamageBonus:.28,healingMult:.88}),
  R('relic-rusted-hook','鏽蝕鉤片','common',['bleed'],'斬擊技能有機率施加流血。',{onSlashBleedChance:.28}),
  R('relic-coagulated-bead','凝固血珠','rare',['bleed','cooldown'],'攻擊流血敵人時，22% 機率下回合多抽 1 張（額外上限 2）。',{bleedCooldownChance:.22}),
  R('relic-first-layer','不完整防護層','common',['shield'],'每場戰鬥開始獲得護盾。',{combatStartShield:12}),
  R('relic-return-shell','回震護殼','uncommon',['shield'],'有護盾時造成的傷害提高。',{shieldedDamageBonus:.14}),
  R('relic-broken-buckle','斷裂束帶','rare',['shield','break'],'有護盾時傷害提高，且攻擊部位時額外增傷。',{shieldedDamageBonus:.08,partBonus:.16}),
  R('relic-marking-lens','紅點標記鏡','common',['mark'],'攻擊已標記敵人時傷害提高。',{markedDamageBonus:.18}),
  R('relic-hunting-order','獵殺指令紙','uncommon',['mark','weakness'],'命中標記目標的弱點時再追加傷害。',{markedWeaknessBonus:.14}),
  R('relic-command-chain','同步指揮鏈','rare',['mark'],'隊友攻擊你已標記的敵人時獲得小幅增傷。',{partyMarkedBonus:.10}),
  R('relic-loose-screw','鬆動螺帽','common',['break'],'部位傷害提高。',{partBonus:.18}),
  R('relic-rupture-gauge','斷裂壓力計','uncommon',['break'],'破壞部位後，自己獲得護盾。',{shieldOnPartBreak:10}),
  R('relic-interruptor','中斷器','rare',['break','cooldown'],'成功阻擋蓄力攻擊後，下回合多抽 1 張（額外上限 2）。',{cooldownOnBlock:1}),
  R('relic-noise-filter','失真濾波器','common',['control'],'對帶負面狀態的敵人造成更多傷害。',{debuffDamageBonus:.12}),
  R('relic-seal-tape','異常封條','uncommon',['control'],'施加負面狀態時延長 1 回合。',{debuffDurationBonus:1}),
  R('relic-static-cage','靜電拘束籠','rare',['control','shield'],'敵人處於負面狀態時，你受到的傷害降低。',{debuffedEnemyDamageTakenMult:.90}),
  R('relic-danger-meter','破表危險計','common',['danger'],'危險度越高，傷害小幅提高。',{dangerDamagePerPoint:.025}),
  R('relic-black-ticket','黑色通行證','uncommon',['danger','economy'],'高危險度時戰鬥金幣提高。',{highDangerGoldMult:1.22}),
  R('relic-red-zone','紅區契印','rare',['danger','weakness'],'危險度 5 以上時，命中弱點額外增傷。',{highDangerWeaknessBonus:.20}),
  R('relic-spare-battery','超載電池','uncommon',['cooldown'],'發動罪孽共鳴技能後，下回合多抽 1 張（額外上限 2）。',{firstSkillCooldownReduction:1}),
  R('relic-loop-key','循環鑰匙','rare',['cooldown'],'擊殺敵人時，下回合多抽 1 張（額外上限 2）。',{cooldownOnKill:1}),
  R('relic-coupon','破損折價券','common',['economy'],'戰鬥取得金幣增加。',{goldMult:1.15}),
  R('relic-ledger','染血收據','uncommon',['economy','lowhp'],'戰鬥結束時依本場損失 HP 額外取得金幣。',{goldPerLostHp:.18}),
  R('relic-vending-chip','販賣機代幣','rare',['economy','consumable'],'商店消耗品價格降低，使用道具效果提高。',{consumableDiscount:.18,consumablePower:.18}),
  R('relic-medical-tag','急救識別牌','common',['consumable'],'治療型消耗品效果提高。',{consumablePower:.20}),
  R('relic-recycling-bag','回收物資袋','uncommon',['consumable','economy'],'使用消耗品後有機率返還少量金幣。',{consumableRefundChance:.35,consumableRefundGold:8}),
  R('relic-scatter-node','散射節點','common',['aoe'],'範圍攻擊傷害提高。',{aoeDamageBonus:.12}),
  R('relic-cleanup-protocol','清場協議','uncommon',['aoe','cooldown'],'擊殺小怪後，下回合多抽 1 張（額外上限 2）。',{cooldownOnMinionKill:1}),
  R('relic-last-spark','最後火花','rare',['lowhp'],'HP 30% 以下時大幅提高傷害，但不提高防禦。',{criticalHpDamageBonus:.32})
];
function getRelic(id){return EXPEDITION_RELICS.find(r=>r.id===id)||null;}
module.exports={EXPEDITION_RELICS,getRelic};
